### ISSUE TITLE
incorrect work when using web/tunnel

### ISSUE THREAD

**Issue by Andrysky** [codota/tabnine-vscode#1009]
hello I don't know if it's your fault or vs code.

- OS version:  Win 11 22h2
- Editor version Visual Studio Code, Version: 1.74.2, 
- Programming language: -
- TabNine extension version: 3.6.35

**Issue Details:**
steps to reproduce:
1) on host1 run code-server serve-local --host 0.0.0.0
2) on host2 connect by given url(host1)
3) on host2 in accounts press signin with tabnine 

result:
signin page open on host1
expected:
signin page open on host2

4) press tabnine starter

result:
opening empty page

![image](https://user-images.githubusercontent.com/5894390/210742705-b6fe1cd8-aae6-4117-bf73-7a9583d08163.png)

if on step 1 run code tunel - result on 
step 3 - same
step 4 - Invalid secret
![image](https://user-images.githubusercontent.com/5894390/210743711-1fbb2eaa-884b-41de-8fce-4e53913811bc.png)

gz#20585

**Comment by TzufTabnine** [comment]
@dimacodota @amirbilu

**Comment by TzufTabnine** [comment]
Hi @Andrysky,
Thanks for the info, we are working on it.
In the meantime, if you want to avoid that message, make sure you close host 1 while using host2 and try to open Tabnine Hub, then you should be able to open the Hub without seeing any error. Let me know if it is working.

**Comment by Andrysky** [comment]
@TzufTabnine 
everything is the same - the browser opens on host1 and not on host2, the settings do not open - an empty window (instead of an invalid secret)

**Comment by TzufTabnine** [comment]
@Andrysky 
Did you close host1 completely (VSCode and browser)? Try to close host2 as well and then open only host2. If it still not working, can you add a video here of the whole process that you are doing?

**Comment by Andrysky** [comment]
@TzufTabnine recorded a video https://drive.google.com/file/d/1mxxJnkLG75tIkZEn0tEQHnN31aQcgXCB/view?usp=sharing

**Comment by TzufTabnine** [comment]
Hi @Andrysky,
Thanks for the video.
Unfortunately, Tabnine is not supported on VS Code for the Web. that's why it is not working for you. If you do want to use Tabnine with VScode, you can do it locally.

**Comment by Andrysky** [comment]
@TzufTabnine 
is this a tabnine problem? or vscode?

if using vscode + Remote - Tunnels (https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server)
it turns out the same problem (- video
https://drive.google.com/file/d/1oJyEvBvlZKBj3KO646A5A571Cdy-x432/view?usp=share_link

**Comment by Andrysky** [comment]
@TzufTabnine 
I don't work locally, I have a weak computer, and it's not convenient to put the server under the table.
+ if you use Remote - SSH - then when using multiple computers - the tabs are not synchronized ( - they are stored locally and not remotely ( - and they don't want to fix it https://github.com/microsoft/vscode-remote-release/issues/7269#issuecomment-1268603967

, so I try to use "completely remote development"

**Comment by TzufTabnine** [comment]
@Andrysky
We are not fully supporting Code Server at the momet. we are working on that feature
