### ISSUE TITLE
Tabnine prevents autoImport from working in VSCode

### ISSUE THREAD

**Issue by TheBunyip** [codota/tabnine-vscode#1012]
- OS version: OSX Ventura 13.1
- Editor version: 1.74.2
- Programming language: Typescript
- TabNine extension version: Published on 01/10/2018, 05:21:45

**Issue Details:**

VSCode's autoImport feature does not work when Tabnine is enabled.  Setting `tabnine.experimentalAutoImports` to `true` appears to have no effect (i.e. it doesn't work).

According to this closed issue (https://github.com/codota/tabnine-vscode/issues/74) this problem was fixed, but several people (on that issue, and on https://github.com/codota/tabnine-vscode/issues/44) are reporting that it still does not work.  

EDIT: it seems to work for a bit after I restart VSCode.  Then after around 30 minutes of use the auto import VSCode suggestions just stop coming up.

gz#20680

**Comment by TzufTabnine** [comment]
@dimacodota

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20680'>Zendesk ticket #20680</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20680'>Zendesk ticket #20680</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @TheBunyip,
Can you please send us some screenshots/videos of the issue?
