### ISSUE TITLE
when I use TabNine in vscode, I can't rename my folders or files.

### ISSUE THREAD

**Issue by jadelxy1997** [codota/tabnine-vscode#1013]
- OS version: Win 11
- Editor version : vscode 1.74.3
- Programming language:  python
- TabNine extension version: 
Published 10/1/2018, 12:21:45
Last released 1/4/2023, 19:58:53
Last updated 1/4/2023, 20:42:39
Identifier tabnine.tabnine-vscode

**Issue Details:**

![8cfdc40cb7133825a0c5dcb4d3eca09](https://user-images.githubusercontent.com/54530758/211803390-e7925864-709a-47b1-aeba-896ad0ddaf6c.png)
![3e89eb41ff95fb09f82c7bae49efbf9](https://user-images.githubusercontent.com/54530758/211803414-16b99e65-21a2-4b91-a644-e9142a295b32.png)

this folder is occupied by TabNine.exe

gz#20704

**Comment by TzufTabnine** [comment]
@dimacodota

**Comment by TzufTabnine** [comment]
@ofekby

**Comment by jadelxy1997** [comment]
> Hi @jadelxy1997, You should be able to rename your folders while using Tabnine, we can't replicate that issue on our side.

OK! TabNine takes up a lot of memory,is it normal?

![image](https://user-images.githubusercontent.com/54530758/213451429-781565d3-27ab-4975-b763-ceb1ff98db0a.png)

**Comment by TzufTabnine** [comment]
@jadelxy1997 If you are working on a 'Local Machine', on the Model Serving mode, it might use a lot of memory (running the model locally). If you wish to use less memory and get better results choose 'Cloud' mode, for example :
![Screenshot_174](https://user-images.githubusercontent.com/121427912/213907300-ed4da62b-1775-4108-aef5-a85662b138e1.png).
It is possible only for a Pro/Enterprise subscription.

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20704'>Zendesk ticket #20704</a>)</i>
