### ISSUE TITLE
Tabnine is not working.

### ISSUE THREAD

**Issue by raykle** [codota/tabnine-vscode#1015]
**please complete the following information:**

- OS version: macOS Monterey 12.6.1, Darwin arm64 21.6.0
- Editor version:
  [VS Code]:
  Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:05:47.808Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
- Programming language: ts, js, ...
- TabNine extension version: TabNine.tabnine-vscode 3.6.36

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

I can open the page throw `TabNine::config` and it works as usual:

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/3097366/212620585-c72daa21-c0ff-46a1-8c95-3958255c0a6c.png">

But when I open the `tabnine settings` it's blank:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/3097366/212620094-06210c60-a9d3-4e2d-910d-3f1451059a8e.png">

 And the dev tools in VS Code show errors :

![image](https://user-images.githubusercontent.com/3097366/212619863-c6b4368e-e2ea-4c10-87fd-9ec9f442a9bc.png)
![image](https://user-images.githubusercontent.com/3097366/212619873-6d65c0ce-71d3-4168-b8cb-ead91c253474.png)

gz#20798

**Comment by TzufTabnine** [comment]
Hi @raykle please restart your IDE, should be fine now. Thanks for letting us know.

**Comment by raykle** [comment]
@TzufTabnine Yes. It works now. 👍
