### ISSUE TITLE
TabNine not provide any suggestion these days

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [codota/tabnine-vscode#1019]
**please complete the following information:**

- OS version: Windows 10 22H2
- Editor version: 1.74.3
- Programming language: c++
- TabNine extension version: 3.6.38

**If the issue is related to TabNine failure, please provide log files:**
```
[Extension Host] Error: Binary request timed out
```
Type `TabNine::config` in your editor, the logs are located at the bottom of the page

This page contains no log related information

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

I've seen this error before, in your uncompleted Visual Studio (not Code) extension.  
I assume your developer set a very low request timeout,  
if TabNine didn't response within 50 ms, for example,  
the extension just gives up to receive generated results.

Are you guys just using a supercomputer located inside your data center?  
This is mad.

gz#21062<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21062'>Zendesk ticket #21062</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21062'>Zendesk ticket #21062</a>)</i>

**Comment by mhtvsSFrpHdE** [comment]
https://github.com/tabnine/tabnine-visual-studio/issues/7#issuecomment-1261222042

`Binary has failed to respond to request` bingo.

Exactly same error.

What I did that day is just increased `BinaryRequestTimeoutMillis` to 3000,  
then that extension is worked. Hard to not think today we faced the same problem.

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21062'>Zendesk ticket #21062</a>)</i>

**Comment by TzufTabnine** [comment]
@mhtvsSFrpHdE 
Can you please send your config file to support@tabnine.com?
See how to find the file [here](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)

**Comment by mhtvsSFrpHdE** [comment]
> @mhtvsSFrpHdE Can you please send your config file to [support@tabnine.com](mailto:support@tabnine.com)? See how to find the file [here](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)

Request received 21119

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21062'>Zendesk ticket #21062</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21062'>Zendesk ticket #21062</a>)</i>

**Comment by mhtvsSFrpHdE** [comment]
> (related to [Zendesk ticket #21062](https://tabninedesk.zendesk.com/agent/tickets/21062))

If I open it and login zendesk, says

oops
The page you were looking for doesn't exist

You may have mistyped the address or the page may have moved
Take me back to the home page

**Comment by mhtvsSFrpHdE** [comment]
Both cloud and local work today, thank you.
