### ISSUE TITLE
Tabnine can't connect to server

### ISSUE THREAD

**Issue by Miskamyasa** [codota/tabnine-vscode#1023]
**please complete the following information:**

- OS version: Mac OS Monterey 12.6.2
- Editor version VSCodium 1.75.0
- Programming language: ts
- TabNine extension version: 

  | 3.6.38
-- | --

**If the issue is related to TabNine failure, please provide log files:**
There is no logs

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**
No error log

Help -> Toggle Developer Tools

**Issue Details:**
<img width="321" alt="image" src="https://user-images.githubusercontent.com/16611383/217909602-89d438f9-82d1-4053-8bac-d799f8df1e54.png">

gz#21251<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21251'>Zendesk ticket #21251</a>)</i>

**Comment by yonip23** [comment]
Hi @Miskamyasa, thanks for reaching out!

Are you using a proxy / remote machine / any kind of setup that might require some additional steps to set up an internet connection properly?

Also, can you please attach the following data for us to troubleshoot your issue:
1. Your Tabnine engine logs
2. Your config file

You can find the how-to's [here](https://support.tabnine.com/hc/en-us/sections/5407690042897-How-to-debug-problems)
If you don't feel comfortable sharing it here, you can send it to support@tabnine.com, and we'll continue the discussion there.

Kind regards,
Yoni
