### ISSUE TITLE
Wrong roaming appdata location

### ISSUE THREAD

**Issue by mniesen** [codota/tabnine-vscode#1025]
**please complete the following information:**

- OS version: Window 10 22H2
- Editor version: Visual Studio Code 1.75.1
- Programming language: N/A
- TabNine extension version: 3.6.38

**Issue Details:**
Tabnine doesn't install properly. This is because the appdata path is wrong. Your using not using %appdata% as an environment variable but rather assuming that roaming appdata will be located on the C drive. In Windows you can use something called folder redirection, this allow for example to place the roaming appdata folder on a network drive. This is the case on my pc. When installing tabnine it creates a folder C:\fldrredir$\\{username}\AppData\Roaming\\..

fldrredir$\{username}\AppData\Roaming\ = the folder on a **network drive** where my roaming appdata is actually stored
{username} = actually my username is here

Tabnine assumes that in C:\fldrredir$\\{username}\AppData\Roaming\\.. my vscode folder is located which is not the case.
As a result I get errors that tabnine thinks that my internet connetion isn't working properly.

gz#21289<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21289'>Zendesk ticket #21289</a>)</i>

**Comment by yonip23** [comment]
Hi @mniesen, thanks for reaching out!
I appreciate your help with the investigation of the issue, but I suspect this might not be the case - As far as I can tell, we're using Windows' [KNOWNFOLDERID](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid) called `FOLDERID_RoamingAppData`:
![image](https://user-images.githubusercontent.com/67855609/218416709-009271a4-caff-48a9-a21c-7122bbf974de.png)

Are you using a proxy / remote machine / any kind of setup that might require some additional steps to set up an internet connection properly?

Also, can you please attach the following data for us to troubleshoot your issue:
1. Your Tabnine engine logs
2. Your config file

If you don't feel comfortable sharing it here, you can send it to support@tabnine.com, and we'll continue the discussion there.

Kind regards,
Yoni

**Comment by yonip23** [comment]
Thank you for sharing your logs, and the details you provided are indeed helpful 🙂 

Can you please try setting an environment variable called `TABNINE_BINARIES_DIR` to the desired location? I believe it should be `\\\\theNameOfTheServer\\fldrredir$\\myRealUsername\\AppData\\Roaming\\Code\\User\\globalStorage\\tabnine.tabnine-vscode\\binaries\\4.4.243\\x86_64-pc-windows-gnu\\`
Then, please:
1. close your IDE
2. kill all Tabnine processes (any of these if exists: `TabNine`, `TabNine-deep-local`, `TabNine-deep-cloud`, `WD-TabNine`)
3. Start your IDE
Let me know if this is of any help.

Kind regards,
Yoni

**Comment by mniesen** [comment]
Do I have to remove the extension before doing this and install it again afterwards?

**Comment by yonip23** [comment]
No need to uninstall and re-install - just follow the provided steps 🙂

**Comment by mniesen** [comment]
I set the environment variable and did the instructions, unfortunately without any success.
Note: the version of the binaries changed to 4.4.249 so I used this in the environment variable instead of 4.4.243.

**Comment by yonip23** [comment]
Can you please attach your binary and IDE logs?
IDE logs are available in Help -> Toggle Dev Tools -> console

I've opened an internal issue with your case, and our team will take a look and prioritize your issue.
We're sorry for the inconvenience, and thank you for reporting!

**Comment by mniesen** [comment]
By binary do you mean the contents of the binaries folder?

**Comment by yonip23** [comment]
I mean the log file similar to the one you attached earlier - `tabnine_rCURRENT.log-xxx` - please attach all of these log files (xxx is the process id, so every time you re-run your vscode a different log file will be created)

**Comment by mniesen** [comment]
[-18864_rCURRENT.log](https://github.com/codota/tabnine-vscode/files/10900031/-18864_rCURRENT.log)
[binaries.zip](https://github.com/codota/tabnine-vscode/files/10900050/binaries.zip)

**Comment by yonip23** [comment]
I'm sorry for not getting back to you sooner. Can you attach your IDE log file as well?
IDE logs are available in Help -> Toggle Dev Tools -> console

To get the relevant logs, please restart your IDE - you should see a log line that starts with `"spawning binary with command:"`.
Please attach all the logs you can get once you see this log line.

Kind regards.

**Comment by mniesen** [comment]
# Help -> Toggle Dev Tools -> console

### after installing ###
```
console.ts:137 [Extension Host] spawning binary with command:  \fldrredir$\myRealUsername\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.273\x86_64-pc-windows-gnu\TabNine.exe  args:  --client=vscode --no-lsp=true --log-file-path=h:\desktop\-4816 --client-metadata clientVersion=1.76.2 pluginVersion=3.6.43 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Default Dark+ Experimental vscode-theme-kind=Dark vscode-machine-id=d6eaafe42bd98d542bc14b65868b32233cd85bf88022ca10779385ebe05be213 vscode-is-new-app-install=false vscode-session-id=6c87f975-7fa2-4541-b8f7-236dea1bd8f81679379894821 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0

console.ts:137 [Extension Host] capabilities resolved immediately

console.ts:137 [Extension Host] No storagePath, languagetool-languageserver logging disabled.

console.ts:137 [Extension Host] Creating server
```
[Here](https://github.com/codota/tabnine-vscode/files/11025485/-4816_rCURRENT.log) is the log file associated with this launch.
### after restarting vscode ###
```
console.ts:137 [Extension Host] spawning binary with command:  \fldrredir$\myRealUsername\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.273\x86_64-pc-windows-gnu\TabNine.exe  args:  --print-version

console.ts:137 [Extension Host] spawning binary with command:  \fldrredir$\myRealUsername\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.273\x86_64-pc-windows-gnu\TabNine.exe  args:  --client=vscode --no-lsp=true --log-file-path=h:\desktop\-19352 --client-metadata clientVersion=1.76.2 pluginVersion=3.6.43 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Default Dark+ Experimental vscode-theme-kind=Dark vscode-machine-id=d6eaafe42bd98d542bc14b65868b32233cd85bf88022ca10779385ebe05be213 vscode-is-new-app-install=false vscode-session-id=db41a66a-daad-4aaa-82a8-7fe16113b9dd1679380107434 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0

console.ts:137 [Extension Host] activating extension

console.ts:137 [Extension Host] starting language server

log.ts:404   ERR [Extension Host] validating \fldrredir$\myRealUsername\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.273\x86_64-pc-windows-gnu\TabNine.exe timeout

console.ts:137 [Extension Host] validating \fldrredir$\myRealUsername\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.273\x86_64-pc-windows-gnu\TabNine.exe timeout

console.ts:137 [Extension Host] Express server listening on port: 50229
```
[Here](https://github.com/codota/tabnine-vscode/files/11025498/-19352_rCURRENT.log) is the log file associated with this launch.

**Comment by yonip23** [comment]
Thank you.
It looks like we have an issue in the vscode plugin, where we misinterpret the path in case it's not a local path.
I'll take it with my team and we'll prioritize a fix for this.

Kind regards

**Comment by mniesen** [comment]
I can still confirm that the problem is **not** solved, therefore I hope this problem will not we marked as stale. 
Two months ago there was mentioned that this would be prioritized.

**Comment by mniesen** [comment]
I can still confirm that the problem is not solved, therefore I hope this problem will not we marked as stale.
Two months ago there was mentioned that this would be prioritized.
