### ISSUE TITLE
TabNine works way better in Sublime

### ISSUE THREAD

**Issue by svipas** [codota/tabnine-vscode#103]
I don't know why, but I saw TabNine works way better in Sublime Text by giving way more suggestions, etc.

The configurations are exact same:
- Enabled **Deep TabNine Local**
- Enabled **Deep TabNine Cloud**

## Sublime Text 3:

![sublime](https://user-images.githubusercontent.com/10441177/82035361-15a49080-96a8-11ea-82fd-8f5d82012c52.png)

## VS Code:

<img width="647" alt="vscode" src="https://user-images.githubusercontent.com/10441177/82035373-19d0ae00-96a8-11ea-9598-3ec046a35c69.png">

**Both using same settings, latest TabNine, latest Sublime Text and VS Code**

I expect it to be like Sublime Text, even performance seems to be better in Sublime Text getting these suggestions.

**Comment by svipas** [comment]
I found this is because of this: https://github.com/codota/tabnine-vscode/blob/90d9887674f01b098d3eeda19ce8e335e17dca93/src/extension.ts#L128

Any reason why it's used in VS Code, but not in Sublime Text?

**Comment by dimacodota** [comment]
Hey @svipas, 
vscode uses a typescript language server to provide semantic completions, meaning that if you install a`@types/node` type definition you will get the semantic completions for the `fs` module, TabNine tries not to interfere with the semantic completions and suggest only(one) the most ranked completion.

<img width="1026" alt="Screen Shot 2020-05-15 at 23 29 10" src="https://user-images.githubusercontent.com/60742964/82093548-02bfa980-9704-11ea-851f-ba76dee27cd5.png">

**Comment by svipas** [comment]
Thanks @dimacodota for info. I decided to fork this extension and modify it to meet my needs.
