### ISSUE TITLE
I disabled tabnine long time ago, and now I can't enable it back

### ISSUE THREAD

**Issue by obrm** [codota/tabnine-vscode#1037]
- OS version: [e.g. Win 10, Mac Catalina] - windows 11 home
- Editor version [e.g. 1.45.0-insider]: 1.75.1
- Programming language: [e.g. js, ts, c++]: JS
- TabNine extension version: latest

I disabled tabnine a long time ago, and now I can't enable it back. It says that it is enabled globaly, but I don't get suggestions.

I can't find what I did, and now it's not working... 😭

I need it now so badly!

gz#21509<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21509'>Zendesk ticket #21509</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @obrm 
Are you behind Proxy/VPN/Firewall? - Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).

Please send to **support@tabnine.com** the following:
Config file -See [here](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location) where to find it.
Log files - See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that (for JetBrains) or for VSCode See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by amirbilu** [comment]
Please send us the log files. Please follow the steps **here**..
<br><p><em><small>°°°</small></em></p>
