### ISSUE TITLE
anti virus malware

### ISSUE THREAD

**Issue by Shawn2208** [codota/tabnine-vscode#1047]
now and again my antivirus program would notify me that tabnine is a risk of malware not sure if this is because my antivirus sucks or this program has malware ?

gz#21684<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21684'>Zendesk ticket #21684</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Shawn2208 
Tabnine is not malware. Which antivirus are you using?
Have you experienced this with other programs as well?

**Comment by Shawn2208** [comment]
@TzufTabnine that's what i thought too not sure whats going on to be honest. i'm using TotalAV. no just tabnine i keep getting notifications about malware then i get another notification saying its been sorted its ongoing issue. its most likely my AV.
