### ISSUE TITLE
Partial completion when text completion is also shown

### ISSUE THREAD

**Issue by BladeMF** [codota/tabnine-vscode#1070]
**please complete the following information:**

- OS version: Windows 11 Pro 22H2 22621.1413
- Editor version [e.g. 1.45.0-insider]: 1.76.2 (user setup)
- Programming language: [e.g. js, ts, c++] PHP
- TabNine extension version: 3.6.43

**If the issue is related to TabNine failure, please provide log files:**

_Not a failure._

**Editor console logs:**

_(No relevant log information)_

**Issue Details:**
When text completion window is open while a tabnine suggestion is shown and then tab is pressed, the completion is partial:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/12109622/227278319-93c206df-daaf-4d8c-a777-44bff9c7f36a.png">
After pressing Tab:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/12109622/227278398-d7f2b649-9051-45df-a509-204d75559c74.png">
If I remove the popup using Escape and _then_ press Tab, it works as expected.

gz#22295<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22295'>Zendesk ticket #22295</a>)</i>

**Comment by SimSimY** [comment]
Hey @BladeMF 

We are looking into this, I'll let you know once it's reloved.
