### ISSUE TITLE
Using tabnine-vscode caused LLVM error

### ISSUE THREAD

**Issue by Alloooshe** [codota/tabnine-vscode#1071]
Hi, I installed Tabnine-vscode extension on vs-code to test it on trial, I have a code that uses Pytorch 
Namely, I am locally loading the whisper model. 
after installation my code didn't work, I suspect the extension to be the cause :
I am getting the following error 

> : CommandLine Error: Option 'nvptx-no-f16-math' registered more than once!
>  LLVM ERROR: inconsistency in registered CommandLine options

I had it running normally before installing the extension.
obviously, the problem is related to LLVM, I uninstalled the extension, and still, the problem persists. 
are there any known issues with using Tabnine with python codes, and libs? 

**please complete the following information:**

- OS version: Ubuntu 
- Programming language: python
- TabNine extension version: latest
- nvidia rtx 3060 laptop
- cuda driver 525

gz#22352<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22352'>Zendesk ticket #22352</a>)</i>

**Comment by SimSimY** [comment]
Hey @Alloooshe,
TabNine doesn't modify your OS settings, and shouldn't leave any traces once uninstalled as such, and assuming you have restarted the laptop, the uninstalled exception can't cause the error.

**Comment by Alloooshe** [comment]
thanks found the issue to be in Qt multi threading
