### ISSUE TITLE
Automatically inserted closing bracket still not skipped (see #69)

### ISSUE THREAD

**Issue by rmplbv** [codota/tabnine-vscode#1078]
**please complete the following information:**

- OS version: Ubuntu 22.04 LTS
- Editor version [e.g. 1.45.0-insider]: VSCode 1.77.1 Release 23095
- Programming language: js
- TabNine extension version: 3.6.4

**Issue Details:**

Superfluous closing brackets are still introduced on tab-completion of tabnine suggestions.
According to #69, this should be fixed by https://github.com/codota/tabnine-vscode/pull/72.

See also other issues mentioned in #69, i.e. #47 and #60. 

gz#22741<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22741'>Zendesk ticket #22741</a>)</i>

**Comment by TzufTabnine** [comment]
@rmplbv Can you add an example (video/screenshot) of the issue here?

**Comment by rmplbv** [comment]
I'll try.
If you already have (closing) brackets, it basically happens almost every time.

**Comment by rmplbv** [comment]
Here's a demo video:

[demo.webm](https://user-images.githubusercontent.com/44094912/231970082-fd0efa10-b6bc-45db-bc8c-294379b57589.webm)
