### ISSUE TITLE
Tabnine status.bar it's not working 

### ISSUE THREAD

**Issue by ShaquibKhanhub** [codota/tabnine-vscode#1089]
**please complete the following information:**

- OS version: [e.g. Win 11, 22H2]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: javascript 
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**
Basically it's not giving me any suggestions 

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#23147<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23147'>Zendesk ticket #23147</a>)</i>

**Comment by TzufTabnine** [comment]
@ShaquibKhanhub 

Can you open Tabnine [Hub](https://support.tabnine.com/hc/en-us/articles/4413876147985-Tabnine-Hub-Where-to-find-it-and-how-to-sign-in)? Are you behind a [Proxy](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues)? Can you please send a screenshot of the issue?

**Comment by ShaquibKhanhub** [comment]
yes sure 
![image](https://user-images.githubusercontent.com/111151404/234792256-14764370-873f-44de-b1c0-5a9ce3225fed.png)

**Comment by ShaquibKhanhub** [comment]
for somedays i'm not getting any suggestions by TabNine it's very helpful but now it's not working help me with this

**Comment by ShaquibKhanhub** [comment]
it that what you're asking 
![image](https://user-images.githubusercontent.com/111151404/234796250-3535e7fd-7fb4-4125-a605-7b553f6a17d0.png)

**Comment by dimacodota** [comment]
yes, exactly. Can you please provide the list of your installed extensions?  run `code --list-extensions` from your terminal as described [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management)

**Comment by ShaquibKhanhub** [comment]
![image](https://user-images.githubusercontent.com/111151404/234806893-ddf89d27-98cd-455c-a2b1-cfc8a5f9f6c3.png)

**Comment by dimacodota** [comment]
is it possible that you have the [Code Autocomplete](https://marketplace.visualstudio.com/items?itemName=svipas.code-autocomplete)  installed?

**Comment by ShaquibKhanhub** [comment]
Yup today only i install that extension but before days I'm facing this problem so o don't think so because of it happening?

**Comment by dimacodota** [comment]
It is a fork of tabnine. tabnine-vscode extension, so they both use the same `Tabnine::config` command id which we failed to override.  con you please uninstall it (you need to reload the IDE to complete the uninstall process) and send us the vscode logs after rerunning the IDE?

**Comment by ShaquibKhanhub** [comment]
Yeah sure let me do this first but can you please tell me again what i have to do like i have to uninstall rhe tabnine extension and install it again like what you are saying?

**Comment by ShaquibKhanhub** [comment]
yeah now its not showing that status.bar error but still it's not giving me suggestions 
And here's the vs code log
![image](https://user-images.githubusercontent.com/111151404/234891312-60b0c211-b73e-4370-ba9a-1112926db625.png)

**Comment by dimacodota** [comment]
Could you please disable the [Blackbox](https://marketplace.visualstudio.com/items?itemName=Blackboxapp.blackbox) extension? It seems like it might be disabling the inline completion providers while it's installed.

**Comment by TzufTabnine** [comment]
@ShaquibKhanhub 

During the trial period (the first 14 days since installation), you get the Pro subscription "i just write any function name like something it's write the whole code for me...", now you are in the Starter subscription, meaning you can only get one word of suggestion, are you getting it?

**Comment by ShaquibKhanhub** [comment]
Yes sometimes only

**Comment by TzufTabnine** [comment]
Glad to hear that @ShaquibKhanhub. The issue is resolved then. You can always subscribe for the Pro subscription.

**Comment by ShaquibKhanhub** [comment]
Yup sure 🤞🏻🤞🏻
