### ISSUE TITLE
How to use tabnine to batch process files (generate code for a thousand files)

### ISSUE THREAD

**Issue by ljr19231244** [codota/tabnine-vscode#1090]
**please complete the following information:**

- OS version: Win 10
- Programming language: python
- TabNine extension version:latest

**Issue Details:**
I am conducting comparative analysis and research on code generation tools, and I want to call tabnine through scripts to generate code in batches for a thousand files. What should I do?

**Comment by TzufTabnine** [comment]
@ljr19231244 
We do not support such a use case. Tabnine is intended to be used within an IDE on a specific file, just as a regular user would work.
