### ISSUE TITLE
Word by word completion.

### ISSUE THREAD

**Issue by geovex** [codota/tabnine-vscode#1097]
**please complete the following information:**

- OS version: arch linux
- Editor version: 1.77.3
- Programming language: any
- TabNine extension version: 3.6.46

Since recently, vscode supports `editor.action.inlineSuggest.acceptNextWord` shortcut. However, if used, it inserts one word and most of the time discards the other part of the completion. This prevents continuously completing word-by-word. Is it expected behavior?

gz#23311<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23311'>Zendesk ticket #23311</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @geovex 
Can you please send us a video of the issue?

**Comment by geovex** [comment]
Looks like it was fixed the day it was posted. I can't reproduce it since.

**Comment by geovex** [comment]
OK it happened again

Sometimes it works but in most cases it completes one word.

https://github.com/codota/tabnine-vscode/assets/6135355/89a76286-71d3-470c-b6b3-b19ad2699f71
