### ISSUE TITLE
Tabnine login issue

### ISSUE THREAD

**Issue by puranjayjain** [codota/tabnine-vscode#1103]
**please complete the following information:**

- OS version: Mac 13.3.1 (a) (22E772610a)
- Editor version [e.g. 1.45.0-insider]:
- Programming language: All
- TabNine extension version: 3.6.0

**Issue Details:**
I have to login to tabnine each time I open vscode.

gz#23433<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23433'>Zendesk ticket #23433</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @puranjayjain

Please send us a video of the issue.
In addition, please send us the [log files](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode)

**Comment by puranjayjain** [comment]
It now logs in after a couple of minutes. Closing this issue it's not happening in the new version of vscode
