### ISSUE TITLE
discord Invalid link

### ISSUE THREAD

**Issue by auroramy** [codota/tabnine-vscode#1104]
![image](https://user-images.githubusercontent.com/118866797/237024776-895b91ce-dfa5-4195-b47a-870f0c21c084.png)

**Comment by TzufTabnine** [comment]
Hi @auroramy 
We closed our Discord chanel. If you want to be part of the Tabnine community, you can follow us here (GitHub), [on Facebook](https://www.facebook.com/TabnineInc/), [Linkedin](https://il.linkedin.com/company/tabnine), and [Twitter](https://twitter.com/tabnine)
