### ISSUE TITLE
卸载不完全

### ISSUE THREAD

**Issue by changbiao** [codota/tabnine-vscode#114]
Issue Type: <b>Bug</b>

插件 tabnine mac版，卸载完重启之后，还会有连接tabnine的服务器，卸载不完全

Extension version: 2.8.6
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 18.7.0

**Comment by changbiao** [comment]
/Users/USER/.vscode/extensions/tabnine.tabnine-vscode-2.8.6

**Comment by shaiahr** [comment]
Hi @changbiao 
If I understand your issue correctly,  you are saying there is still a TabNine process after uninstalling it? If so, please make sure you close all vscode instances and check again.

Thanks
Shai
