### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JEPEREZR** [codota/tabnine-vscode#1159]
- Issue Type: `Performance`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.6.60`
- OS Version: `Darwin arm64 23.0.0`
- VS Code version: `1.80.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/6b/q94ctx6s4y7431fpbyzxjbbm0000gn/T/TabNine.tabnine-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

gz#24432<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24432'>Zendesk ticket #24432</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @JEPEREZR
Read [here](https://support.tabnine.com/hc/en-us/articles/5529656478225-Settings) for more information about the different settings and modes. It is recommended to run on Cloud mode.
