### ISSUE TITLE
Wrong auto imports

### ISSUE THREAD

**Issue by ishan123456789** [codota/tabnine-vscode#116]
When auto importing the plugin imports same plugin twice sometimes and wrong imports rated higher. Like when in Angular project the and trying to import router the router from express is loaded where as I'm currently in the angular project.

	
 - OS version: MACOS Mojave 10.14.6 (18G103)
 - Editor: vscode
 - Editor version:	Version: 1.46.1
 - Programming language: TS
 - TabNine extension version: 2.8.6
 

**Issue Details:**
I typed 
Router and when I clicked on the options available for auto import the Router was imported from express while I was working in Angular project. So wrong import's the first issue. And when I type Router again it imports the Router twice ie. 
`import {Router, Router} from 'express';` So only one should be there.

**Comment by ishan123456789** [comment]
Sorry for the late reply here's my list of extensions:
```
❯ code --list-extensions
Angular.ng-template
apollographql.vscode-apollo
atlassian.atlascode
ChakrounAnas.turbo-console-log
dbaeumer.vscode-eslint
eamodio.gitlens
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
felixfbecker.php-intellisense
johnpapa.angular-essentials
johnpapa.Angular2
johnpapa.vscode-peacock
johnpapa.winteriscoming
karigari.chat
ms-azuretools.vscode-cosmosdb
ms-azuretools.vscode-docker
ms-python.python
ms-vscode-remote.remote-containers
ms-vscode.azure-account
ms-vscode.vscode-typescript-tslint-plugin
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
msjsdiag.debugger-for-chrome
msjsdiag.debugger-for-edge
nrwl.angular-console
PKief.material-icon-theme
redhat.vscode-yaml
remimarsal.prettier-now
sburg.vscode-javascript-booster
streetsidesoftware.code-spell-checker
TabNine.tabnine-vscode
tht13.python
```
I've been working on different projects so need a couple of plugins that might be causing the conflict

**Comment by boaz-codota** [comment]
Relates to #113 , please refer to my comment there.
Could you report on the TypeScript version you're running?
