### ISSUE TITLE
TabNine stopped showing suggestions, TabNine::Config does not work

### ISSUE THREAD

**Issue by thakkarparth007** [codota/tabnine-vscode#118]
- OS version: Win 10	
 - Editor version: 1.46.1
 - Programming language: <any language, doesn't matter>
 - TabNine extension version: 2.8.7
 
[//]: <> ( **If the issue is related to TabNine failure, please provide log files:**	)
[//]: <> ( Type `TabNine::config` in your editor, the logs are located at the bottom of the page)
 
**Editor console logs:**

```Activating extension 'TabNine.tabnine-vscode' failed: undefined.```

**Issue Details:**
Unable to use any TabNine functionality because the extension itself does not load. Not sure where to look for more information regarding the failure. I tried reinstalling the extension and also restarting VS Code, but neither helped.

**Comment by matheuslimacs** [comment]
Same here, just happened this morning (using the free version in small projects since I'm a student).

**Comment by TheOguzhan** [comment]
Hello. I had same problems, too. My Tab9 didn't work. I thought that could be about Win10 Update. I downloaded old versions of Tab9 before, but it didn't work, too. I updated VSCode to 2020 May, then I downloaded Tab9 2.8.5. Now it works really well. 
Suggestions: Download old version of Tab9 or new version of  VSCode or both of them.
P.S. I hope that would help you.
Happy Coding

**Comment by dimacodota** [comment]
can you please provide an 'extension host` log?
open the command palette (cmd +shift + p) then type "Open Log Output File"
alternative  view -> Output then select Log (Extension Host) in the dropdown 

Thanks

**Comment by matheuslimacs** [comment]
Sure, this is mine, hope it helps.

[exthost.log](https://github.com/codota/tabnine-vscode/files/4880927/exthost.log)

**Comment by dimacodota** [comment]
Great! thanks @matheuslimacs, could you please provide the TabNine configuration file? 
the file should be located at %APPDATA%/TabNine/tabnine_config.json

**Comment by matheuslimacs** [comment]
(just zipped the .json since it's unsupported by this comment section)

[tabnine_config.zip](https://github.com/codota/tabnine-vscode/files/4881055/tabnine_config.zip)

**Comment by gentle-shao** [comment]
Same here. Any suggestion?

**Comment by dimacodota** [comment]
Thank you all for your cooperation, we are working on a fix, in the meantime can any of you try the attached vsix and reply here if it fixed the issue?

https://github.com/codota/tabnine-vscode/releases/tag/untagged-04feab6f33e04c669d37

Thanks

**Comment by dimacodota** [comment]
the vsix https://github.com/codota/tabnine-vscode/releases/tag/untagged-17d2b2529a29e9b4f41d

**Comment by yingming25** [comment]
@dimacodota Excuse me, can't download vsix.
I get 404 error page.

**Comment by dimacodota** [comment]
@yingming25  please try again

**Comment by yingming25** [comment]
@dimacodota look like a little diffrent(have {} before text), But Work again.
![tabnine](https://user-images.githubusercontent.com/26245479/86739132-3bc32d00-c068-11ea-88af-e6e60218c3d7.png)
Thank a lot.

**Comment by dimacodota** [comment]
the fix was released as part of 2.8.8 version
