### ISSUE TITLE
crazily usage of RAM

### ISSUE THREAD

**Issue by Bader-Idris** [codota/tabnine-vscode#1180]
- OS version: Win 11
- Editor version: 1.79.2
- Programming language:  js, ts
- TabNine extension version: v3.6.63
I have installed 98 extensions in my VS code, and none of them used this extension's usage of RAM, it uses more than 1 GB, while other extensions don't go above 300 at maximum.

gz#24652<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24652'>Zendesk ticket #24652</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Bader-Idris 
Are you running on Cloud mode? If not, please do.
See [here ](https://support.tabnine.com/hc/en-us/articles/5529656478225-Tabnine-Settings)about the difference between the modes.
