### ISSUE TITLE
win11 got bluescreen by tabnine-vscode

### ISSUE THREAD

**Issue by charryong** [codota/tabnine-vscode#1200]
**please complete the following information:**

- OS version: [e.g. Win 11]
- Editor version [1.80.0]:
- Programming language: [python]
- TabNine extension version:
- 
![image](https://github.com/codota/tabnine-vscode/assets/955812/ac49eddf-5fdd-490d-8692-0920aaf01158)

gz#24957<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24957'>Zendesk ticket #24957</a>)</i>

**Comment by TzufTabnine** [comment]
@charryong 
Please send us the log files (devtools +engine). 
See here:
https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode 
how to do that.

Tabnine Support.

**Comment by TzufTabnine** [comment]
Also, please try [this](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues)

**Comment by charryong** [comment]
[tabnine_rCURRENT.zip](https://github.com/codota/tabnine-vscode/files/12026732/tabnine_rCURRENT.zip)

**Comment by yonip23** [comment]
@charryong hi,
Please share the following:
1. How did you discover that Tabnine caused the bluescreen - please share your evidence.
2. Your VSCode logs: use the `Developer: Open Logs Folder` command.
3. Your VSCode console output: use the `Developer: Toggle Developer Tools` command, and share the console output from there. 

Kind regards,
Yoni

**Comment by charryong** [comment]
[070523-11109-01.zip](https://github.com/codota/tabnine-vscode/files/12034394/070523-11109-01.zip)
The file is sent to microsoft,their answer the bluescreen is caused by the tabnine.

**Comment by charryong** [comment]
> [tabnine_rCURRENT.zip](https://github.com/codota/tabnine-vscode/files/12026732/tabnine_rCURRENT.zip)

This file is I try it again following your answer in a python file,the bluescreen got again.They suggested me to unistall the tabnine.

**Comment by charryong** [comment]
![image](https://github.com/codota/tabnine-vscode/assets/955812/0b502db3-63da-4a10-b793-814efbfd2f4e)
This was ok.

**Comment by yonip23** [comment]
Did Microsoft mention which process caused the blue screen specifically?
Let's check if it caused by the deep local process:
Please open your config file (Hub -> Settings -> Config file path) and set:
`"deep_completions_work_mode": "CloudOnly"`,
`"local_enabled": "No"`
Then kill all Tabnine processes - `TabNine`, `TabNine-deep-local` `TabNine-deep-cloud` `WD-TabNine`, and restart your IDE.
Lmk if that helped

**Comment by charryong** [comment]
no, not said more details. where is the config file?

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location

**Comment by charryong** [comment]
now is the Hybrid,turn it to the Cloud?
![image](https://github.com/codota/tabnine-vscode/assets/955812/fc1b3706-bed0-43fc-82a2-b86786e937d6)

**Comment by yonip23** [comment]
yes 👍🏻

**Comment by charryong** [comment]
no bulescreen,but didt not worked.
![image](https://github.com/codota/tabnine-vscode/assets/955812/c9fc0e74-69db-4353-b32a-f18a4d17cb51)

**Comment by yonip23** [comment]
Can you send the binary logs from this session?

Also, please close the IDE, kill all Tabnine processes, delete `c:\Users\cylot\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries` and restart - looks like you experienced a corrupted state.

**Comment by charryong** [comment]
[tabnine_rCURRENT.zip](https://github.com/codota/tabnine-vscode/files/12045988/tabnine_rCURRENT.zip)

**Comment by yonip23** [comment]
I see that you're using an unofficial Tabnine plugin: https://marketplace.visualstudio.com/items?itemName=svipas.code-autocomplete
Please uninstall it and install the official plugin: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
