### ISSUE TITLE
tab nine css class names autocomplete is not working in html files

### ISSUE THREAD

**Issue by hassanbinsafdar** [codota/tabnine-vscode#124]
tab nine does not show any css from my files . no suggestions of css class names in html

**Comment by yingming25** [comment]
My OS is Win10.
I use TabNine V2.8.9 everything work.

**Comment by hassanbinsafdar** [comment]
@yingming25 my os is mac os catalina 10.5.5 so its not working

**Comment by dimacodota** [comment]
hey @hassanbinsafdar, can you please provide a screen recording(gif) of the issue?

**Comment by rustyxlol** [comment]
Late to this but seems like it is a conflict with [TabOut extension](https://marketplace.visualstudio.com/items?itemName=albert.TabOut). Had the same issue and getting rid of TabOut fixed it.
