### ISSUE TITLE
Can I custom the code color?

### ISSUE THREAD

**Issue by FindingArrow** [codota/tabnine-vscode#1241]
Hello, I love this plugin. It is great.
I found that I can custom the color of the suggestion code in JetBrains IDEs, Will you update this for vscode?

gz#25651<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25651'>Zendesk ticket #25651</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @FindingArrow,
Unfortunately, it is only available in JetBrains IDEs (part of the IDE settings).
