### ISSUE TITLE
 [ERROR] autocomplete timed out/[ERROR]: Error: Binary request timed out.

### ISSUE THREAD

**Issue by sirius16** [codota/tabnine-vscode#1284]
**please complete the following information:**

- OS version: MacOS Ventura 13.4.1
- Editor version: VSCode 1.81.1 -> 1.82.0 (updated while I was experiencing the problem, experienced in both versions)
- Programming language: Python, Javascript, TypeScript (not Plain Text though)
- TabNine extension version: 3.8.14

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

[tabnine_rCURRENT.log-3007.log](https://github.com/codota/tabnine-vscode/files/12555792/tabnine_rCURRENT.log-3007.log)
[tabnine_rCURRENT.log-3683.log](https://github.com/codota/tabnine-vscode/files/12555793/tabnine_rCURRENT.log-3683.log)
[tabnine_rCURRENT.log-4652.log](https://github.com/codota/tabnine-vscode/files/12555794/tabnine_rCURRENT.log-4652.log)
[tabnine_rCURRENT.log-5077.log](https://github.com/codota/tabnine-vscode/files/12555795/tabnine_rCURRENT.log-5077.log)
[tabnine_rCURRENT.log-5671.log](https://github.com/codota/tabnine-vscode/files/12555796/tabnine_rCURRENT.log-5671.log)
[tabnine_rCURRENT.log-8233.log](https://github.com/codota/tabnine-vscode/files/12555797/tabnine_rCURRENT.log-8233.log)
[tabnine_rCURRENT.log-9713.log](https://github.com/codota/tabnine-vscode/files/12555798/tabnine_rCURRENT.log-9713.log)
[tabnine_rCURRENT.log-9801.log](https://github.com/codota/tabnine-vscode/files/12555799/tabnine_rCURRENT.log-9801.log)
[tabnine_rCURRENT.log-10017.log](https://github.com/codota/tabnine-vscode/files/12555800/tabnine_rCURRENT.log-10017.log)
[tabnine_rCURRENT.log-10363.log](https://github.com/codota/tabnine-vscode/files/12555801/tabnine_rCURRENT.log-10363.log)
[tabnine_rCURRENT.log-10753.log](https://github.com/codota/tabnine-vscode/files/12555802/tabnine_rCURRENT.log-10753.log)
[tabnine_rCURRENT.log-14509.log](https://github.com/codota/tabnine-vscode/files/12555803/tabnine_rCURRENT.log-14509.log)
[tabnine_rCURRENT.log-14987.log](https://github.com/codota/tabnine-vscode/files/12555804/tabnine_rCURRENT.log-14987.log)
[tabnine_rCURRENT.log-15682.log](https://github.com/codota/tabnine-vscode/files/12555805/tabnine_rCURRENT.log-15682.log)
[tabnine_rCURRENT.log-17863.log](https://github.com/codota/tabnine-vscode/files/12555807/tabnine_rCURRENT.log-17863.log)
[tabnine_rCURRENT.log-19491.log](https://github.com/codota/tabnine-vscode/files/12555808/tabnine_rCURRENT.log-19491.log)

**Issue Details:**

The autocomplete would not work at all except for maybe once every so often after like 5 minutes. After several hours of struggling I finally happened on the `gitlab.aiAssistedCodeSuggestions.enabled` setting and set it to false, after that it worked. But I'm sure that I've been using that feature without trouble before today/yesterday so the problem is still on TabNine's end. I like having both so I'd prefer if we could solve this problem. But for now I've turned off `gitlab.aiAssistedCodeSuggestions.enabled` and am using the autocomplete

gz#26353<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26353'>Zendesk ticket #26353</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, can you try running Tabnine without GitLab AI?
