### ISSUE TITLE
[Type: enhancement] Force trigger inline suggestion

### ISSUE THREAD

**Issue by sirius16** [codota/tabnine-vscode#1292]
Sometimes there will be no inline suggestion and I'd like to be able to force trigger one. Also sometimes I'd like to get a suggestion in the middle of a line instead of having to break the line in two or having to delete the rest of the line at at the point I'm trying to get a suggestion from, just to trigger an inline suggestion. It would be helpful to be able to have a keyboard shortcut that triggers an inline suggestion, even in the middle of a line

gz#26487<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26487'>Zendesk ticket #26487</a>)</i>

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/13965663739921-How-to-control-Trigger-Inline-Suggestions-in-VSCode-

**Comment by sirius16** [comment]
there is no `trigger.inline.suggestion` as part of tabnine though. Do I have to add it manually? Even opened up the extension folder in ~/.vscode/extensions and searched the entire folder and there was not a single mention of `trigger.inline.suggestion`. So does that really work?
