### ISSUE TITLE
FastAPI Strange suggestion 

### ISSUE THREAD

**Issue by kolaxy** [codota/tabnine-vscode#1298]
**please complete the following information:**

- OS version: Fedora Linux 38 (Workstation Edition) x86_64
- Editor version [e.g. 1.45.0-insider]:
- Programming language: Python 3.11.5 (venv)
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**
FastAPI strange suggestion

![image](https://github.com/codota/tabnine-vscode/assets/115103276/61692db4-2ae8-4d12-b064-e76ff9f75299)

gz#26725<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26725'>Zendesk ticket #26725</a>)</i>

**Comment by TzufTabnine** [comment]
@kolaxy Please send us the log files. See here how to do that-
https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode
