### ISSUE TITLE
Try using vscode-python language server instead of installing pyls?

### ISSUE THREAD

**Issue by yozlet** [codota/tabnine-vscode#13]
TabNine is utterly fantastic, and it's great to see it using LSP for semantic completion. However, installing pyls is an odd choice _when inside VSCode_: most Python users will already have [`vscode-python`](https://github.com/Microsoft/vscode-python) installed (it's the single most popular VSCode extension) and [it comes with its own language server](https://blogs.msdn.microsoft.com/pythonengineering/2018/07/18/python-in-visual-studio-code-june-july-2018-release/), one that has considerably more work going into it than Palantir's.

Is it possible to default to using `vscode-python`'s language server?

**Comment by yozlet** [comment]
Extra reason for wanting this: python users like myself often have multiple virtualenvs on their machine, each with one or more projects in it, and the language server _probably_ needs to run inside the venv for the current project to ensure it can see that venv's modules, etc. `vscode-python` has lots of settings and cleverness for running inside the right venv, and even then it sometimes gets it wrong. I suspect it'll be much easier to piggyback on whatever services `vscode-python` provides than to try and replicate them.

**Comment by zxqfl** [comment]
Thanks for the suggestion. This is a good idea and I will implement it sometime in the future.

**Comment by yozlet** [comment]
Thank you! It may also be increasingly helpful for other languages which are already starting/using a language server, since that's VSCode's preferred model for language extensions. I believe VSCode also runs its own language servers for JS & TS.
