### ISSUE TITLE
How to disable notification about enabling Deep Cloud?

### ISSUE THREAD

**Issue by weiby3** [codota/tabnine-vscode#130]
I have searched the settings and didn't find any config to use.

**Comment by JustFly1984** [comment]
Yes, constant notifications in bottom right corner is very annoying and covers bottom line of my terminal, and sometimes there is 3  or more notifications  at the same time. Would love to see the status in status bar instead of notifications spam on every file save action.

**Comment by JustFly1984** [comment]
@dimacodota  It is pretty confusing to type something in editor. Can you please implement vscode plugin settings as it is implemented for vscode-eslint-plugin?

**Comment by weiby3** [comment]
@dimacodota Not that message. It's this: 
![image](https://user-images.githubusercontent.com/30197106/89509968-8ddfa580-d802-11ea-9b26-ba5b742a7e66.png)

**Comment by dimacodota** [comment]
@weiby3 - may i ask why you signed up for TabNine Professional but didn't enable the Deep Cloud?

**Comment by weiby3** [comment]
@dimacodota 
I don't want to upload some code to Internet.

**Comment by avichay77** [comment]
These notifications were part of an attempt to improve user experience and clarity. 
Based on your feedback we've reviewed this behavior and have decided to reduce the number and types of notifications.
The change will be part of an update that we plan to release next week. 
Thanks for bringing this issue up.

**Comment by JustFly1984** [comment]
Is it possible to enable cloud functionality per project in vscode settings, instead of having it enabled globally?

**Comment by avichay77** [comment]
@weiby3  @JustFly1984 Following your feedback, the number of notifications was reduced dramatically in version 2.9.2.

@JustFly1984 are you using the cloud today? if not - would you use it if you were able to enable the cloud per project? can you explain why?

**Comment by dimacodota** [comment]
@JustFly1984 - you can enable cloud only for whitelisted directories
<img width="788" alt="Screen Shot 2020-08-16 at 11 45 31" src="https://user-images.githubusercontent.com/60742964/90330541-2372f600-dfb6-11ea-975a-27289b5ae36e.png">
