### ISSUE TITLE
Sign in prompt doesn't go away

### ISSUE THREAD

**Issue by Abhinickz** [codota/tabnine-vscode#1306]
**please complete the following information:**

- OS version: Manjaro Linux (Issue Present in Windows, macOS also)
- Editor version [e.g. 1.45.0-insider]: 1.82.2
- Programming language: All
- TabNine extension version: 3.17.0

**Issue Details:**

Every time I open VScode regardless of OS, or VSCode version, TabNine prompts me to Sign in.

and this notification does not go away on its own most of the time.

![image](https://github.com/codota/tabnine-vscode/assets/10339494/d8e2e2c2-28bd-442d-804b-6a77c3d8ca87)

gz#26819<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26819'>Zendesk ticket #26819</a>)</i>

**Comment by TzufTabnine** [comment]
Please send us the engine log files. See [here ](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode)how to do that.
