### ISSUE TITLE
bluescreenshots!

### ISSUE THREAD

**Issue by MateuszS-Qlos** [codota/tabnine-vscode#1328]
**please complete the following information:**

- OS version: Win 11
- Editor version [e.g. 1.45.0-insider]:
- Programming language:  yaml
- TabNine extension version: idk latest?

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#27158<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27158'>Zendesk ticket #27158</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @MateuszS-Qlos 

Please send us the VSCode log files (devtools +engine). See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

Please send us a screenshot/video of the issue
