### ISSUE TITLE
It takes up too much memory

### ISSUE THREAD

**Issue by tomoat** [codota/tabnine-vscode#137]
**please complete the following information:**	
 - OS version:  Mac Catalina
 - Editor version :	1.48.2
 - Programming language:  js, ts
 - TabNine extension version: 3.0.0

版本: 1.48.2
提交: a0479759d6e9ea56afa657e454193f72aef85bd0
日期: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

![image](https://user-images.githubusercontent.com/7428698/91927435-17a06700-ed0c-11ea-8fab-975063635e2e.png)
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page
 
**Editor console logs:**

 Help -> Toggle Developer Tools

**Issue Details:**

It takes up too much memory，Every time you open a VsCode window, TabNine creates a process and takes up an equally large amount of memory？

**Comment by yanir-codota** [comment]
Hi @tomoat 

Thanks for the feedback! 
We are aware of this issue, and already working on a solution! 
We believe a new version solving this issue will be released very soon (about 2 weeks time).

On this note, if you wish to be among the users who'll get an early version, we would love to see you among our Beta users community, and welcome you to join.

**Comment by ultronnet** [comment]
It's still take up too much memory
<img width="746" alt="image" src="https://user-images.githubusercontent.com/72001621/152087519-397e440a-ff30-48cf-9dc9-f21ea2924b7f.png">
