### ISSUE TITLE
"Reload the window" popup shown after each update.

### ISSUE THREAD

**Issue by vanowm** [codota/tabnine-vscode#1375]
When there is an update available, in the extensions list it shows "reload" button. Pressing it reloads the window to update the extension. After the reload TabNine shows this popup:
![image](https://github.com/codota/tabnine-vscode/assets/511517/9de3b2ac-ef42-4e2d-b556-2463a04f050c)

```
TabNine has been updated to v3.36.0-alpha.20231123093532 version. Please reload the window for the changes to take effect.
```
Do we have to reload the window twice to update TabNine?

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
TabNine: v3.29.1-alpha.20231109152959
```

gz#27965<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27965'>Zendesk ticket #27965</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @vanowm You are receiving the beta version, thus there are a lot of updates. You can set it off, see [here](https://support.tabnine.com/hc/en-us/articles/5529656478225-Tabnine-Settings) how to do that.

**Comment by vanowm** [comment]
Sorry, what?

**Comment by TzufTabnine** [comment]
Hi @vanowm ,
Could you please specify what wasn't clear?

**Comment by TzufTabnine** [comment]
It is required every time there is an update. When you are receiving beta, there are a lot of updates. Set the beta off -

**Comment by vanowm** [comment]
Why does it require manual clicking `update` button?
![image](https://github.com/codota/tabnine-vscode/assets/511517/8f8b27f3-8df5-4b0e-b827-00da39546c64)

No other extensions require that.

**Comment by vanowm** [comment]
NVM, somehow auto update was turned off for this specific extension.
