### ISSUE TITLE
Windows 10 64bit flow integration and config loading

### ISSUE THREAD

**Issue by zurp** [codota/tabnine-vscode#14]
Just wanted to leave this here, `which flow` will not point to the right path on Windows 10 64bit.
I managed to get flow lsp working by using this configuration:

```
[language.javascript]
command = "C:\\Users\\dev\\AppData\\Roaming\\npm\\flow.cmd"
args = ["lsp"]
install = [["npm", "install", "-g", "flow-bin"]]
```

On config loading, it seems that TabNine treats files as folders when trying to look for a root / config file, and it's trying to open all the **/*.*/.tabnineroot paths.

Thank you for your work, this is awesome!

**Comment by zxqfl** [comment]
Thanks for posting your config! Where was TabNine looking before you updated the config?

Yes, TabNine simply tries adding `.tabnine_root` after each entry in the file path.

**Comment by neculaesei** [comment]
On my system `which flow` returns `/c/Users/dev/AppData/Roaming/npm/flow`. I just had to add `.cmd` to it.
