### ISSUE TITLE
cannot show codelens

### ISSUE THREAD

**Issue by qz1543706741** [codota/tabnine-vscode#1432]
**please complete the following information:**

- OS version: Mac Sonoma
- Editor version：vscode  1.86
- Programming language: ts，js
- TabNine extension version:

no codelens

**Comment by qz1543706741** [comment]
> Reference in new issue
I have confirmed that I have turn on the switch.But there is no codelens.
![image](https://github.com/codota/tabnine-vscode/assets/49976933/1c00e252-683a-4d67-a038-31dff5cf1314)
![image](https://github.com/codota/tabnine-vscode/assets/49976933/b9201d68-64f0-4cee-a630-6fb094112755)

**Comment by qz1543706741** [comment]
> Hi @qz1543706741 . What is your plugin version?
`v3.71.0`
![image](https://github.com/codota/tabnine-vscode/assets/49976933/8670dff8-9ae0-4254-a396-c59e0f7a8160)

**Comment by qz1543706741** [comment]
@TzufTabnine 
my plugin version is `v3.71.0`
![image](https://github.com/codota/tabnine-vscode/assets/49976933/8670dff8-9ae0-4254-a396-c59e0f7a8160)

**Comment by TzufTabnine** [comment]
Try this function:
function map(f, a) {
  const result = new Array(a.length);
  for (let i = 0; i < a.length; i++) {
    result[i] = f(a[i]);
  }
  return result;
}
Let us know if it works there
