### ISSUE TITLE
Tabnine plugin automatically switches focus to Chat window

### ISSUE THREAD

**Issue by chdorian-logitech** [codota/tabnine-vscode#1433]
- OS version: Win11
- Editor version 1.86.2
- Programming language: c++
- TabNine extension version: 3.72.0

**If the issue is related to TabNine failure, please provide log files:**

Not a failure, but very annoying issue.

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

Tabnine occasionally changes focus from the current focus to the chat entry window. WHatever I was typing, ends up in the chat window (even if it was not opened on the left panel at the time!). Happens with both 'Workspace; toggle enabled and disabled.

gz#29880<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/29880'>Zendesk ticket #29880</a>)</i>

**Comment by t4skmanag3r** [comment]
I'm facing the same issue.

- OS version: Win10
- Editor version 1.86.2
Issue seems to originate from 3.70.0

Tested with all user preferences and other extensions disabled so I'm sure it's specific to tabnine.

**Comment by hoshython** [comment]
The same issue and makes me angry

**Comment by hoshython** [comment]
disabled tabnine after this issue gets solved. It just stops my work

**Comment by direc85** [comment]
Same here with `tabnine.tabnine-vscode 2024-02-21, 16:56:03`:

> Version: 1.86.2
> Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
> Date: 2024-02-13T19:41:37.860Z
> Electron: 27.2.3
> ElectronBuildId: 26908389
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 6.7.6-1-MANJARO

**Comment by TzufTabnine** [comment]
Hi, we are investigating the issue.

**Comment by TzufTabnine** [comment]
Hi,
Please update your plugin and inform us if it resolves the issue.
