### ISSUE TITLE
Tabnine stuck at 'Workspace indexing'

### ISSUE THREAD

**Issue by JohannesKaminski** [codota/tabnine-vscode#1439]
- OS version: Rocky Linux 9.3
- Editor version: 1.87.2
- Programming language: Python3.11
- TabNine extension version: 3.76.0

Tabine Log:
[tabnine_rCURRENT.log](https://github.com/codota/tabnine-vscode/files/14590898/tabnine_rCURRENT.log)

Editor Log:
[vscode-app-1710347279623.log](https://github.com/codota/tabnine-vscode/files/14590910/vscode-app-1710347279623.log)

**Issue Details:**
I recently installed Tabnine, but inside the Tabnine Chat it keeps saying 'Workspace indexing: Not yet started'. I have been running Tabnine for a couple of hours already, without any changes to the prompt. Seeing the auto-complete recommendations also makes this obvious, as the proposals, e.g. for imports, do not reflect my workspace structure.

Reading the logs I can see that some vdb-server seems to fail starting up, which looks directly related to indexing. However I have no idea how to fix this.

gz#30290<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/30290'>Zendesk ticket #30290</a>)</i>

**Comment by JohannesKaminski** [comment]
Sorry for creating duplicate support tickets. Ticket 30289 via support@tabnine.com is also by me.

**Comment by Jas-n** [comment]
I'd like to just reference that this fixed it for me, and hopefully helps anyone else: https://github.com/codota/TabNine/issues/659#issuecomment-2444516686
