### ISSUE TITLE
Workspace context needs to be enabled in order to use the onboarding agent.

### ISSUE THREAD

**Issue by hcapp01** [codota/tabnine-vscode#1447]
**please complete the following information:**

- OS version: Mac Catalina
- Editor version 
- Programming language: n/a
- TabNine extension version: n/a

**Issue Details:**
in chat window
/onboarding
It returns "Workspace context needs to be enabled in order to use the onboarding agent."
However this is nowhere to enable workspace context

gz#30712<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/30712'>Zendesk ticket #30712</a>)</i>

**Comment by amirbilu** [comment]
Hi @hcapp01 what's your Tabnine Pro email?

**Comment by akaasula21** [comment]
Hello team, 

I facing the same issue. How can I get it resolved ?

**Comment by TzufTabnine** [comment]
Hi @hcapp01 what's your Tabnine Pro email?

**Comment by akaasula21** [comment]
Its adarshkaasula68@gmail.com

**Comment by TzufTabnine** [comment]
Do you have a Pro subscription? @akaasula21

**Comment by akaasula21** [comment]
> Do you have a Pro subscription? @akaasula21

No, I have opted for basic plan, but tabnine provided me with 14 day trail for Pro Subscription.

**Comment by Th3R3al0** [comment]
I have this problem to

**Comment by vinmutua** [comment]
i had this problem too
