### ISSUE TITLE
tabnine config not found

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [codota/tabnine-vscode#145]
Issue Type: <b>Bug</b>

I just installed tabnine.after (>tabnine:open settings) Command 'TabNine: Open Settings' resulted in an error (command 'TabNine::config' not found)

Extension version: 3.0.3
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.54GB free)|
|Process Argv|--crash-reporter-id e154b062-c64b-4aa8-8867-3638ddc17c20|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by boaz-codota** [comment]
Hey Irfan, sorry for your bad experience with TabNine.

Are you seeing a TabNine process in the Task Manager?

**Comment by Vivek205** [comment]
Hi @boaz-codota . I'm facing the same issue
