### ISSUE TITLE
An error occurred: Error: Server failed to generate a response

### ISSUE THREAD

**Issue by scallop123** [codota/tabnine-vscode#1452]
I've been persistently shown this error starting an hour ago, it's still there after restarting VSCode.

- OS version: Win 10
- Editor version [latest VSCODE]:
- Programming language: [php]
- TabNine extension version: [3.93.0]

**If the issue is related to TabNine failure, please provide log files:**
I can't locate any log files for this Tabnine error within VSCode

Type `TabNine::config` in your editor, the logs are located at the bottom of the page
I cat see anything after typing the above prompt, show some tutorials where to key in what to retrieve the error log

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#31102<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31102'>Zendesk ticket #31102</a>)</i>

**Comment by TzufTabnine** [comment]
Please provide more details (video)
