### ISSUE TITLE
I need to install the extension offline, but notice me dependencies install failed

### ISSUE THREAD

**Issue by lcwxz1989** [codota/tabnine-vscode#1453]
**please complete the following information:**

- OS version: ubuntu 22.04
- Editor version 1.77.3:
- Programming language: python, rust
- TabNine extension version: 3.92.0

My target mechine is offline, so I just download the extension from market, but the dependencies I did not get the list and download

gz#31198<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31198'>Zendesk ticket #31198</a>)</i>

**Comment by TzufTabnine** [comment]
Can you elaborate?

**Comment by ghill7777** [comment]
> Can you elaborate?

@TzufTabnine I have the same issue.  After installing the extension in VS Code, I get an error pop-up complaining that it's unable to download dependencies.  It may be related to a firewall on my work computer as it installs on my home computer fine.  However, I need to give my IT guys the dependency locations so they can fix it, but I don't know them.
![image](https://github.com/codota/tabnine-vscode/assets/22450264/3f553e54-e122-4856-aa19-86f15bcb6afd)

**Comment by TzufTabnine** [comment]
Hi @ghill777,
It can happen when there are some connectivity issue (slow internet connection/proxy/VPN etc).
See here - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
