### ISSUE TITLE
Tabnine keeps Crashing

### ISSUE THREAD

**Issue by scallop123** [codota/tabnine-vscode#1456]
**please complete the following information:**

- OS version: [e.g. Win 10]
- Editor version [LATEST vscode]:
- Programming language: [PHP]
- TabNine extension version: [3.97.0]

**TABNINE CRASHED 10X THIS MORNING. Workspace indexing showing the circle icon is running but with the message 'Not yet started**

What to do while waiting for your feedback?

gz#31445<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31445'>Zendesk ticket #31445</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, is it still happening? If so, can you tell us more about your workspace (how big is it?)? Can you try to delete Tabnine completely - https://support.tabnine.com/hc/en-us/articles/17823949049745-How-to-delete-Tabnine-completely-from-your-machine and then reinstall Tabnine?
