### ISSUE TITLE
TabNine extension crashing frequently during normal use

### ISSUE THREAD

**Issue by beqjanus** [codota/tabnine-vscode#1457]
Type: <b>Bug</b>

For a while now my TabNine has had the frustrating habit of dying miduse. It seems to happen less when using GPT4 model but that's purely anecdotal I have no hard data to support that thought. 

The extension will be happily running, I'll ask it a question and it will answer, towards the end of the answer or just after it has stopped "typing", and typically before I have time to read the repsonse(!) it will blank the window completely. 
vscode still sees it as a running extension, however restarting the extension host will force it to reload. It will then be ok for one or two queries.

Extension version: 3.97.2001
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (8.88GB free)|
|Process Argv|--folder-uri file:///d%3A/src/phoenix-firestorm-PBR-539 --crash-reporter-id a4f477b7-2667-440b-988f-4989cce0fa82|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

gz#31460<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31460'>Zendesk ticket #31460</a>)</i>

**Comment by TzufTabnine** [comment]
Please send us a video of the issue
