### ISSUE TITLE
Not generating  code

### ISSUE THREAD

**Issue by kadivendipranay** [codota/tabnine-vscode#1473]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#32621<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32621'>Zendesk ticket #32621</a>)</i>

**Comment by TzufTabnine** [comment]
Hi ,
Can you please send a short video of the issue? Can you add logs?
