### ISSUE TITLE
Using TabNine in VSCode Remote-SSH

### ISSUE THREAD

**Issue by ilsaloving** [codota/tabnine-vscode#1482]
**please complete the following information:**

- OS version: Mac Sonoma 14.5
- Remote OS: Ubuntu 24.04
- Editor version [e.g. 1.45.0-insider]: 1.91.1
- Programming language: [e.g. js, ts, c++] N/A
- TabNine extension version: 3.131.0

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

```
19:45:01 GMT+0000 (Coordinated Universal Time) [INFO]: spawning binary with command: /home/ilsa.loving/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.185.0/x86_64-unknown-linux-musl/TabNine args: --print-version 

19:45:01 GMT+0000 (Coordinated Universal Time) [INFO]: spawning binary with command: /home/ilsa.loving/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.185.0/x86_64-unknown-linux-musl/TabNine args: --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.91.1 pluginVersion=3.131.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=ssh-remote vscode-extension-kind=2 vscode-theme-name=Default Dark Modern vscode-theme-kind=Dark vscode-machine-id=bfb8e425f0dc0f4f771756f2fb688ccb030a6d9564ed9058d9a2d41e473e342d vscode-is-new-app-install=false vscode-session-id=20e35810-0fa4-40a7-b48e-8af9531fc3691721850287096 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 

19:45:01 GMT+0000 (Coordinated Universal Time) [DEBUG]: capabilities resolved immediately 

19:45:03 GMT+0000 (Coordinated Universal Time) [ERROR]: validating /home/ilsa.loving/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.185.0/x86_64-unknown-linux-musl/TabNine timeout 
```

**Editor console logs:**

Help -> Toggle Developer Tools

Nothing appears in the VSCode console logs

**Issue Details:**
I am using VSCode's RemoteSSH functionality to do development on a remote host.  I was able to install the TabNine extension, however I am unable to sign in.  When I click on "Sign In" from the TabNine tab, or "Open Hub" from the bottom status bar, nothing happens.

I've tried forwarding port 5555 as suggested in other tickets, but that didn't help.

gz#33575<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/33575'>Zendesk ticket #33575</a>)</i>

**Comment by TzufTabnine** [comment]
Hi,
Are you behind Proxy/VPN/Firewall/Antivirus, or do you have some connectivity issues? Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).
Please send us the log files - https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode
