### ISSUE TITLE
Tab Nine icon not coming in sidebar 

### ISSUE THREAD

**Issue by mehuljariwala** [codota/tabnine-vscode#1489]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina] - M1 Pro 
- Editor version [e.g. 1.45.0-insider]: Version: 1.92.1 (Universal)
- Programming language: [e.g. js, ts, c++]: all
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

I don't see log file 

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#34099<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34099'>Zendesk ticket #34099</a>)</i>

**Comment by TzufTabnine** [comment]
Try right-clicking on the sidebar and enabling Tabnine. Please send us a screenshot of the issue.
