### ISSUE TITLE
Feature Request: Improve Tabnine with test running

### ISSUE THREAD

**Issue by Stephen-S-H** [codota/tabnine-vscode#1494]
OS version: Mac Sonoma 14.5
Editor version: VS-code 1.92.0
Programming language: any
TabNine extension version: 3.135.0
Feature request:

Improve Tabnine test running. The new test mode is pretty good, but it takes a very long time to generate tests this way, and they rarely work out of the box, which requires multiple rounds of running and correcting the test. 

Similar to CodiumAI, which works brilliantly in most scenarios. Either give Tabnine the ability to run and iterate its generated tests, or allow it access to the test results, so we can iterate using Tabnine chat more naturally. Currently I must:

1. Generate a test with Tabnine
2. Insert the test into a file
3. Run the test
4. The test fails
5. Open a new chat
6. Copy the error messages from the test run into the chat, along with a request to help fix the test code
7. Add the source file as context
8. Select the failing test in the editor so it is included, and Submit
9. Repeat as many times as needed.

There is a real opportunity to make this something that is truly usable for tests, right now it is not IMO.

gz#34115<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34115'>Zendesk ticket #34115</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Stephen-S-H , our product manager would like to meet you (Zoom) and hear about all your suggestions, would you be interested? If so, please state your time zone and email so that we can reach out to you.

**Comment by Stephen-S-H** [comment]
Sure! You can contact me via my LinkedIn. I don't really want to post my email here.
https://www.linkedin.com/in/stephen-sazdanoff-haynes/
