### ISSUE TITLE
Gigantic update size

### ISSUE THREAD

**Issue by boozook** [codota/tabnine-vscode#1502]
**please complete the following information:**

- OS version: Mac Sonoma 14.6.1
- Editor version: 1.92.2-VSCodium, Vscode 1.93.0-insider
- Programming language: -
- TabNine extension version: 3.147.0 / 3.147.2001

**Issue Details:**

From latest update vdb server grows in memory up to 14Gb (408Gb virtual memory).

<img width="851" alt="Screenshot 2024-09-03 at 00 13 26" src="https://github.com/user-attachments/assets/332bd42b-bda9-43cb-8203-e9546c3ff3b5">

Also downloaded models size is more than 20Gb. Is it okay?

<img width="1032" alt="Screenshot 2024-09-04 at 00 04 33" src="https://github.com/user-attachments/assets/79f9d899-7aac-467a-86f1-1cf5c1e302a3">

gz#34690<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34690'>Zendesk ticket #34690</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @boozook , please close the IDE, delete the VDB folder, and check again. Also, if there are some files that you don't want to index, please specify them.
https://docs.tabnine.com/main/welcome/readme/personalization/tabnines-personalization-in-depth#what-files-are-being-indexed

**Comment by boozook** [comment]
@TzufTabnine Thanks. Just to ensure, should I delete `~/Library/Application Support/TabNine/servers/vdb` directory including inner `vdb` executable?

**Comment by TzufTabnine** [comment]
@boozook Correct.
