### ISSUE TITLE
TabNine is crashing

### ISSUE THREAD

**Issue by leonardopsantos** [codota/tabnine-vscode#1507]
**Issue Details:**

If I make _any_ request to TabNine in VSCode, I get an "Analyzing your request" message that lingers for about 5 seconds, then VSCode restarts the window. I can not use any chat commands, anything.

My setup is a bit convoluted. I'm running VSCode on Win11, but I'm using the SSH remote extension to connect to a running Docker container (Dev Containers extension) to develop C++ code. I have worked with this setup (SSh + Dev Containers + TabNine) for over 3 years now, so I know the setup used to work very well.

Due to my company's policies, I can't work locally or outside the container, so I can't disable either of the extensions,

I tried:

1. Uninstalling the TabNine VSCode extension ,
2. Closing VSCode
3. Removing the `.vscode-remote-containers` and `.vscode-server` folders from the remote system.
4. Connecting back
5. Re-installing TabNine and trying to use it again

**System Information:**

- OS version: Windows 11
- VSCode:

```
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

- Programming language: C++
- TabNine extension version: 3.157.0

> Type `TabNine::config` in your editor, the logs are located at the bottom of the page

Typing `TabNine::config` does nothing, sorry.

[vscode-app-1726770685627.log](https://github.com/user-attachments/files/17064652/vscode-app-1726770685627.log)

gz#35090<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35090'>Zendesk ticket #35090</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @leonardopsantos Please try this - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
If it is still not working please send us the engine logs -  https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Logs-on-VSCode

**Comment by leonardopsantos** [comment]
Sorry for the (very, _very_) late reply. TN was sort of working fine when I went about looking for the logs, but now it's consistently crashing again.

> Please try this - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues

```sh
$ curl -w "\nRoundtrip time is: %{time_total}" https://c2.p.tabnine.com/health
{"ok":true}
Roundtrip time is: 0.192512
```

I also followed [Support Connectivity Checkup (Tabac)](https://drive.google.com/file/d/1CAALXjiMGgYFPsxQ26LYzRxaasa9x7U8/view):

```sh
$ ./TabNine --diagnose
Running Tabnine diagnostic tool
Connection to Tabnine update server... OK
Connection to Tabnine notification server... OK
Connection to Tabnine API... OK
Connection to Tabnine hub... OK
Connection to Tabnine inference root... Tabnine SaaS - skipping... OK
Connection to Tabnine inference service... OK
Midline Inference... OK
Snippet Inference... OK
Memory Size... OK
CPU Cores... OK
```

Starting from a "clean" state: VSCode is closed, no `vscode-server` instances running on the remote Docker instance:

```sh
$ ps ax | grep -i vscode
1658989 pts/4    S+     0:00 grep --color=auto -i vscode
```

Before closing, I configured the logs according to [Getting Logs on VSCode](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Logs-on-VSCode).

1. Started VSCode, connected to the remote Docker instance
2. Selected some C++ `struct`
3. Typed `/document-code` on the TN console
4. TN crashed after thinking for a while
    - The message was "remote extension closed unexpectedly" 
    - Engine logs are attached.

Thanks for your help

[TN_logs.zip](https://github.com/user-attachments/files/17952147/TN_logs.zip)
