### ISSUE TITLE
Support bash/sh in extension

### ISSUE THREAD

**Issue by slycordinator** [codota/tabnine-vscode#1508]
**please complete the following information:**

- OS version: Win10
- Editor version [e.g. 1.45.0-insider]: 1.93.0
- Programming language: bash/dash
- TabNine extension version: 3.159.0

**Issue Details:**
vscode extension doesn't seem to do anything directly for bash scripts.
In contrast, the tabnine sublime claims to support Bash and according to a comment on https://github.com/codota/TabNine/issues/104 , Bash itself is supported in TabNine.

For comparison:
In a Python script, the tabnine extension show a menu above all functions with menus for Edit, Test, Explain, Document, and Ask.

But in a bash script, this doesn't happen. None of the functions get the same kind of menu.

gz#35164<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35164'>Zendesk ticket #35164</a>)</i>

**Comment by TzufTabnine** [comment]
See our supported languages - https://docs.tabnine.com/main/welcome/readme/supported-languages
