### ISSUE TITLE
Can't Sign in

### ISSUE THREAD

**Issue by GodOfStrategy** [codota/tabnine-vscode#1509]
Type: <b>Bug</b>

i tried countless times to sign in, the sign in button just simply doesnt work. I also tried all the methods listed on Tabnine Official Website.

Extension version: 3.163.0
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.44GB free)|
|Process Argv|--crash-reporter-id a426a221-0f90-4157-8584-ddcedb57a19b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
autoexpandse:31146404
fje88620:31121564
iacca1:31144502
notype1:31143045
cc771715:31146322

```

</details>

gz#35281<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35281'>Zendesk ticket #35281</a>)</i>

**Comment by TzufTabnine** [comment]
Are you behind Proxy/VPN/Firewall/Antivirus, or do you have some connectivity issues? Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).
Try signing in to Tabnine using the token. Follow the steps [here](https://docs.tabnine.com/main/getting-started/misc/client-setup-saas/sign-in/using-an-authentication-token). It is better to use Chrome as your default browser.
Please send us the logs if it still not working.
