### ISSUE TITLE
unable to completely uninstall TabNine once installed

### ISSUE THREAD

**Issue by infact** [codota/tabnine-vscode#1510]
**please complete the following information:**

- OS version: WIN10
- Editor version vscode:
- Programming language: python
- TabNine extension version: 4.24.0

I can't remove the Tabnine process, even after uninstalling the Visual Studio code extension. It still shows that the TabNine 4.24.0 process is running.

I tried the following commands from vs code terminal window , but nothing worked 

Remove-Item -Recurse -Force "$env:USERPROFILE\.tabnine"

Remove-Item -Recurse -Force "$env:APPDATA\TabNine"

Remove-Item -Recurse -Force "$env:APPDATA\Code\User\globalStorage\tabnine.tabnine-vscode"

Get-Process TabNine* | Stop-Process -Force

but it fails with message 'cannot find path ....because it does 
not exist.

gz#35332<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35332'>Zendesk ticket #35332</a>)</i>

**Comment by TzufTabnine** [comment]
@infact , try this 0 https://support.tabnine.com/hc/en-us/articles/17823949049745-How-to-delete-Tabnine-completely-from-your-machine
