### ISSUE TITLE
I uninstall the extension from vscode but the changes I have done with the help of tabnine has been erased while deleting it. 

### ISSUE THREAD

**Issue by lagunxayush** [codota/tabnine-vscode#1511]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#35361<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35361'>Zendesk ticket #35361</a>)</i>

**Comment by TzufTabnine** [comment]
@lagunxayush What is the issue? Please elaborate
