### ISSUE TITLE
can I turnoff autocomplete in VS Code but still keep chat?

### ISSUE THREAD

**Issue by acypher** [codota/tabnine-vscode#1518]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#36055<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36055'>Zendesk ticket #36055</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, you can use the snooze button - https://docs.tabnine.com/main/getting-started/getting-the-most-from-tabnines-code-completion/pause-snooze
