### ISSUE TITLE
/code-explore 

### ISSUE THREAD

**Issue by vinmutua** [codota/tabnine-vscode#1522]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#36259<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36259'>Zendesk ticket #36259</a>)</i>

**Comment by vinmutua** [comment]
Workspace context needs to be enabled in order to use the Code Explorer agent.

**Comment by TzufTabnine** [comment]
That is correct.
