### ISSUE TITLE
Can't use copy ( Ctrl C and Right mouse) in Tabnine Chat with Rider

### ISSUE THREAD

**Issue by kimduc14092003** [codota/tabnine-vscode#1527]
- OS version: Win11
- Editor version [e.g. 1.45.0-insider]: JetBrains Rider 2024.3
- Programming language: C#, Unity
- TabNine extension version: 1.163.0

Can't using copy in Tabnine Chat 

gz#36641<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36641'>Zendesk ticket #36641</a>)</i>

**Comment by TzufTabnine** [comment]
@kimduc14092003 Is the copy button not functional? Can you add a screen recording please?

**Comment by kimduc14092003** [comment]
> @kimduc14092003 Is the copy button not functional? Can you add a screen recording please?

https://drive.google.com/file/d/1U_TmOI35EEoaohzTf_xEXwwoPHwJvzIQ/view?usp=drive_link

**Comment by TzufTabnine** [comment]
It is currently not supported. We might add it in the future
