### ISSUE TITLE
Tabnine consistently resets in the middle of a trouble shooting session.  Logs me out and I have to start all over--very frustrating.

### ISSUE THREAD

**Issue by gkingkcc** [codota/tabnine-vscode#1530]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#37021<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37021'>Zendesk ticket #37021</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, Can you please add a screen recording? Logs?

**Comment by gkingkcc** [comment]
Hi TzufTabnine, can we open my ticket up again?

**Comment by TzufTabnine** [comment]
Hi, Can you please add a screen recording? Logs?

**Comment by gkingkcc** [comment]
Check out this video from Gerald King https://king-commercial-capital.dubb.com/v/sZpnm8 

This short clip is typical of what happens when I use Tabnine.  Also, going through the process of just logging in is troublesome.  It sometimes takes multiple attempts to log in, and then once I'm in and start communicating with Tabnine/Claude or troubleshooting, I get logged out.

**Comment by TzufTabnine** [comment]
We released a fix a few days ago. Can you please delete Tabnine entirely from your machine - https://support.tabnine.com/hc/en-us/articles/17823949049745-How-to-delete-Tabnine-completely-from-your-machine
Then reinstall and try again. If it is still not working, please send us the logs - https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Logs-on-VSCode
