### ISSUE TITLE
Tabnine does not start when I open a project

### ISSUE THREAD

**Issue by KazemaRyukuro** [codota/tabnine-vscode#1532]
**please complete the following information:**

- OS version: Win 11
- Editor version [e.g. 1.45.0-insider]: 17.12.2
- Programming language: all
- TabNine extension version: 1.155.1

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

I have the problem that Tabnine can no longer be started when I open a project in Visual Studio. An error message appears immediately. The hub cannot be started and the settings in VS cannot be loaded either. The error should be in “ActivityLog.xml”, but I can't upload it here.
![image](https://github.com/user-attachments/assets/c0e073a0-52d3-41e2-9c7b-b75042adca05)

gz#37102<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37102'>Zendesk ticket #37102</a>)</i>

**Comment by TzufTabnine** [comment]
Our developer would like to meet with you and solve the issue.
Please make your appointment here:
https://calendly.com/yonidavidson-visualstudio-2022/meet

**Comment by TzufTabnine** [comment]
@KazemaRyukuro Can you update your plugin and try again?

**Comment by KazemaRyukuro** [comment]
I have done the update and it starts again without errors. I can also log in normally. Thank you very much.
