### ISSUE TITLE
Procedure to enable TabNine for VSCode Jupyter Notebook?

### ISSUE THREAD

**Issue by rickhg12hs** [codota/tabnine-vscode#178]
What is the procedure to enable TabNine in VSCode's Jupyter Notebook?  Typing `TabNine::sem` doesn't appear to do anything.

**Comment by boaz-codota** [comment]
Hey @rickhg12hs thanks for reaching out!

TabNine for Jupyter Notebook is a community effort that is not managed by us. Instructions could be found at the repository: https://github.com/wenmin-wu/jupyter-tabnine

Thanks again!

**Comment by rickhg12hs** [comment]
It seems they punted on supporting VSCode.  wenmin-wu/jupyter-tabnine#8
