### ISSUE TITLE
De-prioritized TabNine suggestions to be at the end of the list

### ISSUE THREAD

**Issue by elovin** [codota/tabnine-vscode#179]
**please complete the following information:**

- OS version: ArchLinux kernel 5.9.1
- Editor version: 1.50.1
- Programming language: php,TypeScript,bash
- TabNine extension version: 2.8.8

**Issue Details:**

This is a feature request

The current official TabNine is unusable for my colleagues and myself because we can not change the suggestion priority.

We need the priority to come after the build in suggestions otherwise we get less useful suggestions at the top most of the time.

This problem is faced by a lot of people since there is an [unofficial TabNine extension](https://github.com/svipas/vscode-code-autocomplete) for vscode which does just that.

With that feature TabNine is a great tool to reduce repetitive typing tasks.

So can you please take look at this unofficial extension and add a way to change the suggestion priority ?

**Comment by boaz-codota** [comment]
Hey @elovin thanks for reaching out to us!

Thanks for the suggestion, we will try to address that in upcoming releases.

Thanks, Boaz.
