### ISSUE TITLE
Problems of using Tabnine in. Remote-ssh machine

### ISSUE THREAD

**Issue by wasedawesley** [codota/tabnine-vscode#196]
**please complete the following information:**

- OS version: ssh to remote machine(ubuntu)
- Editor version [e.g. 1.45.0-insider]:
- Programming language: python
- TabNine extension version: 3.1.5

I have installed Tabnine in my ssh-linked machines like this
![image](https://user-images.githubusercontent.com/29596659/98510886-dba2f880-229e-11eb-8cdc-5785a6c84c3f.png)

but I can't open the Tabnine config, and the autocomplete function didn't work very well
![image](https://user-images.githubusercontent.com/29596659/98510865-d2b22700-229e-11eb-9617-a61914d86e53.png)

**Comment by Loovelj** [comment]
See https://tabnine.com/faq#browser_failed
