### ISSUE TITLE
TabNine::config_dir doesn't work

### ISSUE THREAD

**Issue by mitming** [codota/tabnine-vscode#197]
- OS version: [Win 10]
- Editor version [1.51.0]:
- Programming language: [python]
- TabNine extension version:3.15

I use remote ssh extension and I want to use tabnine on a machine without a GUI, when I try

* Copy a working config file from another machine. You can find the file location by typing TabNine::config_dir and adding tabnine_config.json to the end of the path.

I found that the command `TabNine::config_dir` doesn't work!!!!!!!!
![image](https://user-images.githubusercontent.com/73068772/98513295-97b1f280-22a2-11eb-9814-f42b0cf833ba.png)

When I use command `TabNine::config`, it couldn't start a web browser.
![image](https://user-images.githubusercontent.com/73068772/98513424-cb8d1800-22a2-11eb-962e-423c16582da8.png)

By the way, you said there is another way to solve this:

* Use port forwarding to view the config panel from your local machine. If your remote machine's address is janedoe@123.45.67.89, and TabNine is listening on port 5555, the following command will do this: ssh -L `5555:127.0.0.1:5555 janedoe@123.45.67.89`

but it doesn't work too

![image](https://user-images.githubusercontent.com/73068772/98513746-540bb880-22a3-11eb-96df-f90703f63fe5.png)

**I just want to use TabNine, why it is so hard?**

**Comment by boaz-codota** [comment]
Sorry for the bad experience @mitming, we will look into it and provide a solution ASAP.

Thank you very much for caring deeply and contacting us.

**Comment by yanir-codota** [comment]
Hi @mitming , 
Apologies for the late response, 

please be advised that 'TabNine::config_dir' is an editor command and should be typed inside the IDE editor directly and not using the command palette (as appears from the screenshots you've provided).

when typing it inside of a file, you should expect to see something similar to the following:
![image](https://user-images.githubusercontent.com/66241883/99155892-d1c92d00-26c4-11eb-90a1-f1545b239c6c.png)
