### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dioggosoares** [codota/tabnine-vscode#205]
when upgrading to version 3.1.8 typescript turns off intelisense in vscode 1.51.1.

**Comment by dimermichel** [comment]
I'm experiencing the same bug running with Typescript Version 4.0.5 and Vscode Version 1.51.1. No IntelliSense.

**Comment by boaz-codota** [comment]
We've just released a fix to address this: https://github.com/codota/tabnine-vscode/releases/tag/v3.1.9

Please upgrade let us know that everything is now working

**Comment by boaz-codota** [comment]
Relates to: https://github.com/codota/tabnine-vscode/issues/204
