### ISSUE TITLE
TabNine causes typing to be unreasonably slow when used with the Vim extension

### ISSUE THREAD

**Issue by evaera** [codota/tabnine-vscode#214]
- OS version: Win 10
- Editor version: 1.51.1
- Programming language: Rust
- TabNine extension version: 3.1.10

**Issue Details:**

When used with the [VSCodeVim](https://github.com/VSCodeVim/Vim) extension, TabNine causes keystrokes to appear unreasonably slowly. This is probably because the Vim extension isn't able to process the keystroke until TabNine finishes its thinking.

This gets better on low power mode, but seemingly makes results worse?

It would be ideal if you could somehow let the other extension process keystrokes *before* TabNine. If not, maybe an option to process suggestions in a non-blocking way? Or an option to throttle running TabNine to a max frequency?

**Comment by boaz-codota** [comment]
Hey @evaera thanks for reaching out to us about that!

I'm truly sorry for the late response, and would love to help you get into the bottom of this.

VSCode's suggestions mechanism is collecting suggestions from numerous plugins on every keystroke, and is waiting for all to finish before providing suggestions. To make sure it does not block this mechanism, Tabnine has a timeout after 1 second if it fails to gather a response from the sidecar binary.

At any step Tabnine should not interfere with the keystrokes and make it appear slow. So I'll need more information to solve this issue. Could you provide (and I know this is a big request from you) a video with and without Tabnine?

Waiting for your response, Boaz.

**Comment by evaera** [comment]
With TabNine: https://i.eryn.io/2049/t6w76fxF.mp4

Without TabNine: https://i.eryn.io/2049/kd7kt5QG.mp4

**Comment by eamodio** [comment]
I'm experiencing the same without using the Vim extension. Can easily reproduce by just holding down the space bar and instead of it continuously repeating spaces, it starts ok, but then hangs (until I let go of the spacebar) and my PC fans go nuts.

**Comment by yanke1311** [comment]
If you met the problem that after thinking, the cursor of vscode-vim and tabnine were at the different place?

**Comment by alber70g** [comment]
For me the problem with VSCodeVim and this extension, is that in _insert_ mode, it does complete, but it does _not_ go to the end of the inserted statement.
