### ISSUE TITLE
Cannot prioritize other suggestions over TabNine

### ISSUE THREAD

**Issue by AlanLeeMoven** [codota/tabnine-vscode#223]
**please complete the following information:**

- OS version: Mac Catalina 10.15.7
- Editor version: 1.51.1
- Programming language: js
- TabNine extension version: v3.1.12

**Issue Details:**

JS intellisense suggestions (in this case fed through `npm intellisense` -> `path intellisense`) are almost always the value I want when they appear, since they are generated from real, identifiable properties (e.g. properties on from a defined object, named imports from a file in the project, props on a JSX component). Is there a way to change the priority of tabnine suggestions, or for tabnine to validate suggestions in this manner?

"BalanceType" is a named export within `.../enums`, validated by the intellisense suggestions seen below the tabnine suggestions.
<img width="470" alt="Screen Shot 2020-11-20 at 10 57 09 AM" src="https://user-images.githubusercontent.com/42143955/99839432-8c22bf00-2b1f-11eb-8397-93043c8bff4a.png">

**Comment by boaz-codota** [comment]
Hey @AlanLeeMoven thanks for reaching out to us!

We currently don't have plans to deprioritize Tabnine's suggestions. That said, we are experimenting with smaller number of suggestions (and would love your take on what would be your idea of the best number of suggestions from Tabnine) and always working on providing better suggestions (unlike those you received in the example provided). 

Currently there is no magic bullet I can provide you that will solve that behaviour, but we are working relentlessly to make Tabnine better, and we hope to resolve such issues promptly.

Thank you. Boaz.

**Comment by kylecordes** [comment]
A fellow developer here gave up on Tabnine because it pushed down the other suggestions so far that it got in the way of common cases were no AI or ML is needed. So far I've been tolerating those cases.

Tabnine needs to make the IDE better without also making it worse.

**Comment by eamodio** [comment]
Yeah, I feel the same here -- I like the TabNine suggestions in general, but there are quite a few cases where they get in the way of the others that I want.

**Comment by elovin** [comment]
There is[ a fork of this plugin](https://github.com/svipas/vscode-code-autocomplete) which makes tab9 usable.
