### ISSUE TITLE
Reuse tab9 binaries across different editors

### ISSUE THREAD

**Issue by fan-tom** [codota/tabnine-vscode#225]
**please complete the following information:**

- OS version: Mac Mojave
- Editor version: 1.51.1
- Programming language: any
- TabNine extension version: 3.1.10

**Issue Details:**
I use tabnine in VSCode and Intellij IDEs. Itellij IDEs download tab9 binaries into `~/.tabnine` directory, while VSCode extension downloads them into `~/.vscode/extensions/<tabnine ext dir>/binaries`. I'd suggest to use one global directory for tab9 executables to save disk space

**Comment by boaz-codota** [comment]
Hey @fan-tom thanks for reporting this issue!

We are working on a solution to this problem, and sorry that this affects you. We will remove older versions automatically, so Tabnine won't be such a burden on disk space (each version is roughly 20mb in size).

This will take us some time (we want to make sure we do this right). 

Sorry for the inconvenience, you can currently manually delete older versions of Tabnine's binary (we follow [semver](https://semver.org/), so leave the 2 latest versions and remove the rest).
