### ISSUE TITLE
Inserted placeholders are not accessible

### ISSUE THREAD

**Issue by Crazy-Owl** [codota/tabnine-vscode#23]
When editing python code (with Python extension `ms-python.python` installed and activated) some of completions are inserted with placeholder strings like `${1:filename}` etc. This strings suggest that they are to be navigated by pressing `<tab>`, yet this does not happen. I also have `vscodevim.vim` plugin enabled, which can interfere with this.

Can these placeholders be turned off somehow?

**Comment by zxqfl** [comment]
Hm, that's surprising: TabNine doesn't use placeholders in the format you're describing. Are you sure those suggestions are coming from TabNine?

**Comment by Crazy-Owl** [comment]
These strange placeholders started appearing right after I've started using TabNine, but they may be as well provided by other extension, namely `ms-python.python`. I also see TabNine frame regarding the size of the source code next to these variants, so I thought they're coming from TabNine. It may be that TabNine proxies suggestions from other completion engine and placeholders somehow get lost in process.

This is what it looks like:

![image](https://user-images.githubusercontent.com/179961/53885272-575e9380-402e-11e9-86f7-076a1727d516.png)

If these messages are unrelated to TabNine then I'm sorry to bother you about that.

**Comment by zxqfl** [comment]
Could you please provide a series of steps (eg. extensions to install and commands to run) that reproduces this issue?
