### ISSUE TITLE
Ask to open webpage every time I start the container

### ISSUE THREAD

**Issue by lorenzotinfena** [codota/tabnine-vscode#232]
- OS version: Win 10
- Editor version 1.52.0-insider
- Programming language: python
- TabNine extension version:

I'm using this extension i a remote container, with remote container extension
If I add this extension id ("tabnine.tabnine-vscode") in container.json, every time I start the container, it ask me to open your webpage https://www.tabnine.com/welcome/ , I suppose that every time vs code install the extension (at every container launch) it ask that

**Comment by boaz-codota** [comment]
Hey @LorenzoTinfena thanks for submitting an issue!

I'd love to know more about the setup to help you:
* How are you opening vscode in a container?
* Is it possible for you to persist some state in the container?

Sorry for inconvenience and the late response and thanks again for reaching out to us with that issue!

**Comment by LorenzoTinfena** [comment]
I'm opening the container in vs code with https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers (you can also check my repo), from what I understood is possible to persist vscode-server data when the container is down, but if I change computer, or I have to change some configuration files, that I have to rebuild the container, when I rebuild all data are lost and all extensions are reinstalled. I'm new in this extension, so don't trust me. This isn't a real a problem, but I thinked was useful tell it

**Comment by yuvalorsher22** [comment]
Here to say that I'm also experiencing this problem :)
I'm logged to an AWS container via ssh.
Any updates on the matter?
