### ISSUE TITLE
can tell us each changelog of every updating

### ISSUE THREAD

**Issue by heartacker** [codota/tabnine-vscode#235]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
every time tabnine -extension updated. nobody konw  what changed.

**Comment by boaz-codota** [comment]
Hey @heartacker thanks for raising that concern with us!

We have been too focused on implementation lately, not documenting and communicating well enough what is changing. 
We understand deeply what you are complaining about, and will do our best to best document the changes (probably the public github repository could house this changelog best).

Thanks for the feedback!
