### ISSUE TITLE
Setting/Option/Config to turn off Tabnine auto-closing quotes (useful for Markdown)

### ISSUE THREAD

**Issue by universemaster** [codota/tabnine-vscode#244]
OS version: 10.15.5 (19F101)
Editor version : 1.50.1
Programming language: Markdown
TabNine extension version: 3.2.28-0 

---

Requesting new config, due to the difficulty to fix bug #152, which has been closed on github without a fix, or timeline to fix.

Current behaviour.
1. I type:
Multiply Be

2. I press tab to select **Bezout's identity**
(note this looks OK in the dropdown, and does not contain an additional single quote at the end of the string).

3. I get:
Multiply Bezout's identity'

(with the cursor between the y and the end single quote.)

Required behaviour:

**I untick a checkbox "Always auto-close quotes" in TabNine Config:**

Now: I get:
Multiply Bezout's identity

without the quote at the end.

**Comment by boaz-codota** [comment]
Hey @universemaster, sorry for closing the other issue, as I understand that you care deeply about that behaviour.

As I said there, `this is some tough nuance to solve` and a solution is not coming soon.

I'll leave this issue open for us to reprioritise it and try to get to it ASAP.

Thanks!
