### ISSUE TITLE
Autocomplete is appending to text instead of overriding in vscode remote ssh

### ISSUE THREAD

**Issue by jordanmnunez** [codota/tabnine-vscode#25]
While using VS code's new remote ssh https://code.visualstudio.com/docs/remote/ssh

TabNine autocomplete selections are appending to the text instead of writing over what has already been typed.

![2019-05-07 09 59 30](https://user-images.githubusercontent.com/8227371/57318523-62c24f80-70af-11e9-9e8d-ff9315c84ae8.gif)

I have tested this on local files and it is not having the same problem.

**Comment by nganguemvict** [comment]
J'aime bien
