### ISSUE TITLE
[Suggestion] C# Razor files (.cshtml)

### ISSUE THREAD

**Issue by flopezre** [codota/tabnine-vscode#277]
- OS version: [Windows 10 Home 20H2]
- Editor version [1.52.1]:
- Programming language: [C# .NET Core]
- TabNine extension version: v3.1.23

[Edit]
Improve the HTML tags maybe CSS, Javascript in Razor files, please.
![razor_Csharp](https://user-images.githubusercontent.com/4932575/103185259-53060900-489a-11eb-9fc4-321529b090ef.gif)

Another example:
![razor_Csharp2](https://user-images.githubusercontent.com/4932575/103185676-2fdc5900-489c-11eb-8b8a-d529c91db435.gif)

Cheers.

**Comment by boaz-codota** [comment]
We currently train our models very modestly on `cshtml` files.

We will look into that.

Thank you for using Tabnine!
