### ISSUE TITLE
TabNine breaks VSCode Snippets

### ISSUE THREAD

**Issue by hnrw** [codota/tabnine-vscode#279]
**please complete the following information:**

- OS version: Ubuntu 18 on WSL2
- Editor version [e.g. 1.45.0-insider]: 1.52.1
- Programming language: js
- TabNine extension version: v3.1.23

**Issue Details:**

I have a VS Code snippet `f`, that simply returns a js arrow function.

TabNine suggestions sometimes override my snippet, and don't allow me to select it.

In the video below, you'll see the snippet works fine when I type it on an empty line. But if TabNine has given me a suggestion, like it does after a `useEffect()`, then the suggestions won't update with my snippet. I have to delete and re-enter the `f`.

https://user-images.githubusercontent.com/61143948/103359169-4e666e00-4aaf-11eb-9702-7c8ed2e8740f.mp4

When I disable TabNine, the snippets work perfectly in both cases.

![2020-12-30_14-52-33](https://user-images.githubusercontent.com/61143948/103359612-157ac900-4ab0-11eb-8a09-8b835f9a7dd4.gif)

**Comment by boaz-codota** [comment]
This seems like an issue with how VSCode's suggestions work. VSCode exposes no API that might allow us to intervene nor block any suggestions not originating from our plugin.

Please submit this ticket on VSCode repository: https://github.com/microsoft/vscode/issues
