### ISSUE TITLE
How do I set the plug-in to ignore the prompts in the YML file

### ISSUE THREAD

**Issue by AirBashX** [codota/tabnine-vscode#280]
The experience I had using the plug-in in a Docker-composer. Yml file was far less useful than other plug-ins provided by Vscode, so a hint that I would like to disable the plug-in when using a YML file is there any way

**Comment by dimacodota** [comment]
@AirBashX  - you can disable Tabnine in vscode by setting  `tabnine.disable_file_regex:  ["[.]yml$"]`
