### ISSUE TITLE
"CPU not supported, click to resolve" message in status bar, even though it worked before

### ISSUE THREAD

**Issue by garyking** [codota/tabnine-vscode#289]
**please complete the following information:**

- OS version: macOS Mojave 10.14.6
- Editor version [e.g. 1.45.0-insider]: 1.52.1
- Programming language: [e.g. js, ts, c++] JavaScript
- TabNine extension version: 3.1.25

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

I don't see any logs at the bottom of the TabNine Hub.

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

I've been using TabNine for months, and starting this morning, I see the message "CPU not supported, click to resolve" in the VS Code status bar, even though I haven't changed anything.

How can I resolve this?

**Comment by sar** [comment]
Just ran into the same issue, here's a quick workaround.

* Open Extensions pane in VS Code
* Click the cog next to TabNine and select **Install Another Version**
* Roll back to ``3.1.8``

Devs, has it been updated to support only CPUs with AVX2 instruction set or just another bug to squash?

**Comment by garyking** [comment]
I was helped by someone on the Slack channel. I had to upgrade to Tabnine Cloud Lite to get the features back.
