### ISSUE TITLE
Fix the code completion at the end of statements/lines.

### ISSUE THREAD

**Issue by thewhiterabbit** [codota/tabnine-vscode#313]
Tabnine needs to know that when you type "fi", "end if", "EOF", or any other blatantly obvious end of a statement block, that tabnine should NOT try to auto complete so that when you press enter the damn thing isn't going to replace the "end if", or whatever, with bull$h!t that isn't even remotely relevant to your code.

Removed until this neglectful oversight is fixed because native code completion is 10x smarter than tabnine is at this point in VSCode.

Sorry for being this straight-forward, and critical, but I tried this plugin for a week and it was more debilitating than it was helpful.

Literally every end of statement was replaced with junk text that forced me to use the mouse and disrupt my flow of coding.

Very annoying to say the least.

Fix it! You can do much better. I have faith.

**Comment by boaz-codota** [comment]
Hey you. Thank you for the feedback!

We do our best to ever improve the suggestions we provide, but Tabnine by nature is a non deterministic product. It uses machine learning models for the predictions, so it give some truly bad suggestions.

I'm sorry to hear that your experience was that bad, and the cons out weighted the pros. This is something we try hard to improve, and hope to have some breakthroughs in the near future.

Thank you for trying out Tabnine, and thank you for taking the time to provide us feedback.
