### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by jiahao-shen** [codota/tabnine-vscode#32]
The TabNine information shows that the Activate is "No". And it always tell me "Establishing connection to TabNine Cloud..."

![image](https://user-images.githubusercontent.com/29255648/61929976-0df7ec00-afaf-11e9-95bc-37f45cefb93c.png)
![image](https://user-images.githubusercontent.com/29255648/61929982-10f2dc80-afaf-11e9-9a4a-bb8ad61e4ea4.png)

**Comment by zzzzqqqa** [comment]
Same here. It seems it is due to the lack of proxy support.
