### ISSUE TITLE
Slow extension update

### ISSUE THREAD

**Issue by halilim** [codota/tabnine-vscode#321]
- OS version: macOS Big Sur 11.1
- Editor version: 1.52.1
- TabNine extension version: v3.2.6

**Issue Details:**
The extension takes a long time to update. This gets more noticeable on slower connections, especially on a mobile hotspot. `~/.vscode/extensions/tabnine.tabnine-vscode-3.2.6` is 277 MB and 276 MB of it is `binaries`, which includes all of the 6 files for different platforms. It can be considered as a disk space problem too. I'd suggest keeping only the relevant binary, if that's possible.

**Comment by bilucodota** [comment]
Hi @halilim 
Sorry for the late response. Closing it for now as it is definitely on our road-map.
