### ISSUE TITLE
TabNine:: config not found

### ISSUE THREAD

**Issue by TonyGoods** [codota/tabnine-vscode#322]
**please complete the following information:**

- OS version: Mac Catalina
- Editor version: vs code : 1.41.1
- TabNine extension version:

hi👋 ,
very want to use this, but there always has this issue. 
Please help me. 
Thanks~

![image](https://user-images.githubusercontent.com/37533242/106862689-6bbbd700-6702-11eb-85ba-5e42a2baadfe.png)

**Comment by boaz-codota** [comment]
Yea we know it is confusing, but type `tabnine::config` in the code editor, where you edit your code (write it as you'd write code):
![image](https://user-images.githubusercontent.com/69103343/106863148-c6d4d600-66d0-11eb-9dff-df2a385f587a.png)

We had also implemented a command for vscode that you could use (which is better, as it opens in a native experience):
![image](https://user-images.githubusercontent.com/69103343/106863221-da803c80-66d0-11eb-955a-e862ac58b798.png)

Or, you could just click on the navbar item (this is probably the easiest) in the bottom of the IDE:
![image](https://user-images.githubusercontent.com/69103343/106863314-fc79bf00-66d0-11eb-8de7-241e2c7cf2b1.png)

**Comment by TonyGoods** [comment]
thanks for your reply.
I do this, but also don't have this
![image](https://user-images.githubusercontent.com/37533242/106863520-9e1a0400-6703-11eb-939d-4cf9488b681b.png)

**Comment by boaz-codota** [comment]
Are you getting Tabnine predictions at all?

**Comment by TonyGoods** [comment]
Did you mean this? I think I have got
![image](https://user-images.githubusercontent.com/37533242/106877516-cdd10800-6713-11eb-837a-e890eedfc558.png)

**Comment by boaz-codota** [comment]
When you write code, are you getting completions from Tabnine?

Also, if you click on the `tabnine` status bar item, does it open up the `Tabnine Hub`? Could you post a screenshot of it?

**Comment by TonyGoods** [comment]
I'm at home, and can't screenshot, now. In my mac, I don't have the tabnine in the status bar. And don't get the completions from Tabnine. I have uninstalled and installed, also can't. But in my windows, all done well.

**Comment by boaz-codota** [comment]
If you don't have the status bar at all, there are only 1 reason I can think about, and it is that you have a really old version, or some fault state.

The way vscode manages plugins (uncompress the vsix file to a folder and just run it from that folder) can sometimes cause faulty states for plugins that we can't help you fix.

The only solution I think will work is to delete vscode and reinstall it.

Sorry, but I can't think of another reason as why this is happening.

**Comment by TonyGoods** [comment]
ok, I will try to uninstall vs code, and try again. thank you again.

**Comment by TonyGoods** [comment]
hi, I have update my vs code, and all were resolved. thanks again for your help. Love TabNine very much! @boaz-codota
