### ISSUE TITLE
VS Code via TabNine constant hassle with Little Snitch due to missing code signature

### ISSUE THREAD

**Issue by crs1138** [codota/tabnine-vscode#324]
**please complete the following information:**

- OS version: MacOS Mojava 10.14.6 (18G7016)
- Editor version [e.g. 1.45.0-insider]:  1.52.1
- Programming language: any
- TabNine extension version: 3.2.6

**Issue Details:**

I can't set up a permanent rule for Little Snitch due to missing code signature.

```
Warning
For security reasons, an existing rule for any process was not applied to “TabNine”!
The process has no code signature. This means that the developer is anonymous and their real-life identity cannot be determined. Since the existing rule matches any process, it cannot specify identification characteristics for a particular process. Depending on whether you trust the program, create a specific rule to allow or deny the connection for this program only.
```
![image](https://user-images.githubusercontent.com/1313681/106921973-d3771f80-670c-11eb-8561-fea35253f85e.png)

**Comment by boaz-codota** [comment]
Thanks for reporting the issue @crs1138 . 

We are working to resolve this. There is some bureaucracy regarding anything when it comes to Apple.

Thank you for the understanding, and sorry it is yet to be fixed.

**Comment by mhdhejazi** [comment]
The same applies to Android Studio. It's not a single alert but four or five for me. It gets very annoying to repeatedly deal with those alerts every one hour or so.

**Comment by boaz-codota** [comment]
Sorry you are experiencing that @mhdhejazi , we are working towards resolving that issue.

**Comment by crs1138** [comment]
@bilucodota issue's closed - yay! Does that mean I can give Tabnine another chance as the problem has been resolved?

**Comment by pycckuu** [comment]
I think yes! I have not seen for a while LS messages about Tabnine )

**Comment by crs1138** [comment]
That doesn't seem to be the case for me.

**Comment by bilucodota** [comment]
Hi guys - @crs1138 @pycckuu 
Not just yet. But support is coming soon. Will keep you posted.

**Comment by crs1138** [comment]
Thank you for the info @bilucodota – however, please forgive me though, according to what you just wrote, the issue doesn't seem very _closed_ to me.
