### ISSUE TITLE
Tabinine not working  : Activating extension 'TabNine.tabnine-vscode' failed: Cannot find module 'typemoq'

### ISSUE THREAD

**Issue by saurav9878** [codota/tabnine-vscode#325]
- OS version: Ubuntu 20.04.1 LTS
- Editor version [e.g. 1.45.0-insider]: VSCode 1.53.0
- Programming language: [e.g. js, ts, c++] Javascript
- TabNine extension version: 3.2.6

Unable to open Tabnine::config

**Editor console logs:**
```
Activating extension 'TabNine.tabnine-vscode' failed: Cannot find module 'typemoq'
Require stack:
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/mockedRunProcess.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/runProcess.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/runBinary.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/Binary.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/requests/requests.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/capabilities.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/alphaInstaller.js
- /home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
```
**Issue Details:**
 Initially, I thought the extension was not installed properly. I tried uninstalling, removing the folder inside extensions, and also local/share/tabnine models.
 Methods tried: I also went inside tabnine.tabnine-vscode-3.2.6 and ran npm install (tried even yarn) no luck. I was caught up with following error:
 ```
stack trace: TypeError: Cannot read property 'includes' of undefined
	at Object.executeStartupActions [as default] (/home/saurav/.vscode/extensions/tabnine.tabnine-vscode-3.2.6/out/binary/startupActionsHandler.js:10:93)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dimacodota** [comment]
Hi @saurav9878 - is it possible that you are running your node with the `NODE_ENV` environment variable set to `test`?

**Comment by saurav9878** [comment]
Hi @dimacodota , Thanks a ton for the help. **That was exactly the cause of the issue. I had `NODE_ENV=test` set globally.** I've been struggling to figure it out for the past 1 month. Even tried pairing various versions of Tabnine and VSCode. Nothing worked. You're a savior :)
