### ISSUE TITLE
remote vscode tabnine can not active

### ISSUE THREAD

**Issue by YanYeek** [codota/tabnine-vscode#331]
- OS version: Win 10 remote service：centos7
- Editor version :1.53.2
- TabNine extension version: 3.2.7

when i click active
![image](https://user-images.githubusercontent.com/48875922/107877227-06d45e00-6f06-11eb-942c-8ff8cb2400d2.png)
![image](https://user-images.githubusercontent.com/48875922/107877248-33887580-6f06-11eb-871b-534df697a53c.png)

 What should I do to ctivate tabnine？

**Comment by dimacodota** [comment]
@YanYeek - can you please forward port 5555?  
https://code.visualstudio.com/docs/remote/ssh-tutorial#_port-forwarding

**Comment by YanYeek** [comment]
> @YanYeek - can you please forward port 5555?
> https://code.visualstudio.com/docs/remote/ssh-tutorial#_port-forwarding

![image](https://user-images.githubusercontent.com/48875922/107877567-38e6bf80-6f08-11eb-9ce0-f1a7de0c8924.png)
Do I have the right Settings？

**Comment by dimacodota** [comment]
Can you share a screenshot of the tab when you click on the status bar?

**Comment by YanYeek** [comment]
> Can you share a screenshot of the tab when you click on the status bar?

![image](https://user-images.githubusercontent.com/48875922/107877935-59177e00-6f0a-11eb-821b-14890f3f1c8d.png)

**Comment by dimacodota** [comment]
I see that you opened the "Tabnine Home" now you need to sign up
<img width="1396" alt="Screen Shot 2021-02-14 at 16 53 01" src="https://user-images.githubusercontent.com/60742964/107880162-c2d16100-6ee5-11eb-9b3b-fea4ef284743.png">

**Comment by YanYeek** [comment]
> I see that you opened the "Tabnine Home" now you need to sign up
> <img alt="Screen Shot 2021-02-14 at 16 53 01" width="1396" src="https://user-images.githubusercontent.com/60742964/107880162-c2d16100-6ee5-11eb-9b3b-fea4ef284743.png">

Thank you very much for your help. I have solved it. The method used is to clear all the files under `~/.config/TabNine` and then reinstall it
