### ISSUE TITLE
Error on installing/activating VSCode extension in GITPOD

### ISSUE THREAD

**Issue by JonatasAmaral** [codota/tabnine-vscode#337]
**please complete the following information:**

- OS version: GITPOD's Ubuntu 20.04.1 LTS (Focal Fossa)
- Editor version: built-in Eclipse Theia / VSCode based editor (couldn't find a version number)
- TabNine extension version: 3.2.7, 3.2.5, 3.2.4, 3.2.3, 3.2.2 (all VSX versions)

**Editor console logs:**

Chrome's Developer Tools
If helps, here's all [3] logs filtered by "tabnine":

- `root WARN A contributed preference schema has validation issues : data.properties['tabnine.experimentalAutoImports'].type should be equal to one of the allowed values, data.properties['tabnine.experimentalAutoImports'].type[1] should be equal to one of the allowed values, data.properties['tabnine.experimentalAutoImports'].type should match some schema in anyOf`
  ```
    (anonymous) ... @ logger.ts:312
    (anonymous) ... @ logger.ts:304
    Promise.then (async)
    e.log ... @ logger.ts:299
    n ... @ logger.ts:45
    n.doSetSchema ... @ preference-contribution.ts:172
    n.setSchema ... @ preference-contribution.ts:253
    (anonymous) ... @ plugin-contribution-handler.ts:134
    R ... @ plugin-contribution-handler.ts:125
    N ... @ plugin-contribution-handler.ts:134
    e.handleContributions ... @ plugin-contribution-handler.ts:133
    s ... @ hosted-plugin.ts:349
    e.loadContributions ... @ hosted-plugin.ts:342
    (anonymous) ... @ hosted-plugin.ts:271
    (anonymous) ... @ index.ts:19
    (anonymous) ... @ index.ts:19
    a ... @ index.ts:19
    Promise.then (async) 
    c ... @ index.ts:19
    a ... @ index.ts:19
    Promise.then (async) 
    c ... @ index.ts:19
    (anonymous) ... @ index.ts:19
    a ... @ index.ts:19
    e.doLoad ... @ hosted-plugin.ts:250
    (anonymous) ... @ hosted-plugin.ts:244
    (anonymous) ... @ progress-service.ts:77
    (anonymous) ... @ layout.js:777
    (anonymous) ... @ layout.js:777
    a ... @ layout.js:777
    Promise.then (async) 
    c ... @ layout.js:777
    (anonymous) ... @ layout.js:777
    a ... @ layout.js:777
    e.withProgress ... @ progress-service.ts:74
    (anonymous) ... @ hosted-plugin.ts:244
    (anonymous) ... @ index.ts:19
    (anonymous) ... @ index.ts:19
    (anonymous) ... @ index.ts:19
    a ... @ index.ts:19
    (anonymous) ... @ hosted-plugin.ts:242
    Promise.then (async) 
    load.d.leading ... @ hosted-plugin.ts:242
    _ ... @ index.js:160
    (anonymous) ... @ index.js:170
    E ... @ index.js:235
    (anonymous) ... @ hosted-plugin.ts:237
    (anonymous) ... @ event.ts:117
    e.invoke ... @ event.ts:125
    e.fire ... @ event.ts:267
    onDidDeploy ... @ hosted-plugin-watcher.ts:42
    e.onNotification ... @ proxy-factory.ts:182
    (anonymous) ... @ proxy-factory.ts:139
    (anonymous) ... @ main.js:502
    (anonymous) ... @ main.js:273
    (anonymous) ... @ main.js:260
    (anonymous) ... @ setImmediate.js:40
    d ... @ setImmediate.js:69
    a ... @ setImmediate.js:109
    postMessage (async) 
    r ... @ setImmediate.js:120
    h.setImmediate ... @ setImmediate.js:27
    $ ... @ main.js:258
    Q ... @ main.js:307
    value ... @ reader.ts:57
    (anonymous) ... @ reader.ts:18
    e.handleMessage ... @ web-socket-channel.ts:49
    e.handleIncomingRawMessage ... @ abstract-connection-provider.ts:111
    r.onmessage ... @ ws-connection-provider.ts:54
    _handleMessage ... @ reconnecting-websocket-mjs.js:156
    e._callEventListener ... @ reconnecting-websocket-mjs.js:521
    (anonymous) ... @ reconnecting-websocket-mjs.js:158
    _handleMessage ... @ reconnecting-websocket-mjs.js:158
  ```

- `root INFO [85eab854-ce4f-4fba-90b1-862c39e0b65c][tabnine.tabnine-vscode]: Loaded contributions.`
- `root INFO [85eab854-ce4f-4fba-90b1-862c39e0b65c][tabnine.tabnine-vscode]: Started plugin.`

**Issue Details:**

When GITPOD tries to activate the extension, it pops an error:
`Activating extension 'Tabnine Autocomplete AI: JavaScript, Python, TypeScript, PHP, Go, Java, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React' failed: Cannot read property 'Light' of undefined`

![Screenshot (36)](https://user-images.githubusercontent.com/8677724/108600035-589c3e80-7373-11eb-867f-9fc06a4ce73e.png)

Them, the extension does nothing.

The latest `3.2.7` version of the extension does work on local machine (on VSCodium, telemetry free VSCode compile)
All other extensions used locally until today, also has worked on GITPOD.

**It looks related to React:**
[https://github.com/react-navigation/react-navigation/issues/7320]()
[https://github.com/react-navigation/react-navigation/issues/7065]()
[https://github.com/react-navigation/react-navigation/issues/7541]()
[https://github.com/pluralsight/design-system/issues/729]()

**Comment by talcodota** [comment]
Hey @JonatasAmaral,
I think you have a faulty tabnine config value on your vs-code settings.
Please go to your vs-code settings JSON file and find  - tabnine.experimentalAutoImports.
What is its value?
Please change it to true and update us.
Thank you.

**Comment by JonatasAmaral** [comment]
No, did it on [2] blank GITPOD Workspaces, the `setting.json` files are all empty (no user/workspace configs set)

Also, my local VS Code (the one that works) has `"tabnine.experimentalAutoImports": true,`
Setting up the same option in GITPOD's config, doesn't help.

Finally, just to make it clear, GITPOD's editor is **Eclipse Theia**, witch is web editor, _based/inspired_ by VS Code, but not exactly the same.

**Comment by bilucodota** [comment]
Hi @JonatasAmaral,
It seems like gitpod are using an outdated version of `theia`. This version misses a property which Tabnine is looking for.
I've opened a [request](https://github.com/gitpod-io/gitpod/issues/3249) (give it thumbs up!) at gitpod's to update `theia` to the latest version. Hope they will soon.

**Comment by JonatasAmaral** [comment]
Just did it over there

**Comment by bilucodota** [comment]
Closing this is for now. Let us know if you need any further assistance.
