### ISSUE TITLE
Computer restarts

### ISSUE THREAD

**Issue by MroseQ** [codota/tabnine-vscode#338]
- OS version: Win 10 Pro N
- Editor version : 1.53.2
- Programming language: HTML,js
- TabNine extension version: 3.2.7

**Issue Details:**

Every time when I open VSC with tabnine extension enabled after approximately 1 minute my computer just reboots. Nothing more really happens. That's the only thing and it's underwhelming. Can you tell me what should I do?

**Comment by talcodota** [comment]
Thanks for reporting this.
Can you please share the content of the developer tools - console tab before the PC reboots? (Help => Toggle Developer Tools => Console)

**Comment by MroseQ** [comment]
![tabnine1](https://user-images.githubusercontent.com/46853552/108628925-ba38d780-745d-11eb-9da2-5fd9744b8d2c.PNG)
The first three errors are not related to the case as I just moved the files to another director.

**Comment by talcodota** [comment]
Thank you @MroseQ!

Sorry, I will need more information in order to be able to help.
Please set Tabnine logs to write to your disk, and after your PC restarts share the log file here or send it directly to me.

This is how you do it:
* Go to vs-code settings
* Type 'tabnine' in the search box
* You should see the option: 'Tabnine: Log File Path'
* Enter a path you would like the log file to be saved in (including the log file name)

Thanks.

**Comment by MroseQ** [comment]
I've managed to insert the log path, but now the computer restarts after 5 seconds from starting VSC. How will the log file be named?

**Comment by MroseQ** [comment]
I opened the VSC again, yet no log file is visible. Maybe the reboots are too fast for the program to make a log file :/

**Comment by talcodota** [comment]
It could be the case.
The log file should be named by the file name that was entered on your path.
For example, if my path is:
/Users/some-user/logs/tabnine
So my log file name will be: tabnine

**Comment by MroseQ** [comment]
Oh... so if that's the case... the files should be named Desktop because I assumed that it would finish the path on its own.
[wd_log.txt](https://github.com/codota/tabnine-vscode/files/6018009/wd_log.txt)
And I found it, but there are two files. The txt above and the "Desktop-11972" file with no extension, which I can't upload. I hope you can manage something with the txt though.

**Comment by talcodota** [comment]
I will need the other file.
Try sending it to support@tabnine.com
Thanks.

**Comment by MroseQ** [comment]
i've sent it. Good luck <3
