### ISSUE TITLE
ValidatorClient.js: Unexpected token - TabNine can't initialize

### ISSUE THREAD

**Issue by heroje** [codota/tabnine-vscode#356]
- OS version: Windows 10 20H2 19042.804
- Editor version: 1.53.2 (user setup)
- Programming language: JS
- TabNine extension version: 3.2.8

_If the issue is related to TabNine failure, please provide log files:
Type `TabNine::config` in your editor, the logs are located at the bottom of the page_
-- nothing happens.
If I launch the "Tabnine: Open Settings'" command, I get a message: 
"Command 'Tabnine: Open Settings' resulted in an error (command 'TabNine::config' not found)"

**Editor console logs:**
Log (Extension Host) output:
https://gist.github.com/heroje/918a534d7726e4926425d3dc94068f14
![dev cons err1](https://user-images.githubusercontent.com/45423203/109506435-e8419b80-7a9d-11eb-92fa-5544850423f5.png)
I found a mention of tabnine_config.json in other issues. Here's the contents of mine:
[tabnine_config.json.txt](https://github.com/codota/tabnine-vscode/files/6062087/tabnine_config.json.txt)

**Issue Details:**
The extension stopped launching for me. I don't see anything in the status bar, reinstalling it doesn't cause the launch page to pop up.

**Comment by boaz-codota** [comment]
@heroje can you run the binary manually and report back as I explained in this ticket:
https://github.com/codota/tabnine-vscode/issues/355#issuecomment-787975520

**Comment by heroje** [comment]
@boaz-codota Thank you for the fast reply!
Here goes the log:
[cmdlog.txt](https://github.com/codota/tabnine-vscode/files/6062286/cmdlog.txt)

**Comment by boaz-codota** [comment]
That is a weird question (and the answer is probably no), but is it possible that you run vscode using a custom old version of node? It just that I look at the error, and spread operator is available since [node 8.3.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax), and vscode 1.5.3 ships by default with newer node version, but you [can customize it](https://github.com/microsoft/vscode/issues/14229#issuecomment-312616519) so I'm wondering if it is possible that you have done so?

**Comment by heroje** [comment]
I don't think that's the case either, but I'd be interested if there's a way to double-check that VS Code is using the correct version.
Running the equiv. of which in Powershell gives me following:
```
PS C:\Users\Ann> Get-Command node
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     node.exe                                           15.4.0.0   C:\Program Files\nodejs\node.exe
PS C:\Users\Ann> node
Welcome to Node.js v15.4.0.
Type ".help" for more information.
```

**Comment by dimacodota** [comment]
@heroje - can you please share the  "About Visual Studio Code" info?  
<img width="302" alt="Screen Shot 2021-03-01 at 22 16 28" src="https://user-images.githubusercontent.com/60742964/109553735-0d54ff00-7adc-11eb-8376-a8c013e56df0.png">

**Comment by heroje** [comment]
@dimacodota 
Here goes:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by bilucodota** [comment]
Hi @heroje 
Didn't get to look into thoroughly yet, so can't tell the exact reason - but it seems like the [babel-transform ](https://marketplace.visualstudio.com/items?itemName=AndyHsu.vscode-babel-transform) breaks Tabnine extension. 
Try to disable it for now and see if Tabnine works. Please keep us posted.

**Comment by heroje** [comment]
@bilucodota 
Thank you so much - that does seem to be the case! Removing it did solve the issue, and since I don't need it at the time being, I'm happy leaving it off my install.

**Comment by bilucodota** [comment]
@heroje great!
