### ISSUE TITLE
TabNine spawning thousands of processes and clobbering computer

### ISSUE THREAD

**Issue by tigerhawkvok** [codota/tabnine-vscode#361]
**please complete the following information:**

- OS version: Windows 10
- Editor version [e.g. 1.45.0-insider]: 

```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

- Programming language: Python
- TabNine extension version: 3.2.8

**Issue Details:**

TabNine is spawning hundreds or thousands of child processes, clobbering the computer.

The computer starts acting normally again if you `taskkill /t /im "wd-tabnine.exe" /f`:

![image](https://user-images.githubusercontent.com/165937/110019070-ddc11500-7cdc-11eb-9614-7fca743a1ced.png)

(that terminal window had one command, that whole scrollbar is killed TabNine processes)

**Comment by yonip23** [comment]
Hi @tigerhawkvok,
Thank you for reaching out with this issue!

- Can you please attach here the following: 
  - Tabnine logs - Can be set like so:
  ![image](https://user-images.githubusercontent.com/67855609/110233243-73ea7a80-7f2b-11eb-938f-64a62ce145a0.png)
  - `WD-TabNine`'s logs - located near the log file of Tabnine and is called `wd_log.txt`
  - A screenshot of the `Installation Info` section from Tabnine Hub, like so:
  
![image](https://user-images.githubusercontent.com/67855609/110233536-430b4500-7f2d-11eb-8d10-4f0e5076db91.png)

- When did this problem start to occur? Our processes are using lock files to prevent such problems, so can you think of something that changed on your machine, like permissions, paths etc.?

Kind regards,
Yoni

**Comment by Philofallever** [comment]
it also happened to me too

**Comment by boaz-codota** [comment]
If this happens again to anyone, please shoot us an email at support@tabnine.com with screenshots of the processes and the log file obtained by writing `tabnine::logs` anywhere within a file in the IDE.
