### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Barathkumarravichandran** [codota/tabnine-vscode#362]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bilucodota** [comment]
Hi @Barathkumarravichandran, please send your detailed issue to support@tabnine.com
