### ISSUE TITLE
Apple Silicon M1 support: almost there

### ISSUE THREAD

**Issue by forresto** [codota/tabnine-vscode#363]
- OS version: Mac Big Sur (11.2.2)
- Editor version: 1.54.1
- Programming language: ts
- TabNine extension version: 3.2.8

<img width="292" alt="partial support, click to resolve" src="https://user-images.githubusercontent.com/395307/110236527-f597d380-7f3e-11eb-8849-15a305f6b166.png">

> Messages
> Your current setup doesn't meet Tabnine's local deep completion model requirements, so you can't run Tabnine locally.
> Apple M1 users, you can switch to the VSCode insiders build version to enable Tabnine's local deep completions. See details here.

This used to be true, but since [VSCode 1.54, February 2021](https://code.visualstudio.com/updates/v1_54): "Apple Silicon builds - VS Code is now available in stable for Apple Silicon."

**Comment by bilucodota** [comment]
Hi @forresto, can you confirm you're using the Apple Silicon build of VSCode?

**Comment by forresto** [comment]
You're right, I wasn't on the right build. So the only change request is the message:

> Apple M1 users, you can switch to the VSCode insiders build version to enable Tabnine's local deep completions. See details here.

to

> Apple M1 users, you can switch to the VSCode Apple Silicon build version to enable Tabnine's local deep completions. See details here.  https://code.visualstudio.com/Download

**Comment by bilucodota** [comment]
Will do.

**Comment by forresto** [comment]
Thank you! It's nice to have tabnine back. ❤️
