### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Aditya9056** [codota/tabnine-vscode#374]
- Issue Type: `Bug:- Tabnine causing VS Code startup to slow down by 3-4sec and even unresponsive after startup`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.8`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.2`

## Performance Marks (find at ctrl+shift+p -> Developer: Startup Performance)

| Extension | Eager | Load Code | Call Activate | Finish Activate | Event | By |

| TabNine.tabnine-vscode | true  | 2502 | 942 | 2910 | * | TabNine.tabnine-vscode | TabNine.tabnine-vscode |

**Comment by kknaguib** [comment]
@Aditya9056 I'm having an issue as well, this extension stopped working once I upgraded to v1.54.2 (vs code), and had to uninstall it to bring back some standard code completion. Let me know if you find a fix please

**Comment by kknaguib** [comment]
I had to downgrade vs-code back down to version 1.53.2 for it to work for now.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Aditya9056** [comment]
@kknaguib Great! it worked for you.
