### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by munnahosssain** [codota/tabnine-vscode#381]
Error: 2899286408:error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT:../../third_party/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1040:
2899286408:error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC:../../third_party/boringssl/src/ssl/tls_record.cc:298:

**Comment by dimacodota** [comment]
@munnahosssain  - can you please share your vscode about info?

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
