### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by batdalx** [codota/tabnine-vscode#383]
Error: EBUSY: resource busy or locked, open 'C:\Users\Asep imam\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.exe'

**Comment by batdalx** [comment]
cara mengatasinya?

**Comment by dimacodota** [comment]
@batdalx  - can you try to restart vscode? does it reproduced?

**Comment by boaz-codota** [comment]
We've released a fix. Let us know if this still persists for you (after updating to our vscode plugin's latest version).
