### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by tirlochanarora16** [codota/tabnine-vscode#385]
Error: EBUSY: resource busy or locked, open 'C:\Users\tirlo\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by dimacodota** [comment]
Duplicate of #383

**Comment by dimacodota** [comment]
@tirlochanarora16 - can you try to restart vscode? does it reproduced?
