### ISSUE TITLE
command 'TabNine.statusBar' not found

### ISSUE THREAD

**Issue by Ogjerry** [codota/tabnine-vscode#386]
Error: socket hang up

**Comment by dimacodota** [comment]
@Ogjerry - what OS are you using?  are you behind a proxy?

**Comment by Ogjerry** [comment]
Hello
I am using windows 10 64 Bit
Yes, I am behind a proxy

Sent from Mail for Windows 10

**Comment by boaz-codota** [comment]
Tabnine requires an internet connection to download its engine and models. Please enable such connections for the plugin to work as expected.

Duplicate of #426
