### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by khalidhardiansyah** [codota/tabnine-vscode#390]
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\user only\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\user only\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by dimacodota** [comment]
Duplicate of #383
