### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by koitoror** [codota/tabnine-vscode#395]
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\Adm\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine-deep-local.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\Adm\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine-deep-local.exe'

**Comment by dimacodota** [comment]
Duplicate of #383
