### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by DeLta-shoot** [codota/tabnine-vscode#400]
OS: win32 - ia32
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\iLyes.intel-PC\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\i686-pc-windows-gnu\TabNine.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\iLyes.intel-PC\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\i686-pc-windows-gnu\TabNine.exe'

**Comment by dimacodota** [comment]
Duplicate of #383
