### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by aqibarain** [codota/tabnine-vscode#402]
Error: ENOENT: no such file or directory, open 'c:\Users\aaqib.arain\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'

got above error when tried to update tabnine in visual studio code.

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
