### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by urmil89** [codota/tabnine-vscode#405]
OS: win32 - x64
 Error: Error
Message: getaddrinfo ENOTFOUND update.tabnine.com
Stack: Error: getaddrinfo ENOTFOUND update.tabnine.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
