### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by xchengL** [codota/tabnine-vscode#407]
OS: win32 - x64
 Error: Error
Message: ENOENT: no such file or directory, open 'c:\Users\xcheng\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'
Stack: Error: ENOENT: no such file or directory, open 'c:\Users\xcheng\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'

**Comment by dimacodota** [comment]
Duplicate of #402
