### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by Natanlimap** [codota/tabnine-vscode#421]
OS: linux - x64
 Error: Error
Message: ETXTBSY: text file is busy, open '/home/natan/.vscode/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-unknown-linux-musl/TabNine'
Stack: Error: ETXTBSY: text file is busy, open '/home/natan/.vscode/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-unknown-linux-musl/TabNine'

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
