### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by hind27** [codota/tabnine-vscode#427]
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\omar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\omar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.exe'

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
