### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by sorinstanila** [codota/tabnine-vscode#428]
OS: darwin - x64
 Error: Error
Message: ENOENT: no such file or directory, open '/Users/sorinvstanila/.vscode-insiders/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-apple-darwin/TabNine.zip'
Stack: Error: ENOENT: no such file or directory, open '/Users/sorinvstanila/.vscode-insiders/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-apple-darwin/TabNine.zip'

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
