### ISSUE TITLE
Hi, I am a newbie, I can't use TabNine in my VSCode 

### ISSUE THREAD

**Issue by navixlee** [codota/tabnine-vscode#43]
I install the TabNine extension in my VSCode for python, but it's not work for me, it must be used with any setting, but the completion window still not show out, what can I do??

**Comment by navixlee** [comment]
what's step can I verify the TabNine is worked ??

**Comment by r3nderer** [comment]
Same issue, I think this project is dead.

**Comment by lerayflorian** [comment]
Same same

**Comment by ZacharyWaseda** [comment]
same. it did not show the belief of prediction as the TabNine ads. I am not sure whether it is activated.

**Comment by SwastikBhattacharjee** [comment]
Same thing for me

**Comment by SwastikBhattacharjee** [comment]
Same thing!
There is no auto-completion for Javascript, PHP nor even Python.
Its is giving all the things same as emmet.

**Comment by dimacodota** [comment]
Hi @SwastikBhattacharjee , can you please share a screenshot of your status-bar, a screenshot of the extensions section in vscode where Tabnine is installed, and the vscode console log (Help -> Toggle Developer Tools)?

Thanks
