### ISSUE TITLE
Unable to manage subscription in hub

### ISSUE THREAD

**Issue by alanvardy** [codota/tabnine-vscode#434]
**please complete the following information:**

- OS version: Manjaro i3
- Editor version 1.54.2
- Programming language: Elixir
- TabNine extension version: 3.2.13

**Issue Details:**

Hello,

I am unable to access my subscription settings in Tabnine Hub, I have been clicking everywhere without success.

![2021-03-20_08-54](https://user-images.githubusercontent.com/38899847/111876027-03475300-895a-11eb-8b7a-67511db5a07f.png)

The FAQ says that it should be accessible in the hub:

![2021-03-20_08-56](https://user-images.githubusercontent.com/38899847/111876071-3be72c80-895a-11eb-907f-02a5623286a5.png)

Thank you

**Comment by bilucodota** [comment]
Hi @alanvardy, I've reached you by email. Marking this as close.

**Comment by alanvardy** [comment]
Issue resolved, thank you.

**Comment by ohnu** [comment]
I have the exact same issue... what's the solution / workaround ?

**Comment by alanvardy** [comment]
I had logged into the extension with GitHub auth which was different from the email account I signed up with (I had recently changed the primary email for GitHub). Everything worked great except for being able to view the subscription.

My steps were:
1.) Remove the extension and close VS Code
2.) Remove the TabNine files

```
- $ rm -rf ~/.vscode/extensions/tabnine.tabnine-vscode-*
- $ rm -rf ~/.local/share/TabNine
- $ rm -rf ~/.config/TabNine
```

3.) Start VS Code and install the extension again
4.) Make sure that extension has finished initializing (see the bottom bar, could take a few minutes on a low powered machine)
5.) Log in using the correct email account
6.) Let Tabnine download its local model - note that the model is pretty heavy (can go up to 1GB) so it may take time - you may run watch ls -l ~/.local/share/TabNine/models to follow the download progress
7.) Restart VS Code

At this point VS Code froze on initializing for me. I left it for an hour, and then restarted my editor again and everything has worked well from then on. I can now view my subscription from the menu in the top right corner.

Credit to @bilucodota
