### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by thuanan0105** [codota/tabnine-vscode#435]
OS: linux - x64
 Error: Error
Message: getaddrinfo EAI_AGAIN update.tabnine.com
Stack: Error: getaddrinfo EAI_AGAIN update.tabnine.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

**Comment by boaz-codota** [comment]
We've released a fix.

Duplicate of #383
