### ISSUE TITLE
tabnine and auto import can not both work

### ISSUE THREAD

**Issue by nnsay** [codota/tabnine-vscode#44]
first, thanks for the awesome tool.

the `auto import `feature  for typescript can not work when upgrades vscode to `1.37.0`.
the feature is ok when i disable the tabnite extension, so the tabnine seems to have compatibility issues for the latest vscode.

**Comment by andrewwiik** [comment]
Any update on this from the tabnine team?

**Comment by MikeYermolayev** [comment]
Experiencing the same. Would love to have them both working

**Comment by kmvan** [comment]
Watching the issue

**Comment by Sehsyha** [comment]
Watching the issue too, I do not want to use TabNine if auto import is not working :'(

**Comment by zoff4ick** [comment]
++

**Comment by Gameghostify** [comment]
What would be required to get this working?

**Comment by Jarred-Sumner** [comment]
I disabled TabNine because of this issue :(

**Comment by quezak** [comment]
Testing TabNine since yesterday, it's great so far besides two kinda annoying problems -- #47 and this. It's a shame I need to explicitly ctrl-space  and auto-import each new class name inserted via auto-completion :crying_cat_face:

**Comment by jen6** [comment]
any update here?

**Comment by dimacodota** [comment]
hey @jen6,
We are working on this and this is currently in the testing stage, we appreciate further feedback on this, if you would like to be a beta tester, I can send you vsix that you can test.
thanks

**Comment by jen6** [comment]
> hey @jen6,
> We are working on this and this is currently in the testing stage, we appreciate further feedback on this, if you would like to be a beta tester, I can send you a vsix that you can test.
> thanks

@dimacodota 
Thanks for the replying with new information. I really hope to use it. But actually I'm user of the coc-tabnine. As I know it depends on the vscode extension so I wrote comment in this issue. I hope to use it soon.
thanks

**Comment by dimacodota** [comment]
This issue is in the testing stage, we will appreciate any feedback on this, if anyone wants to be a beta tester please reply and I will send you a vsix with beta version.

**Comment by dimacodota** [comment]
The auto import support was released in the 2.8.4 version. 
To enable this, go to settings and set the `Tabnine: Experimental Auto Imports` to true.

**Comment by ytaran-avenga** [comment]
Still doesn't work at all

**Comment by jsifalda** [comment]
:((

**Comment by giangchau92** [comment]
Still not work for typescript
