### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by elch10** [codota/tabnine-vscode#440]
- OS version: Ubuntu 18.04
- Editor version : 1.54.3
- Programming language: python
- TabNine extension version: 3.2.13

I am connecting to the server via **ssh** without internet access. And so I can't install **tabnine**.

A also tried to download **vsix** and install tabnine from **vsix**. But it is also not working(

Can I somehow install **tabnine** on such server?

**Comment by Eransho** [comment]
Hi,
Please contact us to support@tabnine.com and we will try to find a solution
