### ISSUE TITLE
Tabnine Extension was unable to download its dependencies

### ISSUE THREAD

**Issue by ffiller** [codota/tabnine-vscode#446]
**please complete the following information:**

- OS version: Mac OS Big Sur 11.0.1
- Editor version [e.g. 1.45.0-insider]: VSCode Version: 1.54.3
- Programming language: any
- TabNine extension version: v3.2.15

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

TabNine is unable to start. Error (see screenshot) "Tabnine Extension was unable to download its dependencies. Please check your internet connection. [..]". I don't use a proxy and have made no changes to my setup. Any ideas?

![2021-03-29 at 15 13](https://user-images.githubusercontent.com/1758832/112842804-37c9b600-90a2-11eb-8f0b-586f59aab2df.png)

**Comment by boaz-codota** [comment]
Try again? Maybe you had some temporary network connectivity issues?

**Comment by boaz-codota** [comment]
Or, your firewall (local/network) had blocked the connection

**Comment by ffiller** [comment]
Hm indeed, Little Snitch had blocked it 🤦 Thanks!
