### ISSUE TITLE
Add support proxy

### ISSUE THREAD

**Issue by fakhamatia** [codota/tabnine-vscode#452]
Please add support proxy socks/http/https to Tabnine VSCode

**Comment by boaz-codota** [comment]
Hey @fakhamatia we are supporting proxy, just set the proxy on the OS level and should work out of the box

**Comment by fakhamatia** [comment]
Not OS level, only in VSCode, like [WakaTime](https://wakatime.com/faq#proxies)

**Comment by boaz-codota** [comment]
@fakhamatia I believe we support vscode's native proxy: https://code.visualstudio.com/docs/setup/network

If this method does not work, I'm afraid only os level proxy is supported
