### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by helloLari** [codota/tabnine-vscode#456]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.16`
- OS Version: `Darwin x64 16.7.0`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by avnerbarr** [comment]
what is the issue?

**Comment by helloLari** [comment]
It was appearing incompatible

**Comment by dimacodota** [comment]
Duplicate of #458
