### ISSUE TITLE
bad cursor placement with parentheses

### ISSUE THREAD

**Issue by matejcik** [codota/tabnine-vscode#47]
consider the following code:

```python
hello = "world!"

print(hello)
```

with the native autocompleter, after typing `print(h`, `hello` will be in suggetions. When I hit Tab, I will see the following:
```
p r i n t ( h e l l o )
                     ^
```
caret indicates cursor placement.
At that point, before the closing paren, if I hit `)` on my keyboard, the closing paren is overwritten and I see this:
```
p r i n t ( h e l l o )
                       ^
```

With TabNine's completion, at the same point, if I hit `)`, another closing paren is inserted:

```
p r i n t ( h e l l o ) )
                       ^
```

This makes using completions very painful.

**Comment by dimacodota** [comment]
the fix was released in version 2.2.3
