### ISSUE TITLE
TabNine unable to activate

### ISSUE THREAD

**Issue by Akhil-Raj** [codota/tabnine-vscode#49]
I am unable to activate TabNine in my VSCode. I am attaching the error pdf file for reference
[TabNine2.pdf](https://github.com/zxqfl/tabnine-vscode/files/3562997/TabNine2.pdf)
.
Tell me if you need any further info.
Thanks!

**Comment by zxqfl** [comment]
Are you behind an HTTP proxy?

**Comment by Akhil-Raj** [comment]
> Are you behind an HTTP proxy?

Yes @zxqfl

**Comment by c64bob** [comment]
So, when will activation behind a proxy be supported?

**Comment by amircodota** [comment]
Same as [#181](https://github.com/codota/TabNine/issues/181)
