### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Cessiia** [codota/tabnine-vscode#491]
- Issue Type: `Performance`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.17`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\asus\TabNine.tabnine-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dimacodota** [comment]
Hi @Cessiia , where did you install the extension from? can you please update to the latest version (3.4.3)?

**Comment by Cessiia** [comment]
你说的是什么版本

What version are you talking about？

**Comment by Cessiia** [comment]
> Hi @Cessiia , where did you install the extension from? can you please update to the latest version (3.4.3)?

   I downloaded it from the vscode extension store and I'll try it out。

**Comment by shree675** [comment]
I have recently installed TabNine and faced the same issue today while coding an app. My laptop's cooling fans were going crazy. When I checked the processes in the Windows 10 Task Manager, I found TabNine processes utilizing around 27% of the CPU.
This is a case of very high CPU usage.

Please find the screenshot below:

![Screenshot (255)_LI](https://user-images.githubusercontent.com/58718144/123522041-5b6bbf00-d6d8-11eb-9828-ac3afa4f8f65.jpg)

I have downloaded the extension directly from the VS Code extension marketplace.
