### ISSUE TITLE
Configure delay before suggestions

### ISSUE THREAD

**Issue by liyishuai** [codota/tabnine-vscode#494]
- OS version: macOS Big Sur 11.2.3
- Editor version: 1.55.2
- Programming language: [Ott](https://github.com/ott-lang/ott)
- TabNine extension version: 3.4.3

**Issue Details:**

Current: Suggestions show immediately upon typing, blocking views of lines below.

Hope: Configure delay from typing to popping up suggestions.

Tried: In VSCode `settings.json`, `"editor.quickSuggestionsDelay": 1000` does not help.

**Comment by whoisthisstud** [comment]
As a pro user, I need this delay.  Since the enter key adds the suggested code to the editor, having no delay means that when I line break twice, code that I don't need is suggested and added in the matter of two quick enter key presses.  If there is no way to delay, then this becomes more of a liability versus an asset.

**Comment by marcelo-gomj** [comment]
### edit the tabnine settings file in json, which is in:
MacOS | /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json

Linux | /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.jsonor~/.config/TabNine/tabnine_config.json

Windows | C:\Users\{UserName}\AppData\Roaming\TabNine\tabnine_config.json

```json
  "rate_limit_interval_seconds": 1, // add in seconds for delay maybe this will work
  "rate_limit_amount": null,
  "generation": 60,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": 1, // add in seconds for delay maybe this will work
```
**it worked for me**

**Comment by marcelo-gomj** [comment]
### edit the tabnine settings file in json, which is in:
MacOS | /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json

Linux | /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.jsonor~/.config/TabNine/tabnine_config.json

Windows | C:\Users\{UserName}\AppData\Roaming\TabNine\tabnine_config.json

```json
  "binary_update_interval_seconds": 2,  // add in seconds for delay maybe this will work
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": 2,  // add in seconds for delay maybe this will work
  "rate_limit_amount": null,
  "generation": 30,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": 2,  // add in seconds for delay maybe this will work
```
**it worked for me**
