### ISSUE TITLE
TabNine commands doesn't work

### ISSUE THREAD

**Issue by Sigiller** [codota/tabnine-vscode#50]
After extension installation (and vscode reloading), when I try to open config by TabNine::config  nothing happens. 

win10, vs code v. 1.37.1

**Comment by gielfeldt** [comment]
Same here.
MacOS Mojave.
VSCode 1.38.1
TabNine: 2.1.11

**Comment by wannado** [comment]
same here 
![image](https://user-images.githubusercontent.com/1073904/66357390-fa570180-e9b1-11e9-85ad-41b117558f6e.png)

**Comment by lerayflorian** [comment]
Same here on Code 1.39

![image](https://user-images.githubusercontent.com/15338429/67750969-83e97480-fa30-11e9-92ff-d592c52f811e.png)

**Comment by smxyzb** [comment]
me too

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by SimonBo** [comment]
Me too, TabNine v 2.2.3

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-38-generic snap

**Comment by drorweiss** [comment]
Hi all. Seems that the config does open if you **manually type `TabNine::config`** rather than selecting it from the autocomplete box, ironic as it may seem - we're working on correcting it.
Please let me know if it works for you this way. Thanks

**Comment by SimonBo** [comment]
@drorweiss sitll does not work for me

**Comment by drorweiss** [comment]
@SimonBo do you get code suggestions from TabNine? It typically gets disabled on update and you need to reload vscode. Can you check the vscode extensions page to make sure it's active and doesn't need reload?

**Comment by SimonBo** [comment]
@drorweiss I get code suggestions but fewer than before upgrading to the newest version. Actually, it's really iritating now because the suggestions before the update were so good that I felt like I didn't have to write any code:) Now it's not only fewer suggestions but also the suggestions don't appear if I don't type consequtive letters of the word I want (e.x. I have a module called 'UserSitePhoto', before I would type 'USP' and the suggestions would include the 'UserSitePhoto' but now I get no suggestions at all, I have to type 'UserS' to get that suggestion). I tried reinstalling TabNine but I still get few suggestions and TabNine commands dont work. I will try to install an older version and see if it works.

**Comment by SimonBo** [comment]
@drorweiss I downgraded to 2.2.2 and didnt see any improvements. I tried TabNine::config and nothing happened BUT I then tried TabNine::config_dir and it showed me the dir in a suggestion window. I then type TabNine::config again and it opened the browser with config. The suggestions still dont work as before thou.

**Comment by birdmanmandbir** [comment]
> Hi all. Seems that the config does open if you **manually type `TabNine::config`** rather than selecting it from the autocomplete box, ironic as it may seem. We're working on correcting it.
> Please let me know if it works for you this way. Thanks

Same to `TabNine::sem`. It's weird.

**Comment by markvandieren** [comment]
Manually typing TabNine::config did not work for me, but **reinstalling VS Code** did the trick. (Just reinstalling TabNine or clearing the VS Code cache folders did not help).

I uninstalled TabNine. Re-ran the VS Code installer **without** uninstalling and installed on top of the existing installation, then reinstalled TabNine. All VS Code settings and extensions were preserved. 

Win10, VS Code 1.43.2, TabNine 2.5.2

**Comment by DimitriGilbert** [comment]
Same here, I had to remove the extension from vscode and clear tabnine folder (on Ubuntu derivative it should be ~/.local/share/TabNine). 
If I recall correctly, things stop working after a vscode update, no more completion, but tabnine seemed to be running (there was a process consuming a sizeable amount of RAM, as normal)
mint 20
vscode 1.53
plugin version 3.2.6
engine version 3.3.54-39

**Comment by dimacodota** [comment]
@DimitriGilbert - can you please share your vscode extension log (Help -> Toggle developer tools) ?

**Comment by DimitriGilbert** [comment]
@dimacodota "unfortunatly" things works since I deleted the extention and tabnine folder before reinstalling the extension so I'm afraid I can't be of much help.
I'll try to remember if things stop working again (but I just updated vscode and no problems so far)
