### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by HackerGal** [codota/tabnine-vscode#508]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

gz#986

**Comment by dimacodota** [comment]
Hey @HackerGal, what is the issue?

**Comment by HackerGal** [comment]
Hey @dimacodota, the above extension was not able to run after installation and blocking my other extensions from running. I've since uninstalled the extension.

**Comment by maya-tabnine** [comment]
Do you want to try and check what's causing this? If yes you can reinstall and send us your VSCode devtool output.
Click Help->Toggle Developer Tools->Console
