### ISSUE TITLE
Tabnine Hub Not loading

### ISSUE THREAD

**Issue by snyntakk404** [codota/tabnine-vscode#512]
**please complete the following information:**

- OS version: Linux Crostini
- Editor version: 1.56.2
- Programming language: All of them
- TabNine extension version: 3.4.4

**Issue Details:**
The Tabnine hub won't load. It's just blank.
![Screenshot 2021-05-25 7 32 59 PM](https://user-images.githubusercontent.com/84817918/119581170-14647400-bd90-11eb-87e9-9c34720483ea.png)

gz#1091

**Comment by Tabnineteam** [comment]
What is your IDE? Can you please share the binary log and config file?

tabnine_config.json should be located at $XDG_CONFIG_HOME/TabNine or $HOME/.config/TabNine
<br><p><em><small>°°°</small></em></p>

**Comment by eyalSemel** [comment]
I have the same issue:
OS version: ubuntu 20 running on wsl2
Editor version: 1.60.2
Programming language: All of them
TabNine extension version: 3.5.31

tabnine_config.json:
`{
    "version": "3.5.31",
    "hide_promotional_message": false,
    "beta_enabled": "No",
    "ignore_all_lsp": false,
    "creation_time": "2021-08-01T08:21:49.590612500Z",
    "guuid": "f7b2f7fdf89da5579164559c20a0ffb710f4d31b2ca96ada5b5d463f4ca943b2",
    "semantic_status": {},
    "enable_telemetry": true,
    "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
    "hosted_deep_completions_enabled": "Disabled",
    "tabnine_cloud_host": null,
    "tabnine_cloud_certificate_domain": null,
    "tabnine_cloud_port": null,
    "cloud_whitelist": [],
    "num_of_suggestions": 5,
    "line_suggestions": null,
    "multiline_suggestions": null,
    "omit_prefix_suggestions": null,
    "api_key": null,
    "api_base_url": null,
    "binary_update_interval_seconds": null,
    "local_enabled": "Unset",
    "disable_local_when_using_battery": false,
    "hide_deep_information_message": false,
    "enable_power_saving_mode": false,
    "rate_limit_interval_seconds": null,
    "rate_limit_amount": null,
    "generation": 43,
    "local_model_size": null,
    "model_hash_override": null,
    "local_indexing": null,
    "heartbeat_interval_seconds": null,
    "last_service_level": null,
    "override_beams": null,
    "override_context_length": null,
    "onboarding": null,
    "has_git_repos": true,
    "gusr": {
        "dgc": "f7b2f7fdf89da5579164559c20a0ffb710f4d31b2ca96ada5b5d463f4ca943b2"
    },
    "exclude_file_masks": null,
    "inline_suggestions_mode": null
}`
