### ISSUE TITLE
Tabnine doesn't work on VSCode

### ISSUE THREAD

**Issue by Egor-Kozlov** [codota/tabnine-vscode#514]
- OS version: Win 8.1 x64 6.3.9600
- Editor version [e.g. 1.45.0-insider]:
- Programming language: js
- TabNine extension version: 3.4.4
 
Hi!
After installing this extension, it does not work. 
I reloaded vscode, reinstalled the extension, but it does not show any signs of life.
After trying to find out the version or config, nothing happens https://prnt.sc/13i6gyc , and the tabnine window is empty https://prnt.sc/13i6e6z  .

Thanks!

gz#1162

**Comment by maya-tabnine** [comment]
Can you please share the binary log and config file?
tabnine_config.json should be located at C:\Users\username\AppData\Roaming\

**Comment by Egor-Kozlov** [comment]
tabnine_config.json is here :  https://drive.google.com/file/d/1aLCpijrHl-ORvWV4FU-J5c1UuAeO_i0w/view?usp=sharing

**Comment by sayajin101** [comment]
I have the exact same issue, using windows 10.

Locally it works 100%, but using the vscode ssh extension for remote dev it gives me the error "Partial support, click to resolve".
If I click on that the tabnine window is also empty.

The problem is I do all of my dev remotely via the SSH extension.

Is this a known issue and can it be resolved?

**Comment by maya-tabnine** [comment]
Can you also send Tabnine's log? in VSCode please open the extension settings
and enter a path on ‘Tabnine: Log File Path’
Then restart the IDE and wait for the problem to happen.

**Comment by snyntakk404** [comment]
> I have the exact same issue, using windows 10.
> 
> Locally it works 100%, but using the vscode ssh extension for remote dev it gives me the error "Partial support, click to resolve".
> If I click on that the tabnine window is also empty.
> 
> The problem is I do all of my dev remotely via the SSH extension.
> 
> Is this a known issue and can it be resolved?

that happened to me as well

**Comment by maya-tabnine** [comment]
@sayajin101 @snyntakk404 this is known. Check this old issue https://github.com/codota/TabNine/issues/305
or follow our instructions on our faq to port forwarding https://www.tabnine.com/faq#could_not_start_browser :
Use port forwarding to view the config panel from your local machine. If your remote machine's address is janedoe@123.45.67.89, and Tabnine is listening on port 5555, 
the following command from your local machine will do this: ssh -L 5555:127.0.0.1:5555 janedoe@123.45.67.89

**Comment by sayajin101** [comment]
@maya-tabnine Thank you soo much, that did the trick!

Maybe you guys should have this as a popup when you hover over the "Partial support, click to resolve" error that it gives you a link on how to setup this port forward?

**Comment by Hinlavic** [comment]
> I have the exact same issue, using windows 10.
> 
> Locally it works 100%, but using the vscode ssh extension for remote dev it gives me the error "Partial support, click to resolve". If I click on that the tabnine window is also empty.
> 
> The problem is I do all of my dev remotely via the SSH extension.
> 
> Is this a known issue and can it be resolved?

Same problem.
It crashes my SSH function of my remote server entirely, not only the REMOTE-SSH plugin, without any notifications when I simply install it on my server through VSCODE plugin manager.
It takes much time to find this.

**Comment by mzvast** [comment]
Same problem on macOS

**Comment by javascapetech** [comment]
i have the same issue tried everything but dont work
