### ISSUE TITLE
Support tag replace in entire directory 

### ISSUE THREAD

**Issue by TUSHAR4541** [codota/tabnine-vscode#519]
**Please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina] - Win 10
- Editor version [e.g. 1.45.0-insider]: - VS Code 1.56.2
- Programming language: [e.g. js, ts, c++] - HTML
- TabNine extension version: 3.4.4

**Suggestion Details:**

Provide support to search and replace HTML tags in all files of a directive with auto-complete closing tags

gz#1331

**Comment by maya-tabnine** [comment]
That sounds like a cool idea! It is not on our roadmap, but you can definitely develop a VSCode extension on your own for that

**Comment by maya-tabnine** [comment]
Thanks for the suggestion, for any other issues you have you are welcome to reach us at suppport@tabnine.com
