### ISSUE TITLE
Conflicts with vscode's own TS/JS intellisense

### ISSUE THREAD

**Issue by linonetwo** [codota/tabnine-vscode#525]
Same as https://github.com/codota/tabnine-vscode/issues/20

latest version.

**Comment by boaz-codota** [comment]
Well, this is actually a vscode behavior that we have zero influence on.

As you can see in https://github.com/codota/tabnine-vscode/blob/master/src/extension.ts#L91 the API that vscode exposes only allows us to supply suggestions upon predefined characters (which are all characters for Tabnine), not to control what other suggestions are allowed or not.

I think you should open a similar issue in vscode's repo and explain to them the behavior that is interfering with your (and others) workflow.

If there is anything else I can assist with let me know.

**Comment by linonetwo** [comment]
Understood, I see you just register your result, but somehow other extensions' registered results don't pop up. I've found a similar issue in the VSCode repo, I will link this issue there.

**Comment by boaz-codota** [comment]
Thank you @linonetwo , I wish we had more to do here, but this is truly something vscode needs to fix on their side.
