### ISSUE TITLE
Auto Import doesn't work when vs code language is not English

### ISSUE THREAD

**Issue by Jonir227** [codota/tabnine-vscode#528]
**please complete the following information:**

- OS version: MacOS 15
- Editor version [e.g. 1.45.0-insider]: 
- Programming language: ts
- TabNine extension version: 3.4.5

currently, tabnine is checking autoimport by name.

```ts
const importStatement = /Import ([\S]*) from module [\S]*/;
const existingImportStatement = /Add ([\S]*) to existing import declaration from [\S]*/;
const importDefaultStatement = /Import default ([\S]*) from module [\S]*/;
const existingDefaultImportStatement = /Add default import ([\S]*) to existing import declaration from [\S]*/;
const importStatements = [
  importStatement,
  existingImportStatement,
  importDefaultStatement,
  existingDefaultImportStatement,
];
```

but this way can't support multi language. I'm using Vs code in Korean. so this feature is not working.

![image](https://user-images.githubusercontent.com/21289079/121833957-81708700-cd08-11eb-8ef0-7338f77b292f.png)

I think this can be solved by using `fixName` field. It tells code action command is about import.

btw, I love this extension. I hope this problem be fixed soon !

gz#1710

**Comment by nimrod-codota** [comment]
Hey @Jonir227, thanks for using Tabnine and for bringing this to our awareness. We sweep through issues opened here at intermissions. I hope this issue gets some traction so we can prioritise it. Will update here once there's any change of status. Thanks again!
