### ISSUE TITLE
How to use Student Plan?

### ISSUE THREAD

**Issue by SCLeoX** [codota/tabnine-vscode#532]
From the README:

> FREE Tabnine Student Plan We know that tuition, books, rent, and food can get crazy expensive, that’s why Tabnine helps support the community and the dev superstars of tomorrow with a 100% free Tabnine Student license with all our Pro perks renewable for as long as you are a student.

However, I could not find an option to enroll the student plan.

gz#1773

**Comment by maya-tabnine** [comment]
If you are a student you can enroll in our Student Plan! 
Contact our support at support@tabnine.com using your educational email.

**Comment by maya-tabnine** [comment]
You can join Tabnine Student Plan from our website at https://www.tabnine.com/students !

**Comment by SHAHNUR00** [comment]
Is the student offer available?

**Comment by isyuricunha** [comment]
> Is the student offer available?

I don't think so. 

I had the student plan since 2020/2021, but it was automatically canceled. 

I believe they removed the student plan.
