### ISSUE TITLE
Load extension only when necessary

### ISSUE THREAD

**Issue by aravindvnair99** [codota/tabnine-vscode#533]
https://github.com/codota/tabnine-vscode/blob/97f83b2ffc7a241653ef008394d5c50ac57d7f30/package.json#L90-L92

Why not load the extension only after start up instead of on start up of VS Code?

gz#1838

**Comment by maya-tabnine** [comment]
Tabnine processes start running when opening VSCode (or any ide you installed Tabnine on), as you said.
There is no need for the engine to be on when you are not on your IDE writing code.

**Comment by aravindvnair99** [comment]
@maya-tabnine can you reopen this as it's still pending?

**Comment by aravindvnair99** [comment]
Thanks @dimacodota!

**Comment by aravindvnair99** [comment]
#534 will fix this issue.

**Comment by aravindvnair99** [comment]
@dimacodota any updates?

**Comment by aravindvnair99** [comment]
@dimacodota any updates on this? It's been two years.

**Comment by mikekosulin** [comment]
Does anyone use this extension in [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers)?

<img width="772" alt="image" src="https://github.com/codota/tabnine-vscode/assets/6089872/04bef5f4-b58f-4119-bffa-7bc20ba43315">
devcontainer | localmachine

**Comment by mikekosulin** [comment]
Still can't use Tabnine inside devcontainers :(

Version: 3.6.74
