### ISSUE TITLE
Extension name is too big

### ISSUE THREAD

**Issue by aravindvnair99** [codota/tabnine-vscode#535]
The extension name is too big which results in cases such as:

- Unable to see activation time in Visual Studio Code - Running Extensions:
![image](https://user-images.githubusercontent.com/22199259/122211744-b1648980-cec4-11eb-988e-a9b3b3d63d1e.png)

- Name not completely visible in Visual Studio Code - Extension panel
![image](https://user-images.githubusercontent.com/22199259/122211958-ebce2680-cec4-11eb-8a6e-69f8fe3c7859.png)

Why not keep a simple and smaller name such as `Tabnine - AI Code Completion` as mentioned in the [README](https://github.com/codota/tabnine-vscode/blob/97f83b2ffc7a241653ef008394d5c50ac57d7f30/README.md#L15) for example?

https://github.com/codota/tabnine-vscode/blob/97f83b2ffc7a241653ef008394d5c50ac57d7f30/README.md#L15

gz#1839

**Comment by maya-tabnine** [comment]
I understand what you are saying and will pass on your feedback. Thanks :)

**Comment by Alex-CD** [comment]
I know this has been covered in several other issues, but this also means that the welcome screen's tab is wider than my entire monitor 😄

**Comment by storm1er** [comment]
_Right clicks on vscode's bottom bar_

👀 
![image](https://user-images.githubusercontent.com/9821946/129339244-7524c845-a893-435a-b902-52d8a793e01e.png)

![god please no](https://i.kym-cdn.com/photos/images/newsfeed/000/865/302/3d5.gif)

**Comment by mukundshah** [comment]
I just installed Tabnine yesterday, after thinking for nearly half a year (as I had just started my programming journey, so I was hesitant about relying on AI). I'm glad I did installed it. but I'm going to uninstall this soon, if the title doesn't gets fixed. It's unnecessarily long.

**Comment by aravindvnair99** [comment]
> I understand what you are saying and will pass on your feedback. Thanks :)

Hey @maya-tabnine!

Any updates on this?

**Comment by dimacodota** [comment]
fixed in 3.4.32

**Comment by mukundshah** [comment]
@dimacodota Thank You!
