### ISSUE TITLE
Extension issue, unresponsive

### ISSUE THREAD

**Issue by SriVenkatesh-p** [codota/tabnine-vscode#556]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.12`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#2884

**Comment by maya-tabnine** [comment]
Can you share your Tabnine's logs?
Open the extension settings and enter a path on ‘Tabnine: Log File Path’
Then restart IDE and wait for the problem to happen.

And your devtool output?
Click Help->Toggle Developer Tools->Console
