### ISSUE TITLE
globalStorage\tabnine.tabnine-vscode\binaries\3.5.15\x86_64-pc-windows-gnu\TabNine.exe timeout

### ISSUE THREAD

**Issue by Intrflex** [codota/tabnine-vscode#562]
please complete the following information:

OS version: Win 10
Editor: vscode
Editor version: 1.58.0
Programming language: JS
TabNine extension version: 3.4.12
Engine version (could be located within Tabnine Hub):
Issue Details:

Tabnine does not work at all for me I get repeated following errors
![image](https://user-images.githubusercontent.com/50700107/125078613-8da6f480-e0ba-11eb-85da-bf7f57855f44.png)
ive uninstalled VScode, ive removed tabnine, ive downgraded tabnine etc when clicking the tabnine button at the the bottom nothing happens either im at a lost cause on how to solve this, the binaries exist in the global storage also, when i click them nothing shows

gz#3384

**Comment by dimacodota** [comment]
Hi @Intrflex, please check if [that solution](https://github.com/codota/tabnine-vscode/issues/426#issuecomment-814428805) solves the issue.

**Comment by yonip23** [comment]
Closing...
