### ISSUE TITLE
Conflicts with phpactor's variable completion

### ISSUE THREAD

**Issue by BladeMF** [codota/tabnine-vscode#571]
**Please complete the following information:**

- OS version:  Windows 10
- Editor version 1.58.1
- Programming language: PHP
- TabNine extension version: v3.4.14

**Issue Details:**
The variable completion entries from my existing PHP extension (`phpactor`) are not displayed at any time when typing or hitting Ctrl+Space. I have verified that the language server is returning a proper response with completion entries.

gz#3725

**Comment by yonip23** [comment]
Hi @BladeMF 
Thanks pointing it out!
We will look into this, so follow this ticket to stay tuned.
Hoping to update you soon enough.

Cheers

**Comment by BladeMF** [comment]
Thanks guys!

Vladi.
________________________________
