### ISSUE TITLE
Links within TabNine hub are not working

### ISSUE THREAD

**Issue by BladeMF** [codota/tabnine-vscode#572]
**please complete the following information:**

- OS version: Windows 10
- Editor version 1.58.1
- Programming language: PHP
- TabNine extension version: 3.4.14 (on WSL)

**Issue Details:**

Several links within TabNine hub are not working (when I click them nothing visible happens):
* Sign in
* Sign up
* Report issues on Github
* Join our Slack community
* Frequently Asked Questions
* Join the Tabnine Discord server

gz#3729

**Comment by maya-tabnine** [comment]
I see you wrote you work on VSCode remote WSL,
we have an issue with the buttons and links on the hub remotely, so that may be the case in your issue.

**Comment by BladeMF** [comment]
Yes, probably. Someway I can help? I enjoy your product.

**Comment by bilucodota** [comment]
HI @BladeMF, we use `$BROWSER` to open the browser, check out one of the answers [here](https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux)

**Comment by BladeMF** [comment]
Yes, the $BROWSER did the trick, thanks. 

I would suggest that if you detected I was running on WSL and then suggested an official walkthrough of how to do this (there _are_ pitfalls) would be nice.
