### ISSUE TITLE
irresponsive

### ISSUE THREAD

**Issue by Vincentonye** [codota/tabnine-vscode#579]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.17`
- OS Version: `Windows_NT x64 10.0.14393`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#3988

**Comment by maya-tabnine** [comment]
Hi can you provide more details?
Was the installation successful? Is the plugin irresponsive or your VSCode is irresponsive?
Can you reach Tabnine Hub by typing "tabnine::config"?
