### ISSUE TITLE
broken on gitpods

### ISSUE THREAD

**Issue by gengjiawen** [codota/tabnine-vscode#586]
Chrome devtools
![image](https://user-images.githubusercontent.com/3759816/127427324-883e6a30-869c-4b22-8cf3-f77fb4002c74.png)

gz#4419

**Comment by bilucodota** [comment]
Hi @gengjiawen 
Thanks for reaching out
Can you please share some more details?

Are you not able to use Tabnine at all? Did it use to work before or is it the first time you're using Tabnine?

**Comment by gengjiawen** [comment]
Used to work. Not sure why this occured.

**Comment by dimacodota** [comment]
@gengjiawen - can you please update to the latest version and try again ?

**Comment by gengjiawen** [comment]
> @gengjiawen - can you please update to the latest version and try again ?

Fixed. Thanks. Please consider test it on gitpods before release.
