### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by RizalAnditama** [codota/tabnine-vscode#601]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.21`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#4926

**Comment by maya-tabnine** [comment]
Hi, what is the bug you experience?
