### ISSUE TITLE
Tabnine Display Name Length

### ISSUE THREAD

**Issue by SolarTheory** [codota/tabnine-vscode#607]
- OS version: [Win 10]
- Editor version [e.g. 1.60-insider]:
- Programming language: [N/A]
- TabNine extension version: 3.4.22

Could you shorten the Tabnine Display Name? It forces the Status Bar menu to be the width of the screen.  A temporary fix is to edit the package.json, but having to do that every time there is a new version is not ideal.

Thanks.

![Tabnine-VSCode-LongDisplayName-StatusBarIssue](https://user-images.githubusercontent.com/15674476/129526297-e3b58475-e540-4fb8-ad71-e17c690aaacd.png)

gz#5190

**Comment by maya-tabnine** [comment]
Thank you for the feedback, I will pass it on.
The reason we use longer names is to make it easier for people to find Tabnine in the search results

**Comment by manojbaishya** [comment]
Hi @maya-tabnine, I had the posted the same problem at https://github.com/codota/TabNine/issues/410, but there was no response. Between 23-June-2021 (the time of making that issue) and now, I can definitely see a change in the string, but why shortening it has not been taken into consideration? 

Please help me understand, if extension search is tightly linked with the status bar name string.
If yes, why isn't there a tag mechanism in search that brings Tabnine up on entering, for example, "Autocomplete" which will decouple the two. 

<img src="https://user-images.githubusercontent.com/28330014/130342859-80f63dd0-01ca-4e07-b23e-7bc43413c9b5.png" alt="autocomplete-tag" width="600"/>

And if not, why do we have a long name?

My argument is that people who have already installed Tabnine know already that it is for autocomplete functionality and therefore do not need a big reminder in the face.

**Comment by manojbaishya** [comment]
@sarrietav-dev 

1. Navigate to the ```extensions``` folder. Refer to [this link](https://code.visualstudio.com/docs/editor/extension-marketplace#_where-are-extensions-installed) if using standard installation, otherwise for portable it will be within the ```data``` folder.
2. Open ```tabnine.tabnine-vscode-<version>``` and then ```package.json```.
3. Truncate the value for the ```"displayName"``` attribute.
4. Restart VSCode.

**Comment by SolarTheory** [comment]
Fixing it is easy, yes. I think most are aware of how that is done. That's not the issue. 

Everytime there's an extention update, which is frequently with Tabnine, it returns. 

It's just a minor annoyance that could easily be rectified on their end. It's perplexing why they don't want to fix it.

**Comment by dimacodota** [comment]
fixed in 3.4.32
