### ISSUE TITLE
Support for jupyter notebooks on VSCode

### ISSUE THREAD

**Issue by jaimeperezsanchez** [codota/tabnine-vscode#61]
Hi, since native support for jupyter notebooks has recently been announced on VSCode:
Is there any way for Tabnine to work in these files?
Is their support planned?

Thank you!

**Comment by maRT-sk** [comment]
Hi, 
tabnine does not work for jupyter notebooks on VSCode?
Have you guys find a workaround?

**Comment by talmago** [comment]
TabNine will not be able to work with the jupyter extension [custom editor](https://github.com/microsoft/vscode-jupyter/blob/55ea387553812a3ca7c7b15bd1984a485fe37754/package.json#L1349).

But good news - it does seem to work great with the native editor API which is currently rolling out. 

You can use it by installing the [Insiders Build](https://code.visualstudio.com/insiders/).

Another way is to opt in to the "NativeNotebookEditor" experiment as mentioned [here](https://github.com/microsoft/vscode-jupyter/wiki/Experiments).

**Comment by anishazaveri** [comment]
Hi, is there a resolution for this? Copilot works in .ipynb notebooks in VSCode. I was considering switching to tabnine but the lack of ipynb support may be a dealbreaker
