### ISSUE TITLE
conflict with Ement

### ISSUE THREAD

**Issue by hec9527** [codota/tabnine-vscode#62]
- Vs code 1.38.1
- tabnine 2.1.11

This plugin seem to be useful for all developmenter, but no web,  some convenientc shortcut in Ement be covered by tabnine, it's not ok, we need ement more than tabnine if this problem don't fixxxxxxxxx
- eg, we need an element `ol` and 10 `li` in it
    - in ement  `ol>li*10`+`tab`  
    - build it, but when tabnine exist, it just a tab

**Comment by robclancy** [comment]
Yep one of the reasons I have to disable this.

**Comment by dimacodota** [comment]
hey @hec9527 - what OS are you using ?
can you please try to reproduce it ?

please see the current emmet + tabnine state: 
Mac OS (Catalina)
vscode 1.42
tabnine: 2.2.3

![emet-html](https://user-images.githubusercontent.com/60742964/76683408-80840d80-660c-11ea-891c-5f0ce472b82b.gif)

**Comment by hec9527** [comment]
win10, this issue is so long time ago, I'm not sure the detail of version,  if this issue fixed at the latest version of Vscode at Windows plateform and osX . you can close this issue, fewer and fewer will be effected. no necessary find and fix this history problem,let it go
