### ISSUE TITLE
add option to stop using "enter" key as autocomplete, and stop "spellcheck, spelling predict"

### ISSUE THREAD

**Issue by mister-hai** [codota/tabnine-vscode#631]
ACCIDENTALLY HIT ENTER, sorry lol

Can you stop the program from using the Enter key as an autocomplete and leave that to the TAB key,

And can you adjust things so it doesnt try to suggest random-ish things (even things from other projects in other languages? cmon now, I only use "herp" and "derp" in go as "return,error") when I type a single # or hit the spacebar? Literally everytime I hit the spacebar it suggest something. Pretty annoying when you are just trying to type. It should stay out of the "non-code" portions and stick to being an AI code-completion/assist thing

ITS REALLY ANNOYING when I am trying to comment out things and type docs when I accidentally hit that pesky "add a newline" key after hitting literally any other key.

**Comment by mister-hai** [comment]
ACCIDENTALLY HIT ENTER, sorry lol

Can you stop the program from using the Enter key as an autocomplete and leave that to the TAB key,

And can you adjust things so it doesnt try to suggest random-ish things (even things from other projects in other languages? cmon now, I only use "herp" and "derp" in go as "return,error") when I type a single # or hit the spacebar? Literally everytime I hit the spacebar it suggest something. Pretty annoying when you are just trying to type. It should stay out of the "non-code" portions and stick to being an AI code-completion/assist thing

ITS REALLY ANNOYING when I am trying to comment out things and type docs when I accidentally hit that pesky "add a newline" key after hitting literally any other key.

**Comment by maya-tabnine** [comment]
Hi, I found this that explains how to change these settings on VSCode. https://www.reddit.com/r/vscode/comments/ayvd0p/how_to_stop_autocomplete_with_enter/ 
Check this: https://i.imgur.com/EAkDgno.png

**Comment by VaarunSinha** [comment]
This worked for me, thank you.

**Comment by deltemp** [comment]
Like a charm! Thanks!
