### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by stoner1234** [codota/tabnine-vscode#632]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.26`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.60.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#6404

**Comment by maya-tabnine** [comment]
Hi! What is the bug?
