### ISSUE TITLE
hub not loading

### ISSUE THREAD

**Issue by eyalSemel** [codota/tabnine-vscode#643]
details:
OS version: ubuntu 20 running on wsl2
Editor version: 1.60.2
Programming language: All of them
TabNine extension version: 3.5.31

issue: 
hub doesn't load, all I see is this:
![image](https://user-images.githubusercontent.com/55841340/135162959-eded7e28-32d8-4ed1-83fa-4539f4c11929.png)

contents of tabnine_config.json:
`{
    "version": "3.5.31",
    "hide_promotional_message": false,
    "beta_enabled": "No",
    "ignore_all_lsp": false,
    "creation_time": "2021-08-01T08:21:49.590612500Z",
    "guuid": "f7b2f7fdf89da5579164559c20a0ffb710f4d31b2ca96ada5b5d463f4ca943b2",
    "semantic_status": {},
    "enable_telemetry": true,
    "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
    "hosted_deep_completions_enabled": "Disabled",
    "tabnine_cloud_host": null,
    "tabnine_cloud_certificate_domain": null,
    "tabnine_cloud_port": null,
    "cloud_whitelist": [],
    "num_of_suggestions": 5,
    "line_suggestions": null,
    "multiline_suggestions": null,
    "omit_prefix_suggestions": null,
    "api_key": null,
    "api_base_url": null,
    "binary_update_interval_seconds": null,
    "local_enabled": "Unset",
    "disable_local_when_using_battery": false,
    "hide_deep_information_message": false,
    "enable_power_saving_mode": false,
    "rate_limit_interval_seconds": null,
    "rate_limit_amount": null,
    "generation": 43,
    "local_model_size": null,
    "model_hash_override": null,
    "local_indexing": null,
    "heartbeat_interval_seconds": null,
    "last_service_level": null,
    "override_beams": null,
    "override_context_length": null,
    "onboarding": null,
    "has_git_repos": true,
    "gusr": {
        "dgc": "f7b2f7fdf89da5579164559c20a0ffb710f4d31b2ca96ada5b5d463f4ca943b2"
    },
    "exclude_file_masks": null,
    "inline_suggestions_mode": null
}`

gz#7023

**Comment by yonip23** [comment]
Hi @eyalSemel 
Can you try it again and send us the Tabnine logs?
To set the log file in VSCode:
- Open settings
- Search for this entry: `Tabnine: Log File Path` and set it to the path you want (including the file name)

Thanks in advance

**Comment by eyalSemel** [comment]
it created 2 files, here are there contents:

`INFO [auth::token] [2021-09-29T10:37:01.508949100+03:00][INFO][6647 main][auth::token][Some("shared/auth/src/token/mod.rs")][Some(41)] token path: /home/semel/.config/TabNine/tabnine.token
WARN [auth::user] [2021-09-29T10:37:01.521897700+03:00][WARN][6647 main][auth::user][Some("shared/auth/src/user/mod.rs")][Some(252)] No user token available: No such file or directory (os error 2)
INFO [TabNine::main_utils] [2021-09-29T10:37:01.522080800+03:00][INFO][6647 main][TabNine::main_utils][Some("tabnine/frontend/src/main_utils.rs")][Some(182)] /home/semel/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/home/semel/.vscode-server/tabnine_log/tabnine_log.json-6369 --client-metadata clientVersion=1.60.2 pluginVersion=3.4.29 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Community Material Theme Ocean High Contrast vscode-theme-kind=Dark vscode-machine-id=c4b598f7887b81a43e5b8633ca6064b3afc59a5db7cc255a1b46f0b56fcfe4e4 vscode-is-new-app-install=false vscode-session-id=f15e0f94-401c-4c86-9cfe-f7a7bc91c4911632901016649 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
INFO [watchdog_api::wd_client] [2021-09-29T10:37:01.552609700+03:00][INFO][6647 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(74)] Initializing watchdog client...
INFO [TabNine::bootstrap_support] [2021-09-29T10:37:01.574364900+03:00][INFO][6647 bootstrapper_main_run_loop][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(196)] trying to start tabnine version Some("3.6.8")
INFO [TabNine::bootstrap_support] [2021-09-29T10:37:01.574590600+03:00][INFO][6647 bootstrapper_main_run_loop][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(287)] spawning tabnine with args ["/home/semel/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine", "--client=vscode", "--no-lsp=true", "--log-file-path=/home/semel/.vscode-server/tabnine_log/tabnine_log.json-6369", "--client-metadata", "clientVersion=1.60.2", "pluginVersion=3.4.29", "t9-vscode-AutoImportEnabled=true", "t9-vscode-TSAutoImportEnabled=true", "t9-vscode-JSAutoImportEnabled=true", "vscode-telemetry-enabled=true", "vscode-remote=true", "vscode-remote-name=wsl", "vscode-extension-kind=2", "vscode-theme-name=Community Material Theme Ocean High Contrast", "vscode-theme-kind=Dark", "vscode-machine-id=c4b598f7887b81a43e5b8633ca6064b3afc59a5db7cc255a1b46f0b56fcfe4e4", "vscode-is-new-app-install=false", "vscode-session-id=f15e0f94-401c-4c86-9cfe-f7a7bc91c4911632901016649", "vscode-language=en", "vscode-app-name=Visual Studio Code", "vscode-beta-channel-enabled=false", "vscode-status-customization=unknown", "ide-restart-counter=0", "--no_bootstrap"]
INFO [TabNine::bootstrap_support] [2021-09-29T10:37:01.574884400+03:00][INFO][6647 bootstrapper_main_run_loop][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(291)] started tabnine process pid 6685 version Some("3.6.8"), desired version was Some("3.6.8") this version is Some("3.6.8")
INFO [auth::token] [2021-09-29T10:37:01.581142700+03:00][INFO][6685 main][auth::token][Some("shared/auth/src/token/mod.rs")][Some(41)] token path: /home/semel/.config/TabNine/tabnine.token
WARN [auth::user] [2021-09-29T10:37:01.596014600+03:00][WARN][6685 main][auth::user][Some("shared/auth/src/user/mod.rs")][Some(252)] No user token available: No such file or directory (os error 2)
INFO [TabNine::main_utils] [2021-09-29T10:37:01.597120200+03:00][INFO][6685 main][TabNine::main_utils][Some("tabnine/frontend/src/main_utils.rs")][Some(182)] /home/semel/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/home/semel/.vscode-server/tabnine_log/tabnine_log.json-6369 --client-metadata clientVersion=1.60.2 pluginVersion=3.4.29 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Community Material Theme Ocean High Contrast vscode-theme-kind=Dark vscode-machine-id=c4b598f7887b81a43e5b8633ca6064b3afc59a5db7cc255a1b46f0b56fcfe4e4 vscode-is-new-app-install=false vscode-session-id=f15e0f94-401c-4c86-9cfe-f7a7bc91c4911632901016649 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
INFO [watchdog_api::wd_client] [2021-09-29T10:37:01.601664800+03:00][INFO][6685 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(74)] Initializing watchdog client...
INFO [frontend] [2021-09-29T10:37:01.641522500+03:00][INFO][6685 main][frontend][Some("tabnine/frontend/src/lib.rs")][Some(82)] LSP disabled
DEBUG [server::in_app_messaging] [2021-09-29T10:37:01.744069600+03:00][DEBUG][6685 main][server::in_app_messaging][Some("tabnine/server/src/in_app_messaging.rs")][Some(28)] registering in app message analytics handler
INFO [recommend_tabnine_extension] [2021-09-29T10:37:01.790220100+03:00][INFO][6685 main][recommend_tabnine_extension][Some("tabnine/recommend_tabnine_extension/src/lib.rs")][Some(30)] registering recommender
INFO [recommend_tabnine_extension::vscode_recommended_extensions] [2021-09-29T10:37:01.790284100+03:00][INFO][6685 main][recommend_tabnine_extension::vscode_recommended_extensions][Some("tabnine/recommend_tabnine_extension/src/vscode_recommended_extensions.rs")][Some(57)] not activating recommendation engine
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.807266600+03:00][INFO][6685 main][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(92)] No private model found
INFO [lunar_connection::model_chooser] [2021-09-29T10:37:01.807325500+03:00][INFO][6685 main][lunar_connection::model_chooser][Some("tabnine/lunar_connection/src/model_chooser.rs")][Some(38)] current private model is None
INFO [lunar_connection::model_chooser] [2021-09-29T10:37:01.807345700+03:00][INFO][6685 main][lunar_connection::model_chooser][Some("tabnine/lunar_connection/src/model_chooser.rs")][Some(40)] using initial model Model {
    model_hash_override: None,
    model_size: Small,
    base_url: "https://update.tabnine.com",
}
INFO [lunar_connection::local_lunar_connection] [2021-09-29T10:37:01.807597200+03:00][INFO][6685 main][lunar_connection::local_lunar_connection][Some("tabnine/lunar_connection/src/local_lunar_connection.rs")][Some(94)] starting default model pre-loader DownloadSettings {
    api_key: None,
    meta_data_base_url: "https://api.tabnine.com",
    model: Model {
        model_hash_override: None,
        model_size: Small,
        base_url: "https://update.tabnine.com",
    },
}
INFO [lunar_connection] [2021-09-29T10:37:01.807885300+03:00][INFO][6685 lunar settings update thread (Local default local)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(80)] lunar settings update thread started (Local default local)
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808191900+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(146)] Starting private model update thread
INFO [lunar_connection::project_model_override_installer] [2021-09-29T10:37:01.808277200+03:00][INFO][6685 main][lunar_connection::project_model_override_installer][Some("tabnine/lunar_connection/src/project_model_override_installer.rs")][Some(196)] project model override feature is disabled
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808374+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(161)] active private model is None
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808416900+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(170)] Checking if private model changed
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808437700+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(284)] removing private models from cache
ERROR [lunar_connection::private_models] [2021-09-29T10:37:01.808482800+03:00][ERROR][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(287)] Failed to remove private models from cache: No such file or directory (os error 2)
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808509400+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(194)] private model is same
INFO [frontend::initialize] [2021-09-29T10:37:01.808513700+03:00][INFO][6685 main][frontend::initialize][Some("tabnine/frontend/src/initialize.rs")][Some(5)] Started.
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808526800+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(197)] sleeping for 3600s
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808547900+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(170)] Checking if private model changed
INFO [lunar_connection] [2021-09-29T10:37:01.808522800+03:00][INFO][6685 lunar settings update thread (Remote cloud)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(80)] lunar settings update thread started (Remote cloud)
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808561400+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(284)] removing private models from cache
ERROR [lunar_connection::private_models] [2021-09-29T10:37:01.808591500+03:00][ERROR][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(287)] Failed to remove private models from cache: No such file or directory (os error 2)
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808609700+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(194)] private model is same
INFO [lunar_connection::private_models] [2021-09-29T10:37:01.808622300+03:00][INFO][6685 private-model-update-loop][lunar_connection::private_models][Some("tabnine/lunar_connection/src/private_models.rs")][Some(197)] sleeping for 3600s
INFO [lunar_connection::local_lunar_connection] [2021-09-29T10:37:01.837810300+03:00][INFO][6685 model-pre-loader][lunar_connection::local_lunar_connection][Some("tabnine/lunar_connection/src/local_lunar_connection.rs")][Some(308)] running command "/home/semel/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine-deep-local" "--settings" "/home/semel/.config/TabNine/local.settingsSmall" "--settings-version" "1" "--log-file-path" "/home/semel/.vscode-server/tabnine_log/tabnine_log.json-6369" "--client" "vscode" "--client-metadata" "clientVersion=1.60.2" "pluginVersion=3.4.29" "t9-vscode-AutoImportEnabled=true" "t9-vscode-TSAutoImportEnabled=true" "t9-vscode-JSAutoImportEnabled=true" "vscode-telemetry-enabled=true" "vscode-remote=true" "vscode-remote-name=wsl" "vscode-extension-kind=2" "vscode-theme-name=Community Material Theme Ocean High Contrast" "vscode-theme-kind=Dark" "vscode-machine-id=c4b598f7887b81a43e5b8633ca6064b3afc59a5db7cc255a1b46f0b56fcfe4e4" "vscode-is-new-app-install=false" "vscode-session-id=f15e0f94-401c-4c86-9cfe-f7a7bc91c4911632901016649" "vscode-language=en" "vscode-app-name=Visual Studio Code" "vscode-beta-channel-enabled=false" "vscode-status-customization=unknown" "ide-restart-counter=0"
INFO [auth::token] [2021-09-29T10:37:01.842318900+03:00][INFO][6803 main][auth::token][Some("shared/auth/src/token/mod.rs")][Some(41)] token path: /home/semel/.config/TabNine/tabnine.token
WARN [auth::user] [2021-09-29T10:37:01.857769+03:00][WARN][6803 main][auth::user][Some("shared/auth/src/user/mod.rs")][Some(252)] No user token available: No such file or directory (os error 2)
INFO [TabNine_deep_local] [2021-09-29T10:37:01.857872100+03:00][INFO][6803 main][TabNine_deep_local][Some("deep/lunar_endpoints/src/bin/TabNine-deep-local.rs")][Some(132)] parsed settings are Some(Settings { cpu_model: CpuModelSettings { rate_limit_interval_seconds: None, rate_limit_amount: None, enable_power_saving_mode: false }, download: DownloadSettings { api_key: None, meta_data_base_url: "https://api.tabnine.com", model: Model { model_hash_override: None, model_size: Small, base_url: "https://update.tabnine.com" } }, tune: TuneSettings { enable_power_saving_mode: false, override_beams: None, override_context_length: None }, run: RunSettings { is_enabled: true, omit_prefix_suggestions: false, multiline_suggestions: false, line_suggestions: false } })
INFO [TabNine_deep_local] [2021-09-29T10:37:01.857908700+03:00][INFO][6803 main][TabNine_deep_local][Some("deep/lunar_endpoints/src/bin/TabNine-deep-local.rs")][Some(144)] local_lock_path "/home/semel/.config/TabNine/3.6.8/TabNine-deep-local.lockSmall"
INFO [TabNine_deep_local] [2021-09-29T10:37:01.898477600+03:00][INFO][6803 main][TabNine_deep_local][Some("deep/lunar_endpoints/src/bin/TabNine-deep-local.rs")][Some(175)] TabNine-deep-local is already running, responding with existing port
INFO [lunar_connection::local_lunar_connection] [2021-09-29T10:37:01.899990+03:00][INFO][6685 model-pre-loader][lunar_connection::local_lunar_connection][Some("tabnine/lunar_connection/src/local_lunar_connection.rs")][Some(131)] setting default model analytics
WARN [lunar_connection::cloud_availability] [2021-09-29T10:37:03.878139900+03:00][WARN][6685 main][lunar_connection::cloud_availability][Some("tabnine/lunar_connection/src/cloud_availability.rs")][Some(91)] Cannot connect to cloud: Ping request timed out after 2 seconds

INFO [team_ai::data_handling] [2021-09-29T10:37:03.878404300+03:00][INFO][6685 main][team_ai::data_handling][Some("tabnine/team_ai/src/data_handling.rs")][Some(32)] Initialized team ai database successfully at: /home/semel/.local/share/TabNine/team_learning/data_dir/sdb
INFO [team_ai] [2021-09-29T10:37:03.878576400+03:00][INFO][6685 main][team_ai][Some("tabnine/team_ai/src/lib.rs")][Some(73)] Initialized team ai learning successfully
INFO [lunar_connection::local_lunar_connection] [2021-09-29T10:37:11.909773800+03:00][INFO][6685 TabNine deep local exit wait thread][lunar_connection::local_lunar_connection][Some("tabnine/lunar_connection/src/local_lunar_connection.rs")][Some(320)] TabNine-deep-local exited with status exit status: 0
ERROR [team_ai::data_handling] [2021-09-29T10:37:21.620354900+03:00][ERROR][6685 heartbeat_loop][team_ai::data_handling][Some("tabnine/team_ai/src/data_handling.rs")][Some(71)] Failed to query metadata: InvalidColumnType(1, "total", Null)
WARN [team_ai] [2021-09-29T10:37:21.620515+03:00][WARN][6685 heartbeat_loop][team_ai][Some("tabnine/team_ai/src/lib.rs")][Some(102)] Failed to get metadata from team ai database: Failed to open team ai learning local database
WARN [bootstrapper::register] [2021-09-29T10:37:31.639222700+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::register][Some("tabnine/bootstrapper/src/register.rs")][Some(191)] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: TimedOut }
WARN [bootstrapper::register] [2021-09-29T10:37:31.639280600+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::register][Some("tabnine/bootstrapper/src/register.rs")][Some(193)] got an error. trying again
WARN [bootstrapper::register] [2021-09-29T10:38:01.754005200+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::register][Some("tabnine/bootstrapper/src/register.rs")][Some(191)] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: TimedOut }
WARN [bootstrapper::register] [2021-09-29T10:38:01.754054400+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::register][Some("tabnine/bootstrapper/src/register.rs")][Some(193)] got an error. trying again
WARN [bootstrapper::register] [2021-09-29T10:38:31.882965+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::register][Some("tabnine/bootstrapper/src/register.rs")][Some(191)] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: TimedOut }
WARN [bootstrapper::bootstrapper_lib] [2021-09-29T10:38:31.893409500+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(181)] failed registering to server: with error Server
WARN [bootstrapper::bootstrapper_lib] [2021-09-29T10:38:31.904069700+03:00][WARN][6647 bootstrapper_main_run_loop][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(188)] user belongs to default experiment so calling cloud front server fallback
`

--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

**Comment by yonip23** [comment]
i dont see any logs related to the Hub here, but from other log lines i can guess that your wsl is missing some configuration in the networking level - i.e proxy or something similar.

Can you please make sure that you can ping `api.tabnine.com` and `localhost` (on any port, but if not possible then only port 5555) from your wsl?

**Comment by eyalSemel** [comment]
you're right, I can't ping api.tabnine.com from wsl...
Do you have any idea why? pinging google and other server works fine

**Comment by yonip23** [comment]
Im sorry for misleading you - ping is not available for `api.tabnine.com`  😅 

You've got 2 different problems here:
1. Tabnine Hub doesn't work
2. Tabnine fails to reach `api.tabnine.com` 

For the first problem, try to type `tabnine::config` in your IDE, it'll open the Hub in a browser (and not inside the VSCode
(You need to set `$BROWSER` env var in order for it to work on wsl, see: https://github.com/codota/tabnine-vscode/issues/572)

See if you can access the url of the Hub from within the wsl and from your Windows - This will tell us whether its networking issue or the binary (`TabNine`) fails for some other reason.

For the second problem, try `curl https://www.tabnine.com` from within wsl and make sure you can access it from there.

Kind regards

**Comment by eyalSemel** [comment]
when I write tabine::config I get redirected to http://127.0.0.1:5555/sec-ipuzvdmqfpzcpjkctftv and get this response:
![image](https://user-images.githubusercontent.com/55841340/135348488-386eb92a-cf2f-4ea1-98fa-9b7eb421bf64.png)

when I type `curl https://www.tabnine.com` I succesfuly get the data...
any tips?

**Comment by yonip23** [comment]
Im afk now, will get back to you about `api.tabnine.com` tomorrow.
As for the localhost, maybe this is related? https://github.com/microsoft/WSL/issues/4636#issuecomment-552067645

**Comment by bilucodota** [comment]
Hi @eyalSemel 
I want to test if this is a network issue, or whether Tabnine crashes.
Can you please:

- type `tabnine::config` 
- browser opens on `http://127.0.0.1:port/secret`
- try to curl that endpoint from wsl (e.g `http://127.0.0.1:port/secret`)
- if it works, need to figure why Windows does not forward the traffic to wsl
- If it does not work - can you please try to type `tabnine::config` and then attach here Tabnine logs?

**Comment by eyalSemel** [comment]
Hi,
I just tried it and curl http://127.0.0.1:5555/sec-*** works fine....

**Comment by bilucodota** [comment]
So you need to check why Windows won't forward 5555 to wsl..
https://github.com/microsoft/WSL/issues/4636

**Comment by eyalSemel** [comment]
thank you for your help!
I'll give it a go

**Comment by bilucodota** [comment]
@eyalSemel closing this for now. Feel free to open another issue should you have any further questions.
