### ISSUE TITLE
Excessive cpu usage

### ISSUE THREAD

**Issue by st-schneider** [codota/tabnine-vscode#66]
Issue Type: <b>Bug</b>

It seems that sometime tabnine is hammering on all cpus at 100% without even having an active vscode window.

Extension version: 2.1.16
VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:36:54.895Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 10, 6|
|Memory (System)|16.00GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by anakaiti** [comment]
Having the same problem. Happens randomly with no significant activity.

**Comment by anonymouss** [comment]
+1.
especially when open a new project/folder in vscode.
I like this extension, wish it could be better.

**Comment by SoptikHa2** [comment]
Big issue for me as well.

I had open vscode for about 6 hours. For first few hours, nothing happened, even when I was using vscode actively.

Then, I left vscode running in the background and started watching youtube, vscode did nothing and was unfocused.

About 5 or 6 hours after vscode started, I started wondering why are my laptop fans running so much. So I fired htop.

![Screenshot-2020-01-02-01-39-03](https://user-images.githubusercontent.com/24734779/71648160-acc00b80-2cf8-11ea-821b-8d82ec0a0f15.png)
Why is my ram usage at 18G? It even started using swap! Why is the CPU usage so high?

**Comment by denialanderror** [comment]
Same for me. Fine when I open VSCode but leaving it running for a few hours and Tabnine got up to 192% CPU (MacOS).

**Comment by datuarellano** [comment]
+1
Same here. It likes to eat CPU and RAM. :( I disabled it for now.
<img width="413" alt="Screen Shot 2020-02-20 at 8 10 51 PM" src="https://user-images.githubusercontent.com/1914554/74932780-97747d00-541d-11ea-9fd9-f3d8ffe9b8d8.png">

VS Code Version: 1.42.1
OS: Darwin x64 19.2.0

**Comment by drorweiss** [comment]
Hi All, we have a fix in beta (version 2.3.4) for excessive CPU and memory consumption by TabNine.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both Update TabNine automatically and Receive beta releases of TabNine Then, restart your editor, and press TabNine::confiig to verify you have TabNine 2.3.4. or newer. Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by bm-stschneider** [comment]
What about using the vscode settings for that? Typing stuff in an editor with then having a window popped up is a bit disturbing.

**Comment by drorweiss** [comment]
@bm-stschneider are you referring to TabNine::config?

**Comment by bm-stschneider** [comment]
yes of course

**Comment by amircodota** [comment]
Anybody had a chance to try out the latest tabnine?
Can you verify if things improved in terms of cpu and RAM consumption?

**Comment by z3rog** [comment]
> Anybody had a chance to try out the latest tabnine?
> Can you verify if things improved in terms of cpu and RAM consumption?

i can say, it's still in high memory usage in my 2018 16GB Macbook Pro.. TabNine version 2.8.2 @amircodota

**Comment by amircodota** [comment]
@z3rog Can you share the numbers? What RAM usage do you observe?

**Comment by himanshu-satija** [comment]
I am getting RAM usage of 1.56 GB with the latest version
![image](https://user-images.githubusercontent.com/15103616/83233130-e0219c00-a1ab-11ea-8aff-efc737b7d74e.png)

**Comment by z3rog** [comment]
> @z3rog Can you share the numbers? What RAM usage do you observe? 
![image](https://user-images.githubusercontent.com/42612758/83234398-c17acf80-a1c2-11ea-9e10-709b416fa264.png)

@amircodota thanks for replying. here's what my monitor shows. i'm still curious about that, it is possible not to start another process after a new VSCode window opened ?  I personlly always open more than one window,  but that means another TabNine process starts running, and “without a second” another 1GB being used.

**Comment by amircodota** [comment]
@z3rog Those numbers are not un-common for TabNine.
What you can do is disable the "deep TabNine local" option, which will reduce the memory consumption significantly, but at the expense of the quality of suggestions.
You can also opt to use deep TabNine cloud instead of TabNine local (a paid option).

Regarding multiple windows open - I'm afraid currently each window will run its own tabnine process, but we've heard this complaint from many users, and we are looking into ways of resolving it.

**Comment by z3rog** [comment]
> @z3rog Those numbers are not un-common for TabNine.
> What you can do is disable the "deep TabNine local" option, which will reduce the memory consumption significantly, but at the expense of the quality of suggestions.
> You can also opt to use deep TabNine cloud instead of TabNine local (a paid option).
> 
> Regarding multiple windows open - I'm afraid currently each window will run its own tabnine process, but we've heard this complaint from many users, and we are looking into ways of resolving it.

thanks again, i'll try later.
