### ISSUE TITLE
Make "Enable Deep Completions Cloud"/"Enable Deep Completions Local" exclusive choices or clarify what happens when both are selected?

### ISSUE THREAD

**Issue by ldorigo** [codota/tabnine-vscode#674]
Currently it's possible to select both at the same time:

![image](https://user-images.githubusercontent.com/8631181/138880091-fd278158-3144-4ada-b1e0-f3ce317dc059.png)

Which is confusing - aren't they mutually exclusive? What happens when both are checked?

gz#8028

**Comment by bilucodota** [comment]
Closing this issue for now. Let me know should you have any further questions.
