### ISSUE TITLE
TabNine globally installs its own version of Flow and this is impacting a project using a different version of Flow

### ISSUE THREAD

**Issue by infernocloud** [codota/tabnine-vscode#68]
Whenever the TabNine extension installs Flow globally (version 0.116.1), it seems to completely overrule the active Flow binary inside of VS Code and I get many new errors in my console that aren't then when it is running the version specified in my project (version 0.105.0).

Is there a way to make this not install a new version of Flow globally, or somehow work nicer with existing Flow projects?

**Comment by dimacodota** [comment]
hey @infernocloud  - you can use your project flow version by following these steps:

 -  open Tabnine::config (command pallet -> tabnine: config)
 -  locate your configuration folder ("Configuration path" in the first section)
 -  navigate to your configuration folder (the path without the json file)
 -  create a TabNine.toml file in this directory with following configuration(adjust the path relative to your project file and keep the `${project_root}` placeholder) 

```
[language.javascript]
command = "${project_root}/path-to-your-local-flow-version" 
args = ["--stdio"] 
```

You can read more about how to configure it [here](https://www.tabnine.com/semantic)
