### ISSUE TITLE
Automatically inserted closing bracket not skipped

### ISSUE THREAD

**Issue by disappearer** [codota/tabnine-vscode#69]
I've just started using this extension and so far it's awesome! Thank you very much for your time and effort!

One problem that I have:
Usually, when I type `(`, vs code inserts the closing bracket automatically and if I type something like a function parameter and then type the closing bracket `)` it just skips the already inserted one. Same goes when using suggestions from vs code, between the two brackets, when tabnine is disabled. On the other hand when I use tabnine suggestion and type the closing bracket, the automatically inserted bracket doesn't get skipped, but a new closing bracket is inserted like so `(param))`. This is quite inconvenient, since I have to move my hand to the arrow keys, or type a lot to enter vim normal mode and then skip the closing bracket and continue typing, or even use the trackpad/mouse. Could this be fixed?

I'm sorry if this issue has been posted already, but I couldn't find it in the main repo nor this one.

**Comment by quezak** [comment]
(looks to be already reported in #47 and #60)

**Comment by disappearer** [comment]
> (looks to be already reported in #47 and #60)

You're right. I was searching with `parenthesis` instead of `parentheses` and #60 doesn't even mention any of the keywords I searched for.

**Comment by dimacodota** [comment]
the fix was released in version 2.2.3

**Comment by rmplbv** [comment]
I'm on version 3.6.4 and experiencing the exact problem.
