### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by elaverde** [codota/tabnine-vscode#690]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.4.35`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.62.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#8672

**Comment by maya-tabnine** [comment]
Hi!
I'm not sure I fully understand your request,
It would be great if you could provide some more info.
Thanks
