### ISSUE TITLE
Downloading deep model timeout

### ISSUE THREAD

**Issue by xingfanxia** [codota/tabnine-vscode#693]
**please complete the following information:**	
 - OS version: Mac Catalina
 - Editor: Vscode
 - Editor version: 
 ```Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```
 - Programming language: python
 - TabNine extension version:
 - 3.5.0
 - Engine version (could be located within Tabnine Hub): 4.0.4-45

**Issue Details:**
downloading deep model timed out
![image](https://user-images.githubusercontent.com/8936233/141968306-4d9e8431-2214-4deb-9003-d6fb3f89361c.png)
it's stuck in 
![image](https://user-images.githubusercontent.com/8936233/141968785-5543a438-32ca-44ab-b655-eaf40acba79d.png)

gz#8794

**Comment by yonip23** [comment]
@xingfanxia we're the same guys here you know 😬 
Closing this issue as its a duplicate: https://github.com/codota/TabNine/issues/478
