### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jasmeet78** [codota/tabnine-vscode#696]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.5.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#8927

**Comment by yonip23** [comment]
Hi @jasmeet78, what seems to be the problem?
