### ISSUE TITLE
Slowing down typing

### ISSUE THREAD

**Issue by aithurburn** [codota/tabnine-vscode#701]
Issue Type: <b>Bug</b>

Typing is greatly hindered with this extension active

Extension version: 3.5.1
VS Code version: Code - Insiders 1.63.0-insider (c1f2f40bcd81380bf2e286af64becddada57db88, 2021-11-24T05:33:22.438Z)
OS version: Windows_NT x64 10.0.22504
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.16GB free)|
|Process Argv|--crash-reporter-id 11ceb09c-5c06-4704-8eb4-1b1ab7cbaf25|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt1:30397558
vscop804:30404766
vscop940:30404999

```

</details>

gz#9045

**Comment by maya-tabnine** [comment]
Hi!
Are you not satisfied with the suggestions you get?

**Comment by imsys** [comment]
It is always using 10% ~ 20% CPU, even when I'm browsing the internet and VS code is in the background, (on Arch Linux) so I'm disabling it for now.
