### ISSUE TITLE
Extension name too long

### ISSUE THREAD

**Issue by Tschrock** [codota/tabnine-vscode#715]
- OS version: Windows 10 Pro - 21H2 - build 19044.1288
- Editor version: 1.62.3
- Programming language: n/a
- TabNine extension version: v3.5.2

**Issue Details:**
The extension name is extremely long, which causes multiple issues:
1. The title in the extension list is cut off
2. The title on the extension page is cut off
3. The tab for the extension page extremely wide, making it difficult to close or switch tabs
![Code_hf27pNwL3z](https://user-images.githubusercontent.com/2406499/144900762-a248d863-a62f-4361-861f-5d4f5fb63873.png)

4. The accounts menu gets blown out extremely wide
![Code_UGAFuodEnu](https://user-images.githubusercontent.com/2406499/144900870-248ddeff-ccb7-4e86-83c4-a434815fae9a.png)

gz#9632

**Comment by maya-tabnine** [comment]
Hi!
It is like that since we found it makes it easier to find the extension in the search.
We are aware of the long name and considering making it shorter. I will talk to our team and pass on your feedback.

**Comment by Foxhoundn** [comment]
It looks like it's been fixed? Finally :)
![CleanShot 2021-12-10 at 11 24 07](https://user-images.githubusercontent.com/8861481/145558795-4f107196-85a2-4834-a382-341a30190934.png)
![CleanShot 2021-12-10 at 11 23 59](https://user-images.githubusercontent.com/8861481/145558811-e55b82b9-9799-455f-bef3-a87b5d5d644d.png)
