### ISSUE TITLE
Tabnine clashes with auto-import from VSCode while using JavaScript

### ISSUE THREAD

**Issue by deadcoder0904** [codota/tabnine-vscode#74]
This is how auto-import works in VSCode & it works without installing any extension but when I install Tabnine it ruins the auto-import.

**Comment by dimacodota** [comment]
This issue is in the testing stage, we will appreciate any feedback on this, if anyone wants to be a beta tester please reply and I will send you vsix with beta version.

**Comment by dimacodota** [comment]
The auto import support was released in the 2.8.4 version. 
To enable this, go to settings and set the `Tabnine: Experimental Auto Imports` to true.

**Comment by giangchau92** [comment]
Still not working

> The auto import support was released in the 2.8.4 version.
> To enable this, go to settings and set the `Tabnine: Experimental Auto Imports` to true.
