### ISSUE TITLE
can't open the setting panel

### ISSUE THREAD

**Issue by Siwwc** [codota/tabnine-vscode#741]
**please complete the following information:**

- OS version: Win 11
- Editor version: 1.64.0-insider
- Programming language: Rust
- TabNine extension version: 3.5.14

**If the issue is related to TabNine failure, please provide log files:**

**Editor console logs:**
Error: Binary request timed out.    at Timeout._onTimeout (c:\Users\28219\.vscode-insiders\extensions\tabnine.tabnine-vscode-3.5.14\out\extension.js:17:31578)
Error: Could not get enabled capabilities    at Object.t.getCapabilities (c:\Users\28219\.vscode-insiders\extensions\tabnine.tabnine-vscode-3.5.14\out\extension.js:17:42279) 
Binary child process exited with code 3221225781 signal unknown 

**Issue Details:**
Suddenly doesn't work, I just upgrade to pro yesterday, Sad

gz#10749

**Comment by mjbates7** [comment]
I'm also getting this same error but windows 10 and it doesn't matter what language I'm trying to open the settings on.

3.5.14 alpha (also tried non-alpha)

**Comment by Siwwc** [comment]
> Hi @Siwwc, We released a new engine version 4.0.49 to beta which should resolve the issue. can you please reopen all your vscode instances and try again?

How can I download the beta version

**Comment by Siwwc** [comment]
> Hi @Siwwc, We released a new engine version 4.0.49 to beta which should resolve the issue. can you please reopen all your vscode instances and try again?

I reopen the vscode, but the error still exists

**Comment by mjbates7** [comment]
I couldn't see how to download the beta either.. looked for pre-release option in the extension and also under releases on GitHub for a .vsix installer.

I'm on Pro also.

**Comment by dimacodota** [comment]
can you please share  a screenshot of  your directory structure inside %APPDATA%\Code\User\globalStorage\tabnine.tabnine-vscode folder ?

**Comment by mjbates7** [comment]
Hello,

Please find the following screenshot. Top being the folder you suggested then the second being the sub "binaries" folder.

![image](https://user-images.githubusercontent.com/4522738/148918738-1294db66-2dad-4e48-9324-e73f92eeffea.png)

**Comment by Eidenz** [comment]
Same issue, and my folder looks the exact same as mjbates7 even though "receive beta updates" is checked

**Comment by dimacodota** [comment]
thanks, can you please share the content of the `.active` file?

**Comment by Eidenz** [comment]
"4.0.47" for my part

**Comment by mjbates7** [comment]
Also `4.0.47`

**Comment by yonip23** [comment]
Hi all
Please try deleting the `.active` file as well as the folder `4.0.47` and lmk if it fixes your problem. We'll release a fix for that soon.

**Comment by mjbates7** [comment]
Hello,

After deleting that file, I can now access the tabnine configuration panel/settings and it seems to be working. My `.active` file has now got a value of `4.0.49`.

**Comment by Eidenz** [comment]
Works for me as well

**Comment by yonip23** [comment]
Great, thanks for your patience guys!
We're working on a fix to help all users get out of version 4.0.47, will be out soon

**Comment by Siwwc** [comment]
Works for me. Happy

**Comment by Eidenz** [comment]
Now on version `4.0.49` tabnine works but shows a weird error when trying to open the panel:
`Error loading webview: Could no register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

And of course the panel is completely dark.
