### ISSUE TITLE
Tabnine doesn't work with insider builds of vscode

### ISSUE THREAD

**Issue by jeffrgh** [codota/tabnine-vscode#743]
It doesnt work with latest vscode insider.. It does work with regular vscode

gz#10824

**Comment by bilucodota** [comment]
Hi @jeffrgh can you add more details about your setup? + attach some video/screenshots

**Comment by jeffrgh** [comment]
Version 1.64.0 insiders

**Comment by jeffrgh** [comment]
Nvm works now...
Must have been a version issue...
