### ISSUE TITLE
Global IntelliSense crash in VS code

### ISSUE THREAD

**Issue by VyazovskyE** [codota/tabnine-vscode#75]
After enabling TabNine IntelliSense vscode just does not suggest anything.

Update:
It seems after reloading vscode it works properly but only for few minutes.

Before:
![wo_tabnine](https://user-images.githubusercontent.com/51908480/74875352-c7167d00-536a-11ea-9c2b-4178fc400f18.gif)

After:
![with_tabnine](https://user-images.githubusercontent.com/51908480/74875367-ce3d8b00-536a-11ea-9340-2cbeaa261c40.gif)

It was working fine before. 
I did not used vscode for like 2-3 month.

Installed extensions:

Auto close tag
Auto rename tag
Bracker Pair Colorizer 2
Color HighLight
DetENV
EsLint
IntelliSence for CSS class names in HTML
Live Server
Node.js modules Intellisense
Path intellisense
Prettier
Pug beautify
TODO highlight

**Comment by amircodota** [comment]
Hi @VyazovskyE 

Can you specify:
1. What is your vscode version?
2. What is your tabnine plugin version?
3. Reproduce the issue and then send the log file?

To get the log file, type `tabnine::config`, and a browser window should open.
At the bottom, you'll see the log file.

Thanks
Amir

**Comment by VyazovskyE** [comment]
VScode version - 1.42
Tabnine - 2.2.3

I can't open config after autocompletion stops working.
Here is 2 logs. One right after starting VScode and another after about 30 seconds.

**Comment by amircodota** [comment]
I see this in the log file:

"Server did not respond with version, so using default URL"

Is it possible that you do not have network access? Maybe you are behind a proxy or a firewall?

**Comment by VyazovskyE** [comment]
Same connection as before.
Default VScode autocompletion crashes too, but it should work even wo network.

**Comment by amircodota** [comment]
Can you check vscode console output to see if tabnine printed any error?

Two places to check:
1. Help -> Toggle Developer Tools
2. Terminal Window -> Output -> Select "Log (Extension Host)" in the dropdown

Thanks

**Comment by VyazovskyE** [comment]
![image](https://user-images.githubusercontent.com/51908480/76299078-1fce9b00-62c3-11ea-9c40-9817235af096.png)
[log.txt](https://github.com/codota/tabnine-vscode/files/4311462/log.txt)
[log2.txt](https://github.com/codota/tabnine-vscode/files/4311463/log2.txt)
