### ISSUE TITLE
tabnine not working in vsc

### ISSUE THREAD

**Issue by bumby123** [codota/tabnine-vscode#752]
**please complete the following information:**

- OS version: w11
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#11048

**Comment by bumby123** [comment]
hi please someone help me to run Tabnine in VSC? it not runs only appears in the tab starting......

**Comment by maya-tabnine** [comment]
Hi, when you type TabNine::config does it not open Tabnine Hub?
Would you perform the following steps:
1. Uninstall Tabnine from VSCode
2. Delete the Tabnine folder completely ( C:\Users\{UserName}\AppData\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\ )
3. Install Tabnine again

Let me know if that fix this

**Comment by bumby123** [comment]
Hi Maya I had your steps but tabnine not runs yet. My computer is a Dell
E7240 with 120 gb ssd but all the programs runs from a wd mypassport hdd
1tb. So Vsc is installed in in external drive. Additionally I have windows
11 operative system. Is rare a few times Tabnine is running and is a
practical tool for complete code. Maybe some route from external drive to
120 gd ssd will the problem. I think not, because vsc is running correctly,
Recently, I used it with node js, react, edge devtools for debugging and
Visual Studio Code hasnt problems.

Another error I detected Maya is that when I try to install Tabnine from
VSC extension hub is that not always the files download completely, I
dont know why but this effect is occurring me constantly with tabnine.
Maybe if is posible Maya could you send me a a zip file to install manually
tabnine from windows file explorer? I think this alternative maybe help me
a lot, try please. Best regards

**Comment by maya-tabnine** [comment]
Hi, do you have a proxy or firewall? Perhaps there is a block.
Anyway you can try downloading Tabnine from https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode&ssr=false#version-history

**Comment by bumby123** [comment]
hi Maya, im still have problems with Tabnine. I detected when I try to
download the files are incomplete. I also check the firewall I do all
exceptions to tabnine but still it not runs. So in discord someone shared
me a link of github with all the code of tabnine to visual studio code, so
I could install it manually, without lose files.

My question is how can I install Tabnine using this cloned github repository
https://github.com/codota/tabnine-vscode

**Comment by maya-tabnine** [comment]
@bumby123 Can we talk over email? Or even set up a meeting and provide you with detailed instructions. 
We suspect there is an issue there, perhaps related to Win11.

**Comment by bumby123** [comment]
Hi Maya I live in Quito Ecuador, i always trying to contact you via discord
but the answers arrive in 2 days aprox. I think this is maybe by different
time zones. what I most want is for tabnine to work on my computer, I think
it could also be some path because as I mentioned before, vsc runs from an
external hard drive, but there are still parts that are on the main drive,
despite the fact that few sometimes tabnine has worked for me and the other
extensions have had no performance problems, of course if you want we can
meet on discord when you can confirm me. Tell me what you think. Best
regards

**Comment by maya-tabnine** [comment]
Hi @bumby123, I did not see your Discord ticket. What is your username there? I will contact you and we can set up a meeting.

**Comment by nwachukwuoparah** [comment]
hello i installed the extension a few days ago but this week i started setting it up and i got this i am using mac OS and i am on free plan i need directions 
@maya-tabnine 

Tabnine Chat - Preview Period Ended
The preview period for Tabnine Chat in Visual Studio Code has now ended. We hope you found it valuable for your coding projects and enjoyed the experience.

To continue using Tabnine Chat and access its full range of features, we invite you to subscribe to one of our plans.

You can find detailed information about our pricing and the additional benefits of a subscription on our [pricing page](https://www.tabnine.com/pricing).

If you have any questions or need assistance, our support team is always ready to help.

**Comment by drunkcat** [comment]
> hello i installed the extension a few days ago but this week i started setting it up and i got this i am using mac OS and i am on free plan i need directions @maya-tabnine
> 
> Tabnine Chat - Preview Period Ended 

Have you found a solution?

**Comment by Eddiexxx** [comment]
Hi I have installed tabnine but it does not work , I uninstalled it and remove the folder that you had said , but the problem is still on , my inline suggestion is also on and I don't know why it is not working and I have not any suggestion at all

**Comment by Arora-Sir** [comment]
[**@Eddiexxx**](https://github.com/Eddiexxx) commented on [Jul 7, 2024, 7:27 PM GMT+5:30](https://github.com/codota/tabnine-vscode/issues/752#issuecomment-2212459863 "2024-07-07T13:57:39Z - Replied by Github Reply Comments"):
> Hi I have installed tabnine but it does not work , I uninstalled it and remove the folder that you had said , but the problem is still on , my inline suggestion is also on and I don't know why it is not working and I have not any suggestion at all

I've done all the steps too, but nothing seems working. Have you found any solution to this?
