### ISSUE TITLE
Can I limit the number of threads in Tab9?

### ISSUE THREAD

**Issue by weiwandege77** [codota/tabnine-vscode#758]
**please complete the following information:**

- OS version: linux
- Editor version [e.g. 1.45.0-insider]: vscode 2019
- Programming language: [e.g. js, ts, c++] python
- TabNine extension version: v3.5.17

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**
![image](https://user-images.githubusercontent.com/48820768/151300816-3a9f5cf0-d676-4a01-ab2b-8bb0f1d517d0.png)

pls！

gz#11250

**Comment by maya-tabnine** [comment]
Hi do you experience any problems due to the threads? Does TabNine take too much CPU or memory?
