### ISSUE TITLE
tabnine notify to enable semantic on macos although clangd is installed. 

### ISSUE THREAD

**Issue by elliotthuynh** [codota/tabnine-vscode#76]
On vscode, tabnine show 
Type TabNine::sem to enable semantic completion for C/C++.
The completion backend is `clangd`, which you will need to install manually.
Type TabNine::no_sem to suppress this message.
To learn more about semantic completion, see https://tabnine.com/semantic.

but on terminal, clangd work
clangd
clangd is a language server that provides IDE-like features to editors.

It should be used via an editor plugin rather than invoked directly. For more information, see:
        https://clang.llvm.org/extra/clangd/
        https://microsoft.github.io/language-server-protocol/

clangd accepts flags on the commandline, and in the CLANGD_FLAGS environment variable.

I[10:12:33.129] clangd version 9.0.1 
I[10:12:33.130] Working directory: 
I[10:12:33.130] argv[0]: clangd
I[10:12:33.130] Starting LSP over stdin/stdout

**Comment by SMores** [comment]
I'm experiencing the same with the typescript language server on macOS.

>TabNine was unable to start the typescript semantic completion backend.
>The command that failed was: `yarn global add typescript-language-server`
>This means you need to install the backend manually.
>For help, see tabnine.com/semantic.
>Or, type TabNine::no_sem to disable semantic completion for TypeScript.
>(TabNine works well even without semantic completion.)
