### ISSUE TITLE
Memory usage problem

### ISSUE THREAD

**Issue by ultronnet** [codota/tabnine-vscode#766]
**please complete the following information:**

- OS version: [e.g. Mac Monterey 12.1]: Mac Monterey 12.1
- Editor version [e.g. 1.45.0-insider]: 1.63.2 (Universal)
- Programming language: [e.g. js, ts, c++] Java | golang
- TabNine extension version: 3.5.17 (engine version 4.0.60-46)

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

<img width="753" alt="image" src="https://user-images.githubusercontent.com/72001621/152087849-2cb8d223-af41-4022-912b-28b294eef78a.png">

gz#11419

**Comment by maya-tabnine** [comment]
Hi, I would like to get your Tabnine logs. What IDE do you use? I will provide detailed instructions.
