### ISSUE TITLE
TabNine don't write variables

### ISSUE THREAD

**Issue by adriankarlen** [codota/tabnine-vscode#77]
## Below is an video displaying the issue I am having
![tabnine_issue](https://user-images.githubusercontent.com/18417539/76290881-5220ce00-62ac-11ea-8281-e4a1e02b79c2.gif)

In words. TabNine suggests a line containing a variable, but when I tab to write the suggestion out it writes everything but the variable. I only seem to have this issue with php variables. I don't know if it has something to do with the $-sign. 

What can be said that it worked as intended before I installed a phpdoc-extension. The thing is when I noticed that it had stopped working I uninstalled that extension only to have the issue still persist.

Tried looking through the log but could really find anything that seemed relevant. Mostly it was just complaining scanning image-files in another directory in the repo.

This is the log when searching
```
[2020-03-10][09:08:45][lunar_transport::client][INFO] Searching for completions with prefix " e"
[2020-03-10][09:08:45][server][DEBUG] [autocomplete] 15 ms
[2020-03-10][09:08:45][lunar_transport::controller][INFO] Round-trip time: 151 ms.
```

**Comment by blueandhack** [comment]
I have same issue
