### ISSUE TITLE
can not sign in vscode tabnine

### ISSUE THREAD

**Issue by young1024** [codota/tabnine-vscode#776]
**please complete the following information:**

- OS version: [ubuntu 16.04]
- Editor version [1.64.1-vscode]:
- Programming language: [c++]
- TabNine extension version:3.5.24

**Issue Details:**
tabnine is perfect，it improved my code speed, thanks very much!
but I can't access tabnine sign in website, as follows:
![image](https://user-images.githubusercontent.com/25336944/153110708-d9d03905-2d7d-4679-b76b-e25d7c19229d.png)
![image](https://user-images.githubusercontent.com/25336944/153110870-b14f88b9-6b94-48f1-85d8-22099e36138f.png)

I can access tabnine website([https://www.tabnine.com/pricing/landing](https://www.tabnine.com/pricing/landing))
![image](https://user-images.githubusercontent.com/25336944/153111264-91e9200c-6eac-4e81-a687-12a3e8090878.png)

what's wrong with this.

gz#11749

**Comment by bilucodota** [comment]
Hi @young1024. Thanks for reaching out. Can you try a different network/browser?

**Comment by young1024** [comment]
> Hi @young1024. Thanks for reaching out. Can you try a different network/browser?

Hi @bilucodota. I refer to your suggestion, try chrome, firefox web browser, change other network, other co-worker try access, got the same result(can access [https://www.tabnine.com](https://www.tabnine.com), unable to access [http://app.tabnine.com](http://app.tabnine.com/))

**Comment by alejandr0k** [comment]
> 
Sup man, I had the same exactly issue, I didn't find out what was the problem but I fixed (at least temporally this way) :
If you are in Windows> Go to Task Manager where appears all windows process, scroll to "T", there I found 3 process called 
tabnine.exe and ended them one per one.
(The white loading page was trying to load when I ended those process, and it suddenly fully loaded into the browser and signed in VSCODE).
Hope it help you.

**Comment by bilucodota** [comment]
@young1024 is this still happening? where are you located? are you behind proxy/a vpn?

**Comment by young1024** [comment]
> @young1024 is this still happening? where are you located? are you behind proxy/a vpn?

The problem is still there, I have tried switching the VPN on and off, but the effect doesn't change.

**Comment by young1024** [comment]
> > 
> 
> Sup man, I had the same exactly issue, I didn't find out what was the problem but I fixed (at least temporally this way) : If you are in Windows> Go to Task Manager where appears all windows process, scroll to "T", there I found 3 process called tabnine.exe and ended them one per one. (The white loading page was trying to load when I ended those process, and it suddenly fully loaded into the browser and signed in VSCODE). Hope it help you.

Thanks for your suggestion, I have tried but failed.

**Comment by SimSimY** [comment]
Hey @young1024 

Based on the screenshot, this looks like a DNS issue - NXDOMAIN means that the browser has failed to resolve the domain`

Can you try to:
  1. `ping app.tabnine.com` - if you manage to resolve to an IP address (`35.244.201.191` in my case) - try to access the site again, to ensure that plugins are not blocking you - I would suggest that you try to login with chrome's `Guest` profile. 
  2. `dig +trace app.tabnine.com -t A` - If you get an error resolving the domain name, try running `dig` and share the result, 
  3. If that fails as well, try using open servers such as Google's `8.8.8.8 & 8.8.4.4`, you can test if that will work for you by checking the result of `dig +trace app.tabnine.com -t A @8.8.8.8`
  4. If that fails as well, try adding  (this is a temp fix as our IP address changes from time to time)  a record in your `/etc/hosts` file: `35.244.201.191 app.tabnine.com` 

As you are using VPN, I would suggest trying steps 1 & 2 & 3 (the `dig` command) with the VPN and and Off to see if there is any difference.  Also, I've attached my local output of the trace command for reference :

```

; <<>> DiG 9.10.6 <<>> +trace app.tabnine.com -t A
;; global options: +cmd
[...]
.			84806	IN	NS	g.root-servers.net.
[...]
;; Received 525 bytes from 8.8.8.8#53(8.8.8.8) in 67 ms

[...]
com.			172800	IN	NS	e.gtld-servers.net.
[...]
;; Received 1178 bytes from 2001:500:12::d0d#53(g.root-servers.net) in 76 ms

tabnine.com.		172800	IN	NS	ns-36.awsdns-04.com.
tabnine.com.		172800	IN	NS	ns-757.awsdns-30.net.
tabnine.com.		172800	IN	NS	ns-1753.awsdns-27.co.uk.
tabnine.com.		172800	IN	NS	ns-1515.awsdns-61.org.
[...]
;; Received 745 bytes from 2001:502:1ca1::30#53(e.gtld-servers.net) in 136 ms

app.tabnine.com.	300	IN	CNAME	_gcp-static-ip-production-1.tabnine.com.
_gcp-static-ip-production-1.tabnine.com. 300 IN	A 35.244.201.191
tabnine.com.		172800	IN	NS	ns-1515.awsdns-61.org.
tabnine.com.		172800	IN	NS	ns-1753.awsdns-27.co.uk.
tabnine.com.		172800	IN	NS	ns-36.awsdns-04.com.
tabnine.com.		172800	IN	NS	ns-757.awsdns-30.net.
;; Received 238 bytes from 2600:9000:5300:2400::1#53(ns-36.awsdns-04.com) in 317 ms

```

**Comment by hauseyo** [comment]
Hi, I am getting a similar issue. But instead of getting the error, I see the empty screen only. If I try to sign it in a different browser, i.e. Safari, I get the following error (screen attached)

<img width="487" alt="Screenshot 2022-02-17 at 09 51 33" src="https://user-images.githubusercontent.com/63884278/154421519-3eca23ee-735c-4367-8afb-c899d28e14bd.png">

Could you please help?

**Comment by Betristor** [comment]
> > > 
> > 
> > 
> > Sup man, I had the same exactly issue, I didn't find out what was the problem but I fixed (at least temporally this way) : If you are in Windows> Go to Task Manager where appears all windows process, scroll to "T", there I found 3 process called tabnine.exe and ended them one per one. (The white loading page was trying to load when I ended those process, and it suddenly fully loaded into the browser and signed in VSCODE). Hope it help you.
> 
> Thanks for your suggestion, I have tried but failed.

The same problem is bothering me for two days. I switched my VPN on and off and filtered the firewall, nothing changed. And I tried this later, but the processes got themselves back immediately.

**Comment by Betristor** [comment]
> Hey @young1024
> 
> Based on the screenshot, this looks like a DNS issue - NXDOMAIN means that the browser has failed to resolve the domain`
> 
> Can you try to:
> 
> 1. `ping app.tabnine.com` - if you manage to resolve to an IP address (`35.244.201.191` in my case) - try to access the site again, to ensure that plugins are not blocking you - I would suggest that you try to login with chrome's `Guest` profile.
> 2. `dig +trace app.tabnine.com -t A` - If you get an error resolving the domain name, try running `dig` and share the result,
> 3. If that fails as well, try using open servers such as Google's `8.8.8.8 & 8.8.4.4`, you can test if that will work for you by checking the result of `dig +trace app.tabnine.com -t A @8.8.8.8`
> 4. If that fails as well, try adding  (this is a temp fix as our IP address changes from time to time)  a record in your `/etc/hosts` file: `35.244.201.191 app.tabnine.com`
> 
> As you are using VPN, I would suggest trying steps 1 & 2 & 3 (the `dig` command) with the VPN and and Off to see if there is any difference. Also, I've attached my local output of the trace command for reference :
> 
> ```
> 
> ; <<>> DiG 9.10.6 <<>> +trace app.tabnine.com -t A
> ;; global options: +cmd
> [...]
> .			84806	IN	NS	g.root-servers.net.
> [...]
> ;; Received 525 bytes from 8.8.8.8#53(8.8.8.8) in 67 ms
> 
> [...]
> com.			172800	IN	NS	e.gtld-servers.net.
> [...]
> ;; Received 1178 bytes from 2001:500:12::d0d#53(g.root-servers.net) in 76 ms
> 
> tabnine.com.		172800	IN	NS	ns-36.awsdns-04.com.
> tabnine.com.		172800	IN	NS	ns-757.awsdns-30.net.
> tabnine.com.		172800	IN	NS	ns-1753.awsdns-27.co.uk.
> tabnine.com.		172800	IN	NS	ns-1515.awsdns-61.org.
> [...]
> ;; Received 745 bytes from 2001:502:1ca1::30#53(e.gtld-servers.net) in 136 ms
> 
> app.tabnine.com.	300	IN	CNAME	_gcp-static-ip-production-1.tabnine.com.
> _gcp-static-ip-production-1.tabnine.com. 300 IN	A 35.244.201.191
> tabnine.com.		172800	IN	NS	ns-1515.awsdns-61.org.
> tabnine.com.		172800	IN	NS	ns-1753.awsdns-27.co.uk.
> tabnine.com.		172800	IN	NS	ns-36.awsdns-04.com.
> tabnine.com.		172800	IN	NS	ns-757.awsdns-30.net.
> ;; Received 238 bytes from 2600:9000:5300:2400::1#53(ns-36.awsdns-04.com) in 317 ms
> ```

I could resolve the domain, but there is no response when ping tabnine.com. So I'm thinking it's not the fault of DNS or network, but something to do with requesting localhost's port and resources. BTW, I'm no expert in IT, it's just a guess.

**Comment by raykle** [comment]
I have the same problem.
And I'm using a VPN.

- OS version: [MacOS 12.2.1]
- Editor version [1.64.2 (Universal)]:
- Programming language: [js]
- TabNine extension version:3.5.26

![image](https://user-images.githubusercontent.com/3097366/156114421-4acfb124-0cc4-4bff-bccf-c29033704d92.png)

![image](https://user-images.githubusercontent.com/3097366/156114756-b3a8d4e2-4f7c-4efc-b16f-2c182c6ff738.png)

**Comment by bilucodota** [comment]
Hi @raykle - we've just released a fix which should solve the issue. Can you please make sure your `Engine Version` (under `Preferences`) is `4.0.120` and retry?

**Comment by Betristor** [comment]
> Hi @raykle - we've just released a fix which should solve the issue. Can you please make sure your `Engine Version` (under `Preferences`) is `4.0.120` and retry?

I successfully signed in, though actually I did nothing.
I checked the engine version, it's 4.0.120-45. Thanks for your working!
![image](https://user-images.githubusercontent.com/55777837/156349916-73a55b67-6946-415b-a21b-89754d84964d.png)

**Comment by bilucodota** [comment]
Thanks guys. We switch to provider which supports China. Closing this ticket for now. Let us know should you have further issues.
