### ISSUE TITLE
make extension work for web

### ISSUE THREAD

**Issue by its-pablo** [codota/tabnine-vscode#777]
![image](https://user-images.githubusercontent.com/78528552/153724534-59e9e92c-4c42-408d-91bf-765135a13160.png)

gz#11869

**Comment by maya-tabnine** [comment]
Hi, Tabnine is not supported on vscode.dev.
I will pass this request to the team. If we'd see enough interest from the community, we will make sure such a plugin exists :)

**Comment by its-pablo** [comment]
thx

**Comment by ksylvan** [comment]
The TabNine extension can work with VSCode Web, all you have to do is port forward the ports used by the hub and tabnine-deep from localhost (where you are accessing VSCode Web) and the code-server (where the tabnine engines are running).

**Comment by wardnath** [comment]
it says the extension isn't available in marketplace when searching for extension on `https://vscode.dev` - not sure how that approach resolves this @ksylvan ?

**Comment by ksylvan** [comment]
> it says the extension isn't available in marketplace when searching for extension on `https://vscode.dev` - not sure how that approach resolves this @ksylvan ?

Oh I see, vscode.dev is the ready to use version. I’m using my self-hosted version:

See https://github.com/ksylvan/remote-coding/blob/main/README.md#a-note-on-using-tabnine-and-vscode-web
