### ISSUE TITLE
Kaspersky identifies TabNine.exe as Trojan-Dropper.Win32.Agent.testhz

### ISSUE THREAD

**Issue by Supportic** [codota/tabnine-vscode#78]
It deletes this file and it's occuring only since today. 03/12/2020
Path: '.vscode\extensions\tabnine.tabnine-vscode-2.2.3\binaries\2.4.1\x86_64-pc-windows-gnu\TabNine.exe'

**Comment by yahave** [comment]
dup https://github.com/codota/TabNine/issues/232

**Comment by amircodota** [comment]
This has been a false identification by Kaspersky. If you update Kaspersky to the latest definitions file TabNine.exe should not be flagged anymore.
We will really appreciate if you can verify that it is indeed solved.

We are working with Kaspersky to make sure that this does not repeat in future versions.

**Comment by Supportic** [comment]
It is fine now, thanks.
