### ISSUE TITLE
Unable to use Tabnine

### ISSUE THREAD

**Issue by batu1579** [codota/tabnine-vscode#788]
- OS version: [Win10]
- Editor version [1.64.2]:
- Programming language: [js, python]
- TabNine extension version: 3.5.26

**Editor console logs:**

  ERR [Extension Host] Error: Binary request timed out. {"State":{}}
    at Timeout._onTimeout (c:\Users\batu\.vscode\extensions\tabnine.tabnine-vscode-3.5.26\out\extension.js:17:31653)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
console.ts:137 [Extension Host] Error: Binary request timed out. {"State":{}}    at Timeout._onTimeout (c:\Users\batu\.vscode\extensions\tabnine.tabnine-vscode-3.5.26\out\extension.js:17:31653)    at listOnTimeout (internal/timers.js:554:17)    at processTimers (internal/timers.js:497:7)
I @ console.ts:137
console.ts:137 [Extension Host] Binary not returning results, it is being restarted.

**Issue Details:**

Can someone help me? My tabnine suddenly stopped working, and my vscode autocomplete also stopped working. I found that vscode's smart hints work when tabnine is disabled. I followed the previous solution of the issue and tried to fix it by myself, but it didn't work. I deleted all the files in the folder "%APPDATA%\Code\User\globalStorage\tabnine.tabnine-vscode" and restarted vscode. But the Tabnine Settings page only opened for a few seconds after it was loaded. After that, nothing happened, and if I didn't close the Settings page for a while, it would tell me to lose the connection. I wish someone could help me.

p.s. My English is not very good, so I used Google Translate. There may be some deviation in the meaning of some sentences. I am very sorry

gz#12185

**Comment by maya-tabnine** [comment]
Hi what is your engine version and plugin version?

**Comment by maya-tabnine** [comment]
Hi what is your Tabnine engine version?

**Comment by batu1579** [comment]
You mean the file called ".active"?  It's 4.0.115 in that file

**Comment by maya-tabnine** [comment]
Can you also share your Tabnine logs?
Open VSCode settings, search "log file path", and enter a path on ‘Tabnine: Log File Path’ to get the logs. 
Something like /path/to/logs/filename.ext.
Restart your IDE and use it for a few minutes to let the logs flow in.
Then, you'll find a file named filename_rCURRENT.ext-<pid> in the given directory. Please attach it here or send it to us via email.

Thanks!

**Comment by leeyyl** [comment]
Yes, I have the same problem. I only can use free then I try to login my pro account it open web link but can't jump to vscode and active my pro account.

**Comment by maya-tabnine** [comment]
@batu1579  @leeyyl check out https://github.com/codota/tabnine-vscode/issues/776
Would you please make sure your Engine Version (under Preferences) is 4.0.120 and retry signing in?

**Comment by leeyyl** [comment]
It’s now work fine.
So I don’t know what happened before.


在 2022年3月2日 下午7:13:47 上，maya-tabnine ***@***.***> 写道：

**Comment by maya-tabnine** [comment]
@batu1579 it seems you have a different problem. Perhaps your engine is not running.
Try to run the following command from the terminal using the right path:
`PATH_TO_ENGINE/TabNine.cmd --log_to_stderr`

- **Mac**: /Users/{UserName}/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/{Binary_Version}/x86_64-apple-darwin/
- **Linux**: /Users/{UserName}/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/{Binary_Version}/x86_64-unknown-linux-musl/
- **Windows**: C:\Users\{UserName}\AppData\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\{Binary_Version}\x86_64-pc-windows-gnu\

Would you please also collect the output to a file and share it with us?
If that runs ok, I will give you instructions to get the VSCode Tabnine logs.

**Comment by maya-tabnine** [comment]
@batu1579 Hi, if you need our help, please contact us at support@tabnine.com with the logs I asked :) 
We would love to help!

**Comment by batu1579** [comment]
Oh my god, I opened VSCODE this morning and my TABNINE is working again! Of course, I also want to thank you for your help. Thank you! But I'm sorry that I can't provide you with more log information. 
P.S. can I close this issue?

**Comment by maya-tabnine** [comment]
Awesome! Glad to hear that. Contact us again anytime :)

**Comment by david-mart** [comment]
If anyone comes across the same error, here's what I did to fix it.

**Make sure you have VSCode CLI [enabled](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line) before the first step!!**
1. Install Tabnine extension and close VSCode
2. Delete Tabnine binaries
    ```zsh
    rm ~/Library/Application\ Support/Code/User/globalStorage/tabnine.tabnine-vscode 
    # VSCode won't start after this step
    ```
3. Uninstall extension manually
    ```zsh
     code --uninstall-extension TabNine.tabnine-vscode
    ````
4. Open VSCode and install extension through the Extension tab (cli didn't work for me).
