### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vasu356** [codota/tabnine-vscode#792]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.5.26`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.65.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
it is taking more than 1900ms time to run.

gz#12521

**Comment by maya-tabnine** [comment]
Hi @vasu356 we just released a new engine version 4.1.16 to beta. Would you receive beta releases on your Tabnine Hub? I think it will help.

**Comment by maya-tabnine** [comment]
Hi @vasu356, lmk if that resolved your issue!
