### ISSUE TITLE
Tabnine when typing string

### ISSUE THREAD

**Issue by frees11** [codota/tabnine-vscode#793]
Hello is it possible to also have tabnine autocompletion enabled when typing string in quotation marks and apostrophes? 

gz#12596

**Comment by maya-tabnine** [comment]
Hi @frees11, Tabnine should run with those too. Did you have any issues with it?

**Comment by frees11** [comment]
Hello, it will be more visible in this video, when I am writing associative array in php, when filling function or property name it works, but when I am writing string key it doesn't autocomplete anything 

[https://youtu.be/uMExkntAqhU](url)

**Comment by dimacodota** [comment]
hey @frees11, please open your vscode settings json file `Command Palette -> Preference: Open Settings(JSON)` and  add the following configuration: `
"editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
`

**Comment by frees11** [comment]
WOW, thanks so much @dimacodota
