### ISSUE TITLE
message [CANNOT USE these API proposals 'inlineCompletions'.]

### ISSUE THREAD

**Issue by famibee** [codota/tabnine-vscode#796]
**please complete the following information:**

- OS version: Mac Monterey
- Editor version: VSCode  1.65.2
- Programming language: [e.g. js, ts, c++]
- TabNine extension version: 3.5.36

**Editor console logs:**

CRITI Extension 'TabNine.tabnine-vscode CANNOT USE these API proposals 'inlineCompletions'. You MUST start in extension development mode or use the --enable-proposed-api command line flag

Help -> Toggle Developer Tools

**Issue Details:**

 While creating the VSCode extension, I was getting the above message when I opened DevTools. Share information.
　VSCode 拡張機能作成中、DevTools を開くと上記のメッセージが出ていた。情報共有します。

<img width="800" alt="スクリーンショット 2022-03-18 03-18 金 22 57" src="https://user-images.githubusercontent.com/16816132/159016481-688a20da-f7fa-4593-bbab-5ecbf9b1bbe5.png">
gz#12819

**Comment by dimacodota** [comment]
Hi, does the extension functions properly? Do you get any Tabnine suggestions?

**Comment by famibee** [comment]
I'm pleasure to be of some help. In normal use, such a message is displayed.
参考になりましたら幸いです。通常使用ではこのようなメッセージが出ています。
<img width="1490" alt="スクリーンショット 2022-03-23 03-23 水 19 00" src="https://user-images.githubusercontent.com/16816132/159684268-1893c1e6-a3f6-4771-a00f-975338202523.png">

**Comment by maya-tabnine** [comment]
Thanks!

**Comment by crystalfp** [comment]
The error is present also on Windows under Tabnine 3.5.45.
```
[renderer4] [critical] Extension 'TabNine.tabnine-vscode CANNOT USE these API proposals 'inlineCompletions'. You MUST start in
extension development mode or use the --enable-proposed-api command line flag
```
I don't use extension development, only normal development with VS Code 1.67.1
I receive suggestions even if many of them are not pertinent.
Thanks for looking!\
mario
