### ISSUE TITLE
VS Code - Cosmetic issue - rearrange language name aliases

### ISSUE THREAD

**Issue by pitris90** [codota/tabnine-vscode#799]
**please complete the following information:**

- OS version: Win 10
- Editor version 1.65.2:
- Programming language: C++, C, ...
- TabNine extension version: 3.5.38

**Issue Details:**

Tabnine changes default name aliases that are shown on the bottom of VS Code window. For example it changes C++ name to cpp, C name to c etc. 

I managed to change this back to names I like, but it would be nice to not override default aliases that are already in VS Code.  

I edited package.json to this look (package.json in package.zip), I would prefer if this would be default one: 
[package.zip](https://github.com/codota/tabnine-vscode/files/8336076/package.zip)

gz#12957

**Comment by bilucodota** [comment]
Hi @pitris90
Thanks for raising this issue!
I've shared it with the team. We will look into it and update.

**Comment by bilucodota** [comment]
Hi @pitris90 
The issue was fixed in the new version. Appreciate your assistance on this.
