### ISSUE TITLE
Weird suggestions

### ISSUE THREAD

**Issue by theodorton** [codota/tabnine-vscode#8]
I installed this plugin today and it has been working fine until I jumped into another project.

Getting the following suggestions, and I don't know where they're coming from:

<img width="431" alt="screenshot 2018-11-07 at 17 15 34" src="https://user-images.githubusercontent.com/874365/48144250-d2967f80-e2b0-11e8-8021-7d4b89e92c28.png">

**Comment by zxqfl** [comment]
Seems like I should add some additional filtering for long strings with numbers in them.

You might be able to fix it by creating a .ignore file (to make TabNine skip the node_modules while keeping them checked in to Git).

**Comment by theodorton** [comment]
I have the following `.gitignore`:

```
node_modules/
dist/
```
