### ISSUE TITLE
Tabnine not showing up anywhere after installing

### ISSUE THREAD

**Issue by beaver700nh** [codota/tabnine-vscode#809]
- OS version: Raspberry Pi OS Bullseye (Linux 32 bit ARM)
- Editor version 1.65.0
- Programming language: C++
- TabNine extension version: 3.5.41

Hello

I've heard that there should be a `[TabNine]` thingy in the status bar at the bottom, but it is not there for me. In the extensions tab, when I hover over TabNine, it says "This extension is enabled globally" but in the extension page itself it says this:
![screenshot_2022-04-04_20-28-07-851892247](https://user-images.githubusercontent.com/41931581/161655508-c69cef9c-47fa-44fd-8855-2e83076b8095.png)

Also, typing any `TabNine::*` command in the editor doesn't seem to do anything:
![screenshot_2022-04-04_20-23-37-714587958](https://user-images.githubusercontent.com/41931581/161655552-823bc338-ccfe-4ca4-b92b-0b3ed4312e46.png)

Can someone help please? TabNine doesn't seem to be doing anything at all!

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**
Nothing happens, it doesn't do anything at all

Help -> Toggle Developer Tools

**Issue Details:**

gz#13305

**Comment by maya-tabnine** [comment]
Hi!
1. Please try to run the engine directly - run the following command from the terminal using the right path:
`PATH_TO_ENGINE/TabNine.cmd --log_to_stderr`
The path should be: /Users/{UserName}/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/{Binary_Version}/x86_64-unknown-linux-musl/
Would you please collect the output to a file and share it with us?

2. Open VSCode settings, search "log file path", and enter a path on ‘Tabnine: Log File Path’ to get the logs. 
Something like /path/to/logs/
Restart your IDE and use it for a few minutes to let the logs flow in.
Then, you'll find a file named filename_rCURRENT.ext-<pid> in the given directory. 

This will generate your engine log from your VSCode and directly through the binary file.
Also, can you share the latest version number you have at /Users/{UserName}/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries ?
With this information, we can see if Tabnine is running or not and continue resolving this!

**Comment by beaver700nh** [comment]
Ah hello, thank you for getting back to me. Seems I have a few problems.

I don't seem to have a `tabnine.tabnine-vscode/` directory inside `globalStorage/`.

Because of this, I cannot run `TabNine.cmd` and I cannot share the latest version number.

Also, even after entering a log file path (I set it to `/home/<username>/.tabnine-log/`) and restarting VSCode, and using it for a few minutes, no such file `filename_rCURRENT.ext-` was created. Furthermore, the directory `~/.tabnine-log/` was not created either.

Am I missing something? Should I have installed something that I didn't? In the installation instructions, I was only told to run `ext install TabNine.tabnine-vscode`, which I did. Do I need to install something else too?

**Comment by maya-tabnine** [comment]
Thank you for the fast reply!

Would you try to uninstall Tabnine and open the devotool console? Click Help->Toggle Developer Tools->Console
Then reinstall Tabnine and see if you get any errors or messages there. 
Also, do you use a proxy or any firewall that can block the installation?

**Comment by beaver700nh** [comment]
Hello

No I don't think I have any proxy or firewall.

Ok so I have uninstalled TabNine and opened the dev console.
![screenshot_2022-04-06_12-19-51-565569296](https://user-images.githubusercontent.com/41931581/162021315-9c7a2433-d54e-4a58-aa61-ae6919d570f6.png)

Reinstalling now...
![screenshot_2022-04-06_12-20-50-747686383](https://user-images.githubusercontent.com/41931581/162021441-7ccae6d5-c145-4a98-85bc-c7951a56116d.png)

AHA! Well that's interesting...

**Comment by beaver700nh** [comment]
After looking through some GitHubs, it seems this is the only non-Mac Linux that is supported:
> x86_64-unknown-linux-musl

My architecture is ARM32, as stated at the top.

**Comment by beaver700nh** [comment]
It'd be great if someone could add support for ARM!

**Comment by maya-tabnine** [comment]
I haven't noticed that in the first message, sorry! You are right.
I agree with you about the notification message, and I am taking this feedback and passing it on to the team. 
And I will add your request to our backlog, so perhaps in the future we will work on it :)

**Comment by beaver700nh** [comment]
Great, thanks!

**Comment by jeffbmartinez** [comment]
Same issue 2 years later, also encountered without any error message.
Glad I stumbled upon this, but bummed tabnine doesn't work on ARM/raspberry pi.
