### ISSUE TITLE
Tabnine status bar got stuck in "Starting..."

### ISSUE THREAD

**Issue by toanpi** [codota/tabnine-vscode#814]
**please complete the following information:**

- OS version: Win 11
- Editor version 1.66.1 vscode
- Programming language: all
- TabNine extension version: 3.5.42

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page
Error: Not found
**Editor console logs:**
  ERR [Extension Host] Unhandled promise rejection:  Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:718:9)
	at Object.t.runProcess (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45657)
	at Object.t.default (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45249)
	at async t.default.startChild (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:30638)
	at async c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:167779
workbench.desktop.main.js:71 [Extension Host] Unhandled promise rejection:  Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:718:9)
	at Object.t.runProcess (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45657)
	at Object.t.default (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45249)
	at async t.default.startChild (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:30638)
	at async c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:167779
D @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1705
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3102
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:71 [Extension Host] stack trace: Error: spawn UNKNOWN	at ChildProcess.spawn (node:internal/child_process:412:11)	at Object.spawn (node:child_process:718:9)	at Object.t.runProcess (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45657)	at Object.t.default (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45249)	at async t.default.startChild (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:30638)	at async c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:167779
D @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1705
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3102
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2615 Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:718:9)
	at Object.t.runProcess (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45657)
	at Object.t.default (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:45249)
	at async t.default.startChild (c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-3.5.42\out\extension.js:17:30638)
	at async c:\Users\Dell\.vscode\extensions\tabnine.tabnine-vscode-
Help -> Toggle Developer Tools

**Issue Details:**
Tabnine status bar got stuck in "Starting..."

gz#13456

**Comment by toanpi** [comment]
Hi @yonip23 ,

Directory: C:\Users\xxx\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           3/16/2022  7:37 PM                0.0.1
d----           3/11/2022  2:34 PM                4.1.16
d----           3/14/2022  6:22 PM                4.1.18
d----           3/15/2022  7:00 PM                4.1.19
d----           3/16/2022  7:39 PM                4.1.20
-a---           3/16/2022  7:39 PM              6 .active

Last version is 4.1.20 ?

I also follow steps in https://www.tabnine.com/faq, but still not working yet.

**Comment by yonip23** [comment]
Hi, I'd like to see the **recursive** content of this dir 😬 
Sorry for not being clear enough.

> I also follow steps in https://www.tabnine.com/faq, but still not working yet.

Which faq did you try to follow?

> Last version is 4.1.20 ?

No, latest version is currently 4.1.33, and latest beta version is 4.2.1

Can you try the following?
1. close your IDE
2. remove this folder (`C:\Users\xxx\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries`)
3. restart your IDE

Kind regards

**Comment by toanpi** [comment]
Thank @yonip23,
After removing binaries folder, it works again.

**Comment by berdeter** [comment]
Just addintional info, I've stardted this command from a command prompt and it has been running for more than 10 minutes with no result :

(base) C:\Users\AL8542\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.36.0\x86_64-pc-windows-gnu>TabNine.exe --no-lsp=true --client=vscode --client-metadata clientVersion=1.84.0 pluginVersion=3.26.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark Modern vscode-theme-kind=Dark vscode-machine-id=c6c9d92892009963cf23e8495f331a836f47acfeefa9e772bd6867f518e0bb66 vscode-is-new-app-install=false vscode-session-id=3cc14884-a6ae-4577-90d2-1046b7c631e91699262573752 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true --tls_config insecure=false ide-restart-counter=7

In the log it states the command timesout.
