### ISSUE TITLE
Cannot open configuration page when developing via vscode remote development

### ISSUE THREAD

**Issue by wuliang142857** [codota/tabnine-vscode#83]
Hello.
I remotely connect to Linux on Windows via vscode's [VS Code Remote Development] (https://code.visualstudio.com/docs/remote/remote-overview).
Now I am going to configure **Api Key** via `Tabnine::Config`, but I can't open `http://linux_server:5555` in my browser. I guess because TabNine bind is the 127.0.0.1 address. Instead of 0.0.0.0 or all available IPs for this Linux machine.
Can you solve my issue?

**Comment by raulftang** [comment]
same issue here

**Comment by Anthodev** [comment]
Same too.

**Comment by hiramhuang** [comment]
Same here.

**Comment by hiramhuang** [comment]
Solution found! Just setup a port forward on port 5555 and reload the page.

**Solution A: Port forward by VS Code Remote SSH:**

![2021-03-05 at 01 58 47@2x](https://user-images.githubusercontent.com/6188371/110008327-8fe8f300-7d56-11eb-8e3b-f61ff4b0f1a8.png)

**Solution B: Port forward by command line:**

```bash
ssh -L 5555:127.0.0.1:5555 username@1.2.3.4
```

**Comment by Anthodev** [comment]
@hiramhuang yes you're right it works since vscode 1.54 because i tried already that before (1.53) but the port forwarding didn't worked well at that time.

Good thing that's working now!

**Comment by thalesfsp** [comment]
The proposed solution only works if the developer uses its LOCAL VS Code. What if developers work entirely remote, via browser?
