### ISSUE TITLE
Add option to only show completions when a keyboard shortcut is activated

### ISSUE THREAD

**Issue by benwh1** [codota/tabnine-vscode#830]
- OS version: Windows 10, Linux Mint 20
- Editor version: 1.66.2
- Programming language: Rust
- TabNine extension version: 3.5.45

I recently disabled tabnine because when I was using it, the completions were often preventing completions from rust-analyzer from showing up. It would be nice to have an option so that no completions are shown unless a keyboard shortcut is pressed. I looked through the currently available commands but didn't see such an option.

gz#14027

**Comment by boaz-codota** [comment]
Hey @benwh1 thank you for the suggestion, we are looking into that and will prioritize internally.

Could you attach some pictures where Tabnine is preventing you from getting `rust-analyzer` suggestions?

Also, if you are not using the inline mode (available through the settings), I think you might want to check that out.
