### ISSUE TITLE
can't active

### ISSUE THREAD

**Issue by z2665** [codota/tabnine-vscode#84]
I buy a license .  and I want to use it in my development.
I use vscode remote to dev. so the plug must install in the dev server machine.
but the machine connect to internet use the proxy with a white list controll by  company
so I can't active the plug.
Has any way to solve the problem? thanks

**Comment by Talent30** [comment]
same

**Comment by youness1381** [comment]
Hi, do you have WhatsApp, if you do, can I have your phone number?

‫‪JonSun30‬‏ <‪notifications@github.com‬‏> در تاریخ شنبه ۲۵ آوریل ۲۰۲۰ ساعت
۲۰:۰۶ نوشت:‬

**Comment by youness1381** [comment]
I can help you in WhatsApp


‫یونس کریمی <‪younes.mis83@gmail.com‬‏> در تاریخ شنبه ۲۵ آوریل ۲۰۲۰ ساعت
۲۰:۴۱ نوشت:‬

**Comment by HaiyiMei** [comment]
I have the same issue. Do you have solutions?
