### ISSUE TITLE
Extension issue - Long Loading Time

### ISSUE THREAD

**Issue by austin-lai** [codota/tabnine-vscode#851]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.5.49`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.67.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 507,
		"activateCallTime": 1,
		"activateResolvedTime": 5,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "TabNine.tabnine-vscode",
				"_lower": "tabnine.tabnine-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

gz#14780

**Comment by maya-tabnine** [comment]
I am not sure I understand your issue. 
Do you have a video demonstrating it? Would you please send it to support@tabnine.com and mention this issue? 
Thanks!
