### ISSUE TITLE
Extra closing brace in string

### ISSUE THREAD

**Issue by Fawxy** [codota/tabnine-vscode#86]
I noticed that an extra closing brace is added with some suggestions unnecessarily

<img width="344" alt="Screenshot 2019-07-26 at 11 31 11" src="https://user-images.githubusercontent.com/9826062/61946085-8bb0fd00-af99-11e9-8351-3804bb2c0086.png">
<img width="334" alt="Screenshot 2019-07-26 at 11 35 38" src="https://user-images.githubusercontent.com/9826062/61946086-8bb0fd00-af99-11e9-9e8c-94cbbaa9845f.png">
<img width="333" alt="Screenshot 2019-07-26 at 11 35 50" src="https://user-images.githubusercontent.com/9826062/61946087-8c499380-af99-11e9-996a-28102e1e93a7.png">
<img width="250" alt="Screenshot 2019-07-26 at 11 35 55" src="https://user-images.githubusercontent.com/9826062/61947608-8eadec80-af9d-11e9-869e-761d7c433f43.png">

I would expect the end result to be `${encodeURI(file)}`

**Comment by amircodota** [comment]
Hi @Fawxy 

It should be fixed in the latest version of tabnine for vscode. Can you verify?
