### ISSUE TITLE
tabnine shows suggestions on vs code but when i press enter key it does write the code

### ISSUE THREAD

**Issue by sadath-12** [codota/tabnine-vscode#863]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#15207

**Comment by maya-tabnine** [comment]
Hi, how can I help?
If you want to change the completion key, you need to check the settings of your VSCode. 
See [this page](https://support.tabnine.com/hc/en-us/articles/5410027913489-Change-default-key-bindings-for-autocompletion )
