### ISSUE TITLE
error

### ISSUE THREAD

**Issue by uixhamzah** [codota/tabnine-vscode#864]
**please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Editor version [e.g. 1.45.0-insider]:
- Programming language: [e.g. js, ts, c++]
- TabNine extension version:

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

gz#15224

**Comment by maya-tabnine** [comment]
Hi, how can I help?
