### ISSUE TITLE
Customized shortcut doesn't work

### ISSUE THREAD

**Issue by lethefrost** [codota/tabnine-vscode#866]
**please complete the following information:**

- OS version: macOS 12.4
- Editor version: 1.68.1
- Programming language: any
- TabNine extension version: 3.5.58

**Editor console logs:**

```js
workbench.desktop.main.js:597:
CRITI Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```
at beginning, and no other TabNine related outputs.

**Issue Details:**

I configured the shortcut `tabnine.accept-inline-suggestion` as `cmd+enter` (or just any key combination other than the default `tab`). However, I noticed that in any file of any language, the customized shortcut just doesn't work. When I press `tab` which is the default shortcut for that command, it works. But if I press the customized key combination, such as `cmd+enter`, literally nothing will happen. The program behavior looks like the shortcut customization is not working at all, so the extension is using the default shortcut.

However, this setting used to work very well and as expected a few days ago. I am not sure whether it's because of the updates of VS Code or this extension. Please have a look through it. Thank you so much!

gz#15370

**Comment by cNoveron** [comment]
Same here, same OS, same IDE, please fix!

**Comment by lethefrost** [comment]
> Same here, same OS, same IDE, please fix!

I have just tested Tabnine on Windows. This shortcut setting also fails to work on Windows, any version of VSC. I guess this bug results from some changes in the last release of Tabnine.

**Comment by Cerzal** [comment]
try installing a previous version via extension menu -> tabnine.
Then assign a key combination to editor.action.inlineSuggest.commit.
This worked for me.

**Comment by MorganGeek** [comment]
> try installing a previous version via extension menu -> tabnine.

For me the whole extension has not been working from the beginning despite I was paying for a subscription and always use the most recent version as advised in the docs, and by emails through support. I'm glad I read this comment as I could make TabNine work on MacOS, VSCode, by running a very old version.

3.5.26 is the latest VSCode extension version to work for me.
