### ISSUE TITLE
How to hide update notifications?

### ISSUE THREAD

**Issue by NatoBoram** [codota/tabnine-vscode#867]
**please complete the following information:**

- OS version: Pop!_OS 22.04 LTS x86_64
- Editor version: 1.67.0-insider
- Programming language: N/A
- TabNine extension version: v3.5.581

**Issue Details:**

TabNine outputs *a lot* of notifications and I'd like to disable some of them.

For example, here's a notification that I'd like to disable:

![image](https://user-images.githubusercontent.com/10495562/174883060-7b8236a7-af3f-43ae-932c-147566604ffd.png)

https://github.com/codota/tabnine-vscode/blob/3823b6757320243f46b6010681f66dd4f8abc436/src/preRelease/installer.ts#L41-L47

I was unable to find the setting that disables that.

gz#15414

**Comment by maya-tabnine** [comment]
This is a VSCode setting.
I looked it up online and found [this link](https://stackoverflow.com/questions/42496935/disabling-visual-studio-code-update-notification)

**Comment by NatoBoram** [comment]
You are referring to VSCode's update mechanism. I am referring to TabNine's custom notification after an update.

**Comment by dimacodota** [comment]
hey @NatoBoram, you can disable the tabnine "beta" channel  updates (`tabnine.receiveBetaChannelUpdates`)
<img width="1069" alt="Screen Shot 2022-07-11 at 0 11 32" src="https://user-images.githubusercontent.com/60742964/178162256-01543676-c088-4658-9afa-e81a64bd16a6.png">

**Comment by NatoBoram** [comment]
Do you mean that the only way to disable this specific notification is to opt out of beta?

**Comment by NatoBoram** [comment]
Do you mean that the only way to disable this specific notification is to opt out of beta?

**Comment by NatoBoram** [comment]
\*Sigh*

**Comment by NatoBoram** [comment]
Do you mean that the only way to disable this specific notification is to opt out of beta?

**Comment by NatoBoram** [comment]
Do you mean that the only way to disable this specific notification is to opt out of beta?

**Comment by NatoBoram** [comment]
Do you mean that the only way to disable this specific notification is to opt out of beta?
