### ISSUE TITLE
Enter in parentheses will automatically select the contents in parentheses

### ISSUE THREAD

**Issue by HenryTSZ** [codota/tabnine-vscode#87]
Press enter in the brackets of the intelligent prompt, and the content in the brackets will be selected by default, so that the intelligent prompt cannot be used normally in the brackets

![img](https://user-images.githubusercontent.com/55341525/77244847-bcdeeb80-6c54-11ea-9346-7d122b190434.gif)

**Comment by Danielhu229** [comment]
Same situation here.

**Comment by dimacodota** [comment]
fixed in 2.5.2
