### ISSUE TITLE
Completion issues

### ISSUE THREAD

**Issue by BladeMF** [codota/tabnine-vscode#880]
**please complete the following information:**

- OS version: Win11
- Editor version [e.g. 1.45.0-insider]: 1.69.0 insider
- Programming language: PHP
- TabNine extension version: 3.6.1

**If the issue is related to TabNine failure, please provide log files:**

I can't find the logs on that page.

**Editor console logs:**

Nothing in the console.

**Issue Details:**
1. TabNine's suggestions do not appear in the completion list, only the language server's. I am happy to provide the actual response from the language server with the completion list if that helps. TabNine's suggestions appear only as inline suggestions (although that option is not turned on in settings).
2. TabNine appears (the issue is gone when the extension is disabled) to interfere with the language server's suggestion popup: For an existing line of `$this`, (1) if I type `->` the popup does not appear, no matter how many times I delete the two symbols and type them again; (2) if I delete just the `>` and type it again, the list appears, but without TabNine's suggestions (only the inline one).

gz#16011

**Comment by BladeMF** [comment]
Yes. The actual problem is that my initial state was "Advanced=ON, Inline=OFF", which if I understand correctly is not a valid combination.

**Comment by maya-tabnine** [comment]
Ok, sorry for the trouble you experienced with that! I will add this to our faq documentation too.
