### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PratikVijayTiwari1kalki** [codota/tabnine-vscode#885]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.6.3`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.69.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

gz#16302

**Comment by maya-tabnine** [comment]
Hi what is your issue?
