### ISSUE TITLE
Feature Suggestion: suggest file name for autocomplete

### ISSUE THREAD

**Issue by HenriqueSchmitz** [codota/tabnine-vscode#887]
I have been using tabnine for a while and I love it.

I am not sure if this is the best place to add this suggestion, but I think it would be nice to bring this one up. I use tabnine for TS on VSCode and I realized that it never suggests the name of the file I just created as the name for the class or interface I am creating in that file, which almost always is the right suggestion.

If you ever have time for tackling this one I think it would be a great addition. Also thanks for the already great extension!

PS: Sorry if I am spamming the wrong place for feature suggestions

gz#16412

**Comment by maya-tabnine** [comment]
Hi, thanks for pointing this out! I will add it as a feature request. 
And don't worry, you are always welcome to contact us. User feedback is very helpful and important to us:)
