### ISSUE TITLE
Crash when trying to access the parameter windows or edit my file

### ISSUE THREAD

**Issue by Ward727a** [codota/tabnine-vscode#893]
- OS version: Windows 10
- Editor version: 1.69.2
- Programming language: TS
- TabNine extension version: 3.6.4

**If the issue is related to TabNine failure, please provide log files:**

### Can't find

**Editor console logs:**

  ERR [Extension Host] validating c:\Users\[NAME]\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.81\x86_64-pc-windows-gnu\TabNine.exe timeout
console.ts:137 

[Extension Host] validating c:\Users\[NAME]\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.81\x86_64-pc-windows-gnu\TabNine.exe timeout
console.ts:137

abstractExtensionService.ts:902 Extension host (LocalProcess) terminated unexpectedly. Code: 3758096392, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:902
log.ts:313   

ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
notificationsAlerts.ts:42 Extension host terminated unexpectedly 3 times within the last 5 minutes.
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   

ERR command 'tabnine:navigation' not found: Error: command 'tabnine:navigation' not found
    at m._tryExecuteCommand (vscode-file://vscode-app/c:/Users/[NAME]/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1685:3532)
    at m.executeCommand (vscode-file://vscode-app/c:/Users/[NAME]/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1685:3414)

**For an image of the console log:**
https://i.imgur.com/soyhiYl.png

**Issue Details:**

When I launch my VSCode and go into the TabNine windows, the window doesn't show and say that the Host Extension crashed, I tried to uninstall and re-install the extension, but nothing to do, the extension keep crashing.

**Comment by bilucodota** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/16529'>Zendesk ticket #16529</a>)</i>

**Comment by Ward727a** [comment]
@bilucodota I can't access to the related ticket via the link you provided (error 404)

**Comment by Ward727a** [comment]
Found that it's was one of my extension that make Tabnine crashed like that, IDK why, but I uninstalled it, and all work fine now!
