### ISSUE TITLE
TabNine binary timeout

### ISSUE THREAD

**Issue by jamesastound** [codota/tabnine-vscode#895]
**please complete the following information:**

- OS version: macOS Monterey 12.4
- Editor version [e.g. 1.45.0-insider]:
  Version: 1.69.2 (Universal)
  Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
  Date: 2022-07-18T16:12:57.074Z (5 days ago)
  Electron: 18.3.5
  Chromium: 100.0.4896.160
  Node.js: 16.13.2
  V8: 10.0.139.17-electron.0
  OS: Darwin arm64 21.5.0
- Programming language: all
- TabNine extension version: 3.6.5

**If the issue is related to TabNine failure, please provide log files:**

**Editor console logs:**

`CRITI Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.`

`ERR [Extension Host] validating /Users/james/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.84/aarch64-apple-darwin/TabNine timeout`

`[Extension Host] validating /Users/james/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.84/aarch64-apple-darwin/TabNine timeout`

**Issue Details:**
I am no longer receiving any hints from TabNine. The extension no longer appears in the footer toolbar.

Tried uninstalling, restarting and re-installing. Tried deleting `/Users/james/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/` and re-installing. Exact same problem remains.

gz#16543

**Comment by bilucodota** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/16543'>Zendesk ticket #16543</a>)</i>

**Comment by jamesastound** [comment]
Ran fine directly. VSCode no longer giving the timeout error. Is there anything I need to anonymize, before posting the log output?

**Comment by jamesastound** [comment]
Tabnine Hub has always opened. I appear to be getting completions on my 2019 MacBook Pro (Intel) running Montery 12.4, but not on my 2021 MacBook Pro (ARM)

Intel Mac:
![Screen Shot 2022-07-25 at 10 15 28 AM](https://user-images.githubusercontent.com/46630094/180814128-64d796d4-bf9a-46c4-b363-d408dbe31bc1.png)

ARM Mac:
![Screen Shot 2022-07-25 at 10 16 11 AM](https://user-images.githubusercontent.com/46630094/180814299-9e5fbc2f-28f0-4936-8668-bc2c0a8b9a77.png)

Tried multiple attempts to get a suggestion, but no such luck on ARM.

**Comment by jamesastound** [comment]
It did work, can't recall when it stopped, tho. I've been running TabNine on the 2021 (ARM) since I opened my account in February.

**Comment by jamesastound** [comment]
I am closing this ticket. I. guess the ARM version doesn't show any hints in the pop-up intellisence box, like the Intel. But I got the inline versions working by deleting everything and re-installing all my extensions. Still not sure what the hiccup was.
