### ISSUE TITLE
Extension fails to start - TabNine.exe timeout

### ISSUE THREAD

**Issue by ein-bandit** [codota/tabnine-vscode#900]
Hello,

- OS version: Win 10
- Editor version 1.69.2
- Programming language: c#
- TabNine extension version: 3.6.5

I installed TabNine vscode extension yesterday. All went pretty well.
But today I cannot start up the extension.

First, VsCode Intellisense did not work at all. So i disabled the extension -> Intellisense works again.

**If the issue is related to TabNine failure, please provide log files:**
Not possible, extension does not start up.

**Editor console logs:**
When i try to re-enable the extension I get the following error in vs code dev tools
![image](https://user-images.githubusercontent.com/6816384/181211000-ba5c4fae-6d2d-433a-9ea8-a7cf5d1298a6.png)

gz#16633

**Comment by maya-tabnine** [comment]
Hi, that does look odd.
Can I ask you to check a specific setting? Please reach settings and look for inline. Is it ticked?
<img width="517" alt="Screen Shot 2022-07-27 at 15 33 11" src="https://user-images.githubusercontent.com/82452749/181247522-6f3c4eda-21c1-482e-8da8-8a9825fd98ed.png">
 
Would you also try running the binary directly? See [this guide](https://support.tabnine.com/hc/en-us/articles/6246826943889-Running-Tabnine-engine-directly-)

**Comment by jeengbe** [comment]
This does not necessarily mean that something is wrong: https://github.com/codota/tabnine-vscode/blob/master/src/binary/binaryFetcher/binaryValidator.ts#L16-L19

The timeout is never cancelled, hence always errors. In most cases, `readLine.once("line")` just calls `resolve(true)` first.

**Comment by ein-bandit** [comment]
could not reproduce. can be closed
