### ISSUE TITLE
Change Inline Completions to Dropdown completions

### ISSUE THREAD

**Issue by OscarLlorente** [codota/tabnine-vscode#912]
- OS version:Ubuntu 22.04
- Editor version:vscode 1.69.2
- Programming language: Python
- TabNine extension version: 3.6.8

I am trying to change the configuration from inline completions to dropdown but since the configuration page seems to have changed in the last year I can't find it, does anyone know how to do this?

Thanks in advance

gz#16781

**Comment by maya-tabnine** [comment]
Hi see https://github.com/codota/TabNine/issues/541

For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.

**Comment by OscarLlorente** [comment]
Oh, thank you very much!
