### ISSUE TITLE
Strength or Speed settings keeps reseting to Speed 

### ISSUE THREAD

**Issue by StandingPadAnimations** [codota/tabnine-vscode#916]
- OS version: Windows 10
- Editor version VScodium 1.70 (VScodium is just VScode but without telemetry, so extensions still work)
- Programming language: Rust
- TabNine extension version: 4.4.99

Whenever I set the Strength setting to Balanced, it will always revert back to speed the moment I close the settings window (also this is more of a minor thing but it seems that Tabnine doesn't account for function signatures in its suggestions, but again that's minor)

https://user-images.githubusercontent.com/75058058/183274388-42886024-2a3c-4425-9aef-658e1e035abb.mp4

gz#16869

**Comment by maya-tabnine** [comment]
This is a known issue that I added to our backlog.
You should also know that The strength vs. speed is about to be removed from Tabnine Hub because it is irrelevant in specific model servings. Lately, we released the new hub, so things are not completely steady yet.
