### ISSUE TITLE
Config-Page opens on every :: in powershell files

### ISSUE THREAD

**Issue by Knarzi** [codota/tabnine-vscode#921]
- OS version: Win 11
- Editor version: 1.70.1:
- Programming language: Powershell
- TabNine extension version: 3.6.11

**Issue Details:**

When I use Tabnine and edit a Powershell file (vscode powershell extension is installed), then Tabnine opens the config page in the browser every time I write :: . In C#, html, css or other files this isn't happening. In the Powershell language the :: is used to access namespace and enum members, so this is a little bit annoying.

Sample:

```powershell
if ($GroupType -eq [GroupType]::Securitygroup {
    
}
```

After `[GroupType]::` the config page pops up.

gz#16985

**Comment by Knarzi** [comment]
Okay. Today the problem is gone and I can't reproduce it anymore.

**Comment by maya-tabnine** [comment]
Hi @Knarzi . Did the problem reappear since 3 days ago?

**Comment by Knarzi** [comment]
No, it does not happen again. I close the issue. Thx!
