### ISSUE TITLE
3.6.12, 3.6.13 Tabnine typing lag

### ISSUE THREAD

**Issue by Edemilorhea** [codota/tabnine-vscode#931]
**please complete the following information:**

- OS version: Win10 and Win11
- Editor version : 1.70
- Programming language: C#
- TabNine extension version: 3.6.12, 3.6.13

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

[critical] Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

Help -> Toggle Developer Tools

**Issue Details:**

If i update to 3.6.12 or 3.6.13 will Tabnine let me typing slow.
but I use 3.6.10 now is well.

![image](https://user-images.githubusercontent.com/92776711/185918502-72b307bb-4bbe-40af-9f13-9d8d3f6c16fb.png)

gz#17268

**Comment by maya-tabnine** [comment]
Hi, sorry for the late reply here :) 
Do you still experience lagging on the latest version?
And about the message, this is not a bug but an old message that we removed, so users won't get confused.
Do you still get it today?

**Comment by Edemilorhea** [comment]
I just tried it, and I feel problem still have, But C# omnisharp extension have problem in these time, So Maybe is it's problem also.

**Comment by maya-tabnine** [comment]
You should try using only the cloud model type, it uses less CPU and memory from the machine.
