### ISSUE TITLE
Hub Html code doesn't respect asExternalUri 

### ISSUE THREAD

**Issue by jeengbe** [codota/tabnine-vscode#936]
**please complete the following information:**

- TabNine extension version: 3.6.14

**If the issue is related to TabNine failure, please provide log files:**

_Type `TabNine::config` in your editor, the logs are located at the bottom of the page_ yeah we haven't come this far

**Editor console logs:**

```
GET http://localhost/static/js/main.eb6c0893.js net::ERR_ABORTED 404 (Not Found) notifications-widget:1
GET http://localhost/static/css/main.51306a6f.css net::ERR_ABORTED 404 (Not Found) tabnine-today-widget:1
````

**Issue Details:**

When running TabNine in code-server, [`asExternalUri`](https://github.com/codota/tabnine-vscode/blob/master/src/hub/hubUri.ts#L14) is correctly applied to the url for opening the hub (`http://127.0.0.1:5555/sec-enlvawapknkuowjljvht` is correctly transformed to `http://localhost/proxy/5555/sec-enlvawapknkuowjljvht`). This does however not apply to subsequent requests initiated by the then-mounted iframe.
Requests (see above) correctly error, however, manually requesting `http://localhost/proxy/5555/static/js/main.eb6c0893.js` yields the correct result.
This might not be the appropriate repository, as there may be little to do with the extension. There would need to be some sort of base_url that the binary respects when serving hub html files.

Currently, all paths are relative to the base url (`<script defer="defer" src="/static/js/main.eb6c0893.js"></script>`).

gz#17679

**Comment by jeengbe** [comment]
Update: The same applies to any subsequent requests after manually mounting the hub:
![image](https://user-images.githubusercontent.com/51749023/188218594-96bace98-169a-49ee-9d71-5b6bcacffc86.png)

**Comment by jeengbe** [comment]
Another solution would be binding TabNine to a different address (0.0.0.0), and provide a config option to the extension that allows overwriting the base path. This would allow docker to expose :5555, thus making localhost:5555 work on the client machine as well.

**Comment by amirbilu** [comment]
Hi jeengbe

We've made several fixes around this issue in the last week.

I'd really appreciate if you can try again - the issue is most likely resolved.

Please let us know if the issue persists.

Regards
Amir
<br><p><em><small>°°°</small></em></p>

**Comment by amircodota** [comment]
@jeengbe We do not currently support code-server.

This is on our roadmap though, so we'll come back here and update if the status changes

**Comment by ksylvan** [comment]
Trying this with code-server 4.8.2, code-1.72.1 and TabNine.tabnine-vscode 3.6.19 and it still does not work.
