### ISSUE TITLE
Document Formating Not Working

### ISSUE THREAD

**Issue by MrOgunga** [codota/tabnine-vscode#947]
We have written the needed data into your clipboard because it was too large to send. Please paste.

gz#18437

**Comment by MrOgunga** [comment]
I downloaded prettier and tabnine and it doesnt work.

**Comment by maya-tabnine** [comment]
Hi are you sure that prettier is causing the issue?
I tried to reprudoce but Tabnine works fine along ith prettier on my VSCode. Is the problem still happening for you?
