### ISSUE TITLE
conflict with plugin unocss

### ISSUE THREAD

**Issue by cjh-store** [codota/tabnine-vscode#952]
**please complete the following information:**

- OS version:Win 10
- Editor version [e.g. 1.45.0-insider]:1.72.0
- Programming language: vue
- TabNine extension version:3.6.15

Conflict in using plugin unocss
The prompt that causes unocss needs to enter '- 'once, then delete it, and then enter '-' to get a prompt.

gz#18576

**Comment by maya-tabnine** [comment]
Hi! We added this to our backlog.
Thanks for bringing this to our attention.
